### ISSUE TITLE
How to use Web Socket with oak

### ISSUE THREAD

**Issue by sarthaksavvy** [oakserver/oak#101]
Deno has a standard library for WebSocket, https://deno.land/std/ws

but this is used with standard http server of deno, how we can use it with oak

**Comment by arsandev** [comment]
I think it's okay to use standard http server because ws runs on a different port. So you have to serve it outside the app server. Oak also uses the standard http server in its module https://deno.land/x/oak/deps.ts.

CMIIW

**Comment by katywings** [comment]
@sarthaksavvy I figured the usage out (:, you can see a socket using oak here: https://github.com/nexojs/nexo/blob/master/devMiddleware.ts#L44

**Comment by kitsonk** [comment]
Even though this was first let's move it over to #105, as the feature makes sense and we should find a way to not need to hack around to be able to do it.
