### ISSUE TITLE
"listening" event

### ISSUE THREAD

**Issue by Ricki-BumbleDev** [oakserver/oak#104]
First of all: Dope project!

I would like to log something when the server is listening and ready to take requests.
Would it be possible to add something like a "listening" event?

Usage example:
```ts
const PORT = 8000;
const app = new Application();
app.use(...);
app.addEventListener('listening', () => console.log(`Listening at http://localhost:${PORT} 🦕`));
await app.listen({ port: PORT });
```

**Comment by kitsonk** [comment]
It is implicit in `app.listen()` that if it doesn't reject, that it is open, but yes, it is difficult to observe when it actually does open, so I can see a listen event would be useful (and it can contain the promise for the listening too).
