### ISSUE TITLE
My ugly socket workarounds

### ISSUE THREAD

**Issue by katywings** [oakserver/oak#105]
IS: Oak always responds to requests here: https://github.com/oakserver/oak/blob/master/application.ts#L198. There currently is no way to disable this during a middleware (as far as I know). So you have to keep the middleware running if you want to avoid invalidating an opened socket, resulting in workarounds like: https://github.com/nexojs/nexo/blob/20ac82e2fa5be883257928a521feacb3fb87b93c/devMiddleware.ts#L68
This workaround further results in a weird timing issue if you later want to close the server with an abortController. The timing issue then can be fixed with this even uglier workaround: https://github.com/nexojs/nexo/blob/20ac82e2fa5be883257928a521feacb3fb87b93c/devMiddleware.ts#L92

SHOULD:
Atleast make it so that the request.respond from oaks handleRequest can somehow be disabled inside a middleware. But probably better find some automatic way to disable request.respond if there is an open socket - this because the bottom related topic.

RELATED:
There is an open PR in Deno that will move the current documented socket-"for await" from the middleware into a separate non-blocking promise: https://github.com/denoland/deno/commit/36cbb4b3abcf9cb9c3134dba1ef71a0e1f95acdd#diff-ee7188edb906c603183a76c7e9a5c466R46
IF this gets merged then oaks default request.respond will probably not be compatible with the updated deno ws docs .

Let me know if I can help you on this stuff :).

**Comment by kitsonk** [comment]
So the fundamental bit is that middleware needs a way to "drop" a response?  We have `send()` to send a file (I just realised that should really be on the `context` as well, silly me...), so if we had a `context.drop()` it would drop the response, but continue to allow the middleware to process.

Is there some sort of API(s) that would make sense to allow sending back stuff over a WebSocket?  I will look into it, but if you have any strong opinions, would love to hear them.

**Comment by katywings** [comment]
No no no, you are not silly!

Personally i am openminded. Regarding sending stuff over sockets: I think that this mostly depends on the consumers business logic, I can not think of a send abstraction that wouldn't hurt flexibility, atleast on a framework level. Stuff like https://github.com/faye/faye can be amazing on library level though.

Regarding the "drop" api: this really only depends on the design philosophy of oak - or specifically how close it wants be to koa. It looks like in koa they solve the api like this: https://github.com/koajs/koa/blob/master/lib/application.js#L216

**Comment by kitsonk** [comment]
Well, I am not overly dogmatic about trying to follow koa.  There are a few things they do that I disagree with, and a few things that the could do as well.  Like the closing is pretty divergent, because koa uses the Node.js event emitters, where as Deno uses the browser standards.  Also koa is written to be strongly typed, and there are some structures they are really loose with.

I guess a property is desirable though in this case, as it can be introspected by other middleware, and even potentially changed... good ole middleware battle!  Yes respond, no don't respond, yes respond.

I am going to look more into how koa is letting access to the raw socket, as I can see how that could be beneficial.

**Comment by katywings** [comment]
@kitsonk Maybe an alternative could be that context has something like a "upgrade" method which does the following:
- if request is not upgrade: returns null
- else:
  - if socket already exists in the context: return it
  - create socket and store it in the context for "upgrade" calls in future middleware

and then in oaks handleRequest:
  - if ctx socket exists: do not request.respond

This way would not only avoid sideeffect like "noDefaultRespond" settings in context, but it also would simplify the lazy usage of the same socket in multiple middlewares. With one con: it has to be good documented since it will be pretty different from the vanilla deno ws docs.

**Comment by kitsonk** [comment]
Ok, I think I know what I would like to do after thinking about it.  I will raise it as a PR for some commentary and iteration.

**Comment by katywings** [comment]
@kitsonk Thanks a lot for the amazing solution!
