### ISSUE TITLE
Support multipart form data

### ISSUE THREAD

**Issue by lengfangbing** [oakserver/oak#109]
Sorry! I am learning English. So...
I mean this
That's the request header:
![image](https://user-images.githubusercontent.com/46396510/82666496-a0692a80-9c68-11ea-9a30-4aedc8b0bec2.png)
That's the request body:
![image](https://user-images.githubusercontent.com/46396510/82666545-bd056280-9c68-11ea-9614-fd1556f67718.png)
The type is multipart/form-data
This my router:

```javascript
export default router => {
  router.get('/getList', async ctx => {
    ctx.response.body = 'get getList';
  });
  router.post('/getList', async ctx => {
    const result = await ctx.request.body({
      contentTypes: {
        json: ['application/json'],
        form: ['multipart/form-data'],
        text: ['application/json']
      }
    });
    if(result.type === 'form'){
      console.log(result.value.get('name'));
    }
    ctx.response.body = result.value;
  });
}
```

But what I got is null, I consoled this value with for...of, the output is 

```javascript
[
  "----------------------------387832257824253405999369
Content-Disposition: form-data; name",
  ""group_id"

1659592055145472
----------------------------387832257824253405999369
Content-Dispos..."
]
```

I know this is the boundary, but how to deal whit this file type?
**Thank you very much!** : )

**Comment by lengfangbing** [comment]
I find that contentTypes contains four types : 'json', 'text', 'form', 'raw'. 
So the multipart/form-data equals form? 
![image](https://user-images.githubusercontent.com/46396510/82668262-f8556080-9c6b-11ea-987c-fda2e646bfa4.png)
I changed it but still got this issue.

**Comment by gjuoun** [comment]
> Sorry! I am learning English. So...
> I mean this
> That's the request header:
> ![image](https://user-images.githubusercontent.com/46396510/82666496-a0692a80-9c68-11ea-9a30-4aedc8b0bec2.png)
> That's the request body:
> ![image](https://user-images.githubusercontent.com/46396510/82666545-bd056280-9c68-11ea-9614-fd1556f67718.png)
> The type is multipart/form-data
> This my router:
> 
> ```js
> export default router => {
>   router.get('/getList', async ctx => {
>     ctx.response.body = 'get getList';
>   });
>   router.post('/getList', async ctx => {
>     const result = await ctx.request.body({
>       contentTypes: {
>         json: ['application/json'],
>         form: ['multipart/form-data'],
>         text: ['application/json']
>       }
>     });
>     if(result.type === 'form'){
>       console.log(result.value.get('name'));
>     }
>     ctx.response.body = result.value;
>   });
> }
> ```
> 
> But what I got is null, I consoled this value with for...of, the output is
> 
> ```js
> [
>   "----------------------------387832257824253405999369
> Content-Disposition: form-data; name",
>   ""group_id"
> 
> 1659592055145472
> ----------------------------387832257824253405999369
> Content-Dispos..."
> ]
> ```
> 
> I know this is the boundary, but how to deal whit this file type?
> **Thank you very much!** : )

The data coming from ```ctx.request.body()``` is a raw data.
You may need to find a ```multipart parser``` or write your own middleware/function.

**Comment by kitsonk** [comment]
No @gjuoun this should parse correctly.

I will look into it.

**Comment by lengfangbing** [comment]
> The data coming from `ctx.request.body()` is a raw data.
> You may need to find a `multipart parser` or write your own middleware/function.

yes, I found it. But When I find code in oak/request.ts, It has already deal with this file type. So I need before body function add a new function to deal it?right?
Thank you very much!

**Comment by lengfangbing** [comment]
> No @gjuoun this should parse correctly.
> 
> I will look into it.

Great, thank you very much:)

**Comment by gjuoun** [comment]
> No @gjuoun this should parse correctly.
> 
> 
> 
> I will look into it.

As I tested, it only returns the string of the raw form data.

**Comment by gjuoun** [comment]
> > The data coming from `ctx.request.body()` is a raw data.
> 
> > You may need to find a `multipart parser` or write your own middleware/function.
> 
> 
> 
> yes, I found it. But When I find code in oak/request.ts, It has already deal with this file type. So I need before body function add a new function to deal it?right?
> 
> Thank you very much!

Either way will do. 

But I hope there is a middleware repo so that some forks can submit their solution

**Comment by lengfangbing** [comment]
> > > The data coming from `ctx.request.body()` is a raw data.
> > 
> > 
> > > You may need to find a `multipart parser` or write your own middleware/function.
> > 
> > 
> > yes, I found it. But When I find code in oak/request.ts, It has already deal with this file type. So I need before body function add a new function to deal it?right?
> > Thank you very much!
> 
> Either way will do.
> 
> But I hope there is a middleware repo so that some forks can submit their solution

yes, ok, I will try this way, thanks a lot XD

**Comment by lengfangbing** [comment]
> No @gjuoun this should parse correctly.
> 
> I will look into it.

Hello~ I wonder why use UrlSearchParams Instance here. Is there something special you considered? 
Of course, this's ok. I just think if we can use the body.value with 'key': 'value' is better? 
So I think there is something special?
@kitsonk 
![image](https://user-images.githubusercontent.com/46396510/82746610-61e88280-9dc4-11ea-962b-54c4f79a12dc.png)

Thank you : )

**Comment by devYusuf** [comment]
@gjuoun still no solution?

**Comment by lengfangbing** [comment]
> @gjuoun still no solution?

I can use deno std library to solve formData, but it may break the oak rules. oak should deal with it.

**Comment by gjuoun** [comment]
> @gjuoun still no solution?

https://github.com/oakserver/oak/issues/114#issuecomment-633714912

**Comment by kitsonk** [comment]
@lengfangbing  Yes, dealing with multi-part form data is something oak should do without the user being aware of how it is dealt with.

**Comment by kitsonk** [comment]
I've started working on this, but it is fairly complex.  I am not convinced the `std` multi part really is a good interface, so I am going to come up with something a better better I think.

**Comment by lengfangbing** [comment]
> I've started working on this, but it is fairly complex. I am not convinced the `std` multi part really is a good interface, so I am going to come up with something a better better I think.

Sounds great~

**Comment by adahox** [comment]
> I've started working on this, but it is fairly complex. I am not convinced the `std` multi part really is a good interface, so I am going to come up with something a better better I think.

until this, whats the best  alternative to use ? there's something?

**Comment by hviana** [comment]
I also really needed this feature, so as not to break the rules of oak, I created the middleware: 
https://deno.land/x/upload_middleware_for_oak_framework
