### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by sh7dm** [oakserver/oak#11]
It will be nice to have GraphQL middleware. I'd like to help with it.

**Comment by kitsonk** [comment]
I don't see that being part of oak.  I see that as expressive middleware as a seperate project.  oak is a framework that provides some higher order concerns, like I see body parsing as part of the framework, but I see actual functionality, like understanding GraphQL as not in scope for oak.

**Comment by kitsonk** [comment]
Thanks for the feedback, but I don't think a GraphQL middleware is a direct concern of oak and best handled by some other project.
