### ISSUE TITLE
Request: Add middleware property to context

### ISSUE THREAD

**Issue by halvardssm** [oakserver/oak#113]
Hi! When using middlewares, it would be beneficial to pass along information, e.g. when authenticating. 

Example, a JWT middleware:
```
const jwtMiddleware: RouterMiddleware = async (ctx, next) => {
	await next();
	let isUnauthorized = true
	let isExpired = false

	if (ctx.request.headers.has("Authorization")) {
		const authHeader = ctx.request.headers.get("Authorization")!
		if (authHeader.startsWith("Bearer ") && authHeader.length > 7) {
			const token = authHeader.slice(7)
			const decryptedToken = await validateJwt(token, SECRET_KEY, { isThrowing: false })
			if (decryptedToken && decryptedToken.payload?.iss) {
				isUnauthorized = false
				ctx.params.CTX_USER = decryptedToken.payload.iss
			}
		}
	}

	if (isUnauthorized) {
		ctx.throw(ErrorStatus.Unauthorized, isExpired ? "Token expired" : "Authentication failed")
	}
}
```

As you can see, I use `ctx.params.CTX_USER` to pass the information to the rest of the application, but it would be better if there would be a `ctx.middleware` or something similar available to pass the information along. 

I really enjoy this module, thanks for your hard work!

**Comment by LauraBeatris** [comment]
Instead of creating a new context property, would be cleaner to pass along information in the current ```request context```

For instance:
```ctx.request.CTX_USER```

**Comment by kitsonk** [comment]
This is what `ctx.state` is for...  It can be strongly typed as well, by using the generic.  Is there something missing from that?

**Comment by LauraBeatris** [comment]
Nice!! I didn't know about ``ctx.state``, my bad 🤦‍♀️

So it won't be necessary to create a new property in context since we already have the ```ctx.state``` to handle that and it is strongly typed 🚀

**Comment by halvardssm** [comment]
Thanks! I didn't realize that `ctx.state` was used for this 😅
