### ISSUE TITLE
Application state in Routers not typed properly

### ISSUE THREAD

**Issue by Tsourdox** [oakserver/oak#115]
While using typescript and defining a state for the application like so:

```const app = new Application<AppState>()```

typings for ctx.state is not typed accordingly to AppState interface with this code

```new Router().get('/', (ctx) => ctx.state)```

Am I missing something or do the Router class need generic typings similar to Application?

While running the code the state is actually there, only the typings that are incorrect.

**Comment by kitsonk** [comment]
@Tsourdox yeah, it is an oversight.  I am doing a rewrite of the router right now that will include the ability to assert the state as a generic.

Currently though you should be able to do something like this:

```ts
new Router().get('/', (ctx: RouterContext<RouteParams, AppState>) => ctx.state);
```

**Comment by Tsourdox** [comment]
Just to give you some more insight (if needed), I'm using a simple router middleware like so:

```
export const createBook: RouterMiddleware<{}, AppState> = async (ctx) => {
    const body = await ctx.request.body()
    const book = Object.assign({}, body.value, { id: ctx.state.bookIndex++ })
    ctx.state.books.push(book)
    ctx.response.body = book
}
```

And then on my router:

```.post('/books', createBook as any)```

without the `as any` I get the following error:

![Skärmavbild 2020-05-25 kl  11 21 06](https://user-images.githubusercontent.com/17639389/82799168-e5b07680-9e79-11ea-9343-a015f2a922e4.jpg)

**Comment by kitsonk** [comment]
I believe this is fixed in master now.
