### ISSUE TITLE
Cannot get params from context

### ISSUE THREAD

**Issue by Waxoussou** [oakserver/oak#116]
It seems that get method does not handle the parameter from the url 
if I write that route 
`router.get('/book/:id', (context) => {
       // route action
})`
nothing is happening. 
I removed the '/:id' part of the string and that seems to be the issue here ... but how to indicate parameters if not that way ?

**Comment by LauraBeatris** [comment]
Hey @Waxoussou 

Can you send a snippet of your router? 

The method and the path are being correctly passed as arguments, so i don't think that the error is in there.

**Comment by kitsonk** [comment]
As stated by @LauraBeatris a more complete reproduction is required.

**Comment by davidxiao** [comment]
Hi, @kitsonk , it can get `params`, while can not use this way, any advice?
```
// Context doesn't have params
router.get('/book/:id', (context:Context) => { // route action })
```

**Comment by Waxoussou** [comment]
Thanks for the answers. 
Here, a bit more of my code : 

app.js : 
`import { Application } from './deps.js';
import errorHandler from './middlewares/errorHandler.js'
import router from './routes.js';

const port = 5050;
const app = new Application()


app.use(errorHandler)
app.use(router.routes())
app.use(router.allowedMethods())

console.log(`server running on ${port}`);

await app.listen({ port })
` 
my router (route.js) : 
`import { Router } from './deps.js';
import { getProducts, getProduct, addProduct, updateProduct, deleteProduct } from './controllers/products.js'

const router = new Router();

router.get('/api/v1/products', getProducts)
    .get('/api/v1/products/:id', getProduct)
    .post('/api/v1/products', addProduct)
    .put('/api/v1/products/:id', updateProduct)
    .delete('/api/v1/products/:id', deleteProduct)

    .get("/book/:id", (context) => {
        console.log(context.params, context.params.id)
    });


export default router;`

I've been creating my route book/:id just to test since i was not finding any params on my others routes

And finally, the products.js file which contains all the routes method related to each point  :

`
import { MongoClient } from '../deps.js'

const client = new MongoClient();
client.connectWithUri("mongodb://localhost:27017");

const db = client.database("denoTesting");
const products = db.collection("products");

// @desc Get all products  
// @route GET/api/v1/products 
const getProducts = async ({ response }) => {
    const productList = await products.find({})
    response.body = {
        success: true,
        data: productList,
    }
}

// @desc Get a product  
// @route GET/api/v1/products/:id 
const getProduct = ({ params, response }) => {
    console.log('HELLO DENO', params)

}` 

I've tried to send request with curl : ` ~ curl -X GET http://localhost:5050/api/v1/products/?id=1`
or even with Postman 
Let me know if you need anything else.
Thanks for your time ;)

**Comment by LauraBeatris** [comment]
Hi @Waxoussou :smile: 

Your error handler middleware should be placed after declaring the routes. The error will happen in one of the routes and then it will be passed to that handler. 

Also, I tested your routes and they seem to be working correctly. 

I think that you passing a ``query param`` instead of a ``route param``

```

**Comment by Waxoussou** [comment]
> Hi @Waxoussou 😄
> 
> Your error handler middleware should be placed after declaring the routes. The error will happen in one of the routes and then it will be passed to the handler.
> 
> Also, I tested your routes and they seem to be working correctly.
> 
> I think that you passing a `query param` instead of a `route param`
> 
> > I've tried to send request with curl : ~ curl -X GET http://localhost:5050/api/v1/products/?id=1
> 
> Instead of `/products/?id=1` it should be `/products/1`

thanks so much @LauraBeatris !!! indeed , I was passing query params instead ! damn' ... 
Btw, would you know how to handle query param with oak though ? 

About my error handler, it was working well even declared before the routes ... I did get errors each time i got one...  How can it be ?

**Comment by kitsonk** [comment]
> Btw, would you know how to handle query param with oak though

```ts
ctx.request.url.searchParams.get("id");
```

I can see that is getting a bit cumbersome though, and some users would expect to be able to have the `params` and these "merged".  I want to avoid creating aliases and the like, but I think a helper function that would return the searchParams as a single object optionally merged with the parsed out params would be a good idea... something that would work like this:

```ts
const query = queryParams(ctx, { mergeParams: true });
```
