### ISSUE TITLE
Middleware not working when using a router

### ISSUE THREAD

**Issue by denjucks** [oakserver/oak#118]
I placed middleware after a router and it never gets called for some reason. I want to log the status of a response. Below is the code used.

```javascript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

const router = new Router();
router.get("/", async (context, next) => {
  context.response.body = "hello world";
  await next();
});

app.use(router.routes());
app.use(router.allowedMethods());

app.use(async (context, next) => {
  console.log(context.response.toServerResponse().status);
  await next();
});

await app.listen({ port: 8000 });
```

**Comment by lengfangbing** [comment]
> I placed middleware after a router and it never gets called for some reason. I want to log the status of a response. Below is the code used.
> 
> ```js
> import { Application, Router } from "https://deno.land/x/oak/mod.ts";
> 
> const app = new Application();
> 
> const router = new Router();
> router.get("/", async (context, next) => {
>   context.response.body = "hello world";
>   await next();
> });
> 
> app.use(router.routes());
> app.use(router.allowedMethods());
> 
> app.use(async (context, next) => {
>   console.log(context.response.toServerResponse().status);
>   await next();
> });
> 
> await app.listen({ port: 8000 });
> ```

you should write middleware before route. 
you can write

```javascript
app.use(async (ctx, next) => {
    await next();
    console.log(ctx.response.status);
});

// write here  router.get().......
```

**Comment by denjucks** [comment]
I placed it before the router and it doesn't work:

```javascript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use(async (context, next) => {
    console.log(context.response.toServerResponse().status);
    await next();
  });

const router = new Router();
router.get("/", async (context, next) => {
  context.response.body = "hello world";
  await next();
});

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

I see no body in the browser and the status says 404

**Comment by kitsonk** [comment]
by doing `context.response.toServerResponse().status` you are consuming the response which means it can't be sent to the server.  I need to make that more hidden, because it shouldn't be used by middleware.  If you want to know what the status of the response is at the time... `context.response.status`, but you also want to put the `next()` before hand.

If you are depending on automatic body processing though, which will set the status when the body is processed, then that isn't quite do-able at the moment, because the status isn't set until after all the middleware has run.

**Comment by denjucks** [comment]
I thought calling `.toServerResponse()` might be an issue, good to know to avoid it! So then eventually something like this should work?

```javascript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use(async (context, next) => {
    await next();
    console.log(context.response.status);
});

const router = new Router();
router.get("/", async (context, next) => {
  context.response.body = "hello world";
});

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

**Comment by lengfangbing** [comment]
> I thought calling `.toServerResponse()` might be an issue, good to know to avoid it! So then eventually something like this should work?
> 
> ```js
> import { Application, Router } from "https://deno.land/x/oak/mod.ts";
> 
> const app = new Application();
> 
> app.use(async (context, next) => {
>     await next();
>     console.log(context.response.status);
> });
> 
> const router = new Router();
> router.get("/", async (context, next) => {
>   context.response.body = "hello world";
> });
> 
> app.use(router.routes());
> app.use(router.allowedMethods());
> 
> await app.listen({ port: 8000 });
> ```

yes, this must work. But if you dont set a status in response. You will get undefined. I also wonder why X_X

**Comment by kitsonk** [comment]
If I change `response.status` to a getter, I can put logic in there that would determine based on the current state of the response, what the `.status` would be if not set.

**Comment by kitsonk** [comment]
This is fixed in master now.  Getting `response.status` will return what should be sent in the response if it is not explicitly set.  There is also improvements so that calling `.toServerResponse()` doesn't "break" the response (though you shouldn't need to do it in most cases).

**Comment by lewislbr** [comment]
Just a quick question @kitsonk, does the placement of `await next()` matters? I've seen it in the beginning, middle and end of a body function.

PD. Thanks for your work and for Oak being similar to Koa and not Express 😜

**Comment by kitsonk** [comment]
@lewislbr https://oakserver.github.io/oak/#control-the-execution-of-middleware
