### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by egutierrez10** [oakserver/oak#124]
I am beginning to learn Deno and decided to use Oak as my middleware to build a REST API. However, I keep getting this error: 

Uncaught ReferenceError: ErrorEvent is not defined
export class ApplicationErrorEvent<S extends State> extends ErrorEvent {
                                                            ^
    at application.ts:78:61

Any ideas on how to fix it?

**Comment by kitsonk** [comment]
You need to provide more information than this, like what version of Deno you are using and what version of oak.

**Comment by egutierrez10** [comment]
It has been resolved. Required me to update Deno to the latest version. 👍
