### ISSUE TITLE
Is a directory (os error 21)

### ISSUE THREAD

**Issue by aykhanhuseyn** [oakserver/oak#125]
There is OS error when I'm using OAK. 
-------------------------------------

$ deno run --allow-net ./index.ts
Download https://deno.land/x/oak/mod.ts
error: Is a directory (os error 21)

$ deno --version
deno 1.0.2
v8 8.4.300
typescript 3.9.2

macOS Catalina 10.15.4

Additionally: 
I checked it on Windows 10 too. 

I get different error on Windows.
error: Access is denied. (os error 5)

**Comment by kitsonk** [comment]
It is hard to guess what is in `./index.ts` unless you provide it. I am afraid my mind reading skills are limited.

**Comment by aykhanhuseyn** [comment]
> It is hard to guess what is in `./index.ts` unless you provide it. I am afraid my mind reading skills are limited.

https://github.com/aykhanhuseyn/deno-oakAPI 
Can you check it pls

**Comment by kitsonk** [comment]
Deno requires fully qualified URL for modules and does not support any "magic" resolution.  Please refer to Deno documentation. https://deno.land/manual/getting_started/typescript
