### ISSUE TITLE
how to use middleware on a particular route like in express

### ISSUE THREAD

**Issue by IrfanAli17899** [oakserver/oak#128]
Hi, in express you can use middleware on a particular route by:
app.use("/", ( ) => { });
app.use("/user", router);
but here in oak you can only pass one argument in the use method of app class.
please let us if it is there or underdevelopment thanks. !!!

**Comment by kitsonk** [comment]
Please read the documentation: https://github.com/oakserver/oak#router and refer to examples: https://github.com/oakserver/oak/blob/master/examples/routingServer.ts.
