### ISSUE TITLE
the listen method can't be resolved or rejected?

### ISSUE THREAD

**Issue by warwr1ck** [oakserver/oak#129]
```
await app.listen({ port: 8000 })
console.log('listening at port 8000')
```

and the ```console.log``` won't be executed.

and my version of deno is 1.0.2
the version of oak is v4.0.0

**Comment by warwr1ck** [comment]
only when the server was closed, the ```console.log``` will be executed.

**Comment by cleverplatypus** [comment]
3 years in the issue, if it's an issue and not a feature is still there.

Maybe I'm wrong but I'd expect the behaviour of

```js
await app.listen({ port: 8000 })
```

to be: `start listening and resolve when it's ready`.

Instead, any statements after that are not executed until the server is shut down, i.e. stops listening.

If that's the intended behaviour, albeit objectionable, it should be documented. 

Cheers

**Comment by kitsonk** [comment]
It is the intended behaviour.  The listen promise only resolves when the application is no longer listening.
