### ISSUE TITLE
Router prefix

### ISSUE THREAD

**Issue by msweda** [oakserver/oak#13]
Based on the RouterOptions interface, it seems like I should be able to specify a prefix for a router by declaring a new router like so:
```
const router = new Router({
    prefix: 'example',
});
```

However, it seems the Router constructor doesn't actually do anything with the prefix router option.

I cloned the repo and fixed this for personal use. If you're interested I could create a PR. Do you already have this addition on your radar?

**Comment by kitsonk** [comment]
I do, but I haven't had the time to implement it.  It is specifically related to #6 as well in my opinion.

**Comment by msweda** [comment]
It seems I can't push my branch to the repo due to permissions.
I'd love to contribute assuming it'd help you out.

**Comment by kitsonk** [comment]
You should be able to [fork the repo into your own account and raise a pull request](https://help.github.com/en/articles/creating-a-pull-request).  Most projects don't allow contributors push access to their main repos.
