### ISSUE TITLE
error: error sending request for url (https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts)

### ISSUE THREAD

**Issue by sochishun** [oakserver/oak#133]
按照官方教程，执行命令：deno run --allow-net server.ts
运行失败，命令行出错：
error: error sending request for url (https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts): error trying to connect: dns error: 请求的名称有效，但是找不到请求的类型的数据。 (os error 11004)

**Comment by kitsonk** [comment]
This is not something related to oak.  I suspect it is a GFC issue or a local environment issue.  Retrieving the URL works perfectly fine elsewhere in the world.

**Comment by lencx** [comment]
@sochishun 
DNS Settings:
`114.114.114.114` or `8.8.8.8`

**Comment by bey6** [comment]
It's not work for me with DNS settings: `114.114.114.114`, and i am sure that i can visit the url.

so how to solve this problem?

**Comment by lencx** [comment]
Hi, I tried it, even if not set DNS, ok for.
You run `deno run --allow-net --reload server.ts`.
If it still doesn't work, paste the error output.

**Comment by bey6** [comment]
First,
I got this error when i tried to use the [view_engine@v1.3.0](https://deno.land/x/view_engine@v1.3.0),
And,
The error still when i run with `deno run --allow-net --reload server.ts`, got below :

```
error: error sending request for url (https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts): error trying to connect: dns error: The requested name is valid, but no data of 
the requested type was found. (os error 11004)
    at https://deno.land/x/oak@v6.0.0/deps.ts:43:0
```

But it works fine without view_engine template, so i think `This is not something related to oak.` is right.

There are an [issue from view_engine](https://github.com/deligenius/view-engine/issues/13), said maybe version problem, i tried, failed too.
