### ISSUE TITLE
auto attach to app instance

### ISSUE THREAD

**Issue by platinumindustries** [oakserver/oak#140]
is there any way to auto attach the router to the app instance/context once instantiated? So that we can do something like:

```
app.use(router(app))
app.route('/').get()
```

More like its done [here](https://github.com/hanrea/koa2-routing).

**Comment by kitsonk** [comment]
No. I would prefer to have a single API, and not something that mutates instances.

**Comment by platinumindustries** [comment]
That makes sense. Thanks.
