### ISSUE TITLE
question for cookies.set

### ISSUE THREAD

**Issue by autsada** [oakserver/oak#141]
Hi,

I am trying to understand the cookies.set documentation, and I am curious about this phrase **"If the applications .keys is set, then the cookie will be signed and the signature added to the response."**  My question is where to set the application .keys?

Thank you in advance. :)

**Comment by autsada** [comment]
I found the app.keys already, now just wondering if there is an example of how to send httpOnly cookie to the frontend?

Thank you.

**Comment by kitsonk** [comment]
`ctx.cookies.set("key", "value", { httpOnly: true });`
