### ISSUE TITLE
static site ... loading js files no mime type

### ISSUE THREAD

**Issue by closet6** [oakserver/oak#143]
hi, i'm getting this error when trying to host static site

the index.html is loading fine
then when trying to load the js files (app) i get:

`Loading module from “http://localhost:8000/modules/my-element.js” was blocked because of a disallowed MIME type (“”).`

my assumption was oak would set the mime type based on extension. if im right is this a bug?

if im wrong is there any documentation that shows an example of the right way to set the the mime type for all served ".js" files?

thanks

**Comment by platinumindustries** [comment]
For static file serving, you should use the [send](https://github.com/oakserver/oak#static-content) function.

**Comment by kitsonk** [comment]
@closet6 you are not providing enough information... We can't guess at what code you write.  The example static server provides content types based on extension: https://github.com/oakserver/oak/blob/master/examples/staticServer.ts.  What is not working for you when you follow that pattern?

**Comment by closet6** [comment]
ok, thanks for the info, i will report back by end of week.

**Comment by closet6** [comment]
here is the code im using:

```
  .get("/", async (context) => {
    context.cookies.set(
      "lastVisit",
      new Date().toISOString(),
      { httpOnly: true, sameSite: "strict" },
    );
    await send(context, context.request.url.pathname, {
      root: `/app/web`,
      index: "index.html",
    });
  });
```

here is the html file script loads
```


  <script type="module" src="../modules/web.js"></script>
  <script type="module" src="../modules/header.js"></script>
  <script type="module" src="../modules/footer.js"></script>
```

**Comment by kitsonk** [comment]
I am unable to reproduce this.  I modified the [static HTML in the examples](https://github.com/oakserver/oak/blob/master/examples/static/index.html) to load a JavaScript module that loads another JavaScript module and everything works fine, including getting the correct content type using the example [static server](https://github.com/oakserver/oak/blob/master/examples/staticServer.ts).

I can't see anything obviously wrong with the code you provided, so I am at a loss as to what is going wrong.

**Comment by GuilhermeVendramini** [comment]
Hi @closet6, I'm using https://deno.land/x/dejs and static files aren't called. So this is my solution:

`router
  .get("/core/themes/boostrap/assets/:folder/:file", async (context) => {
    const folder = context.params.folder;
    const file = context.params.file;
    context.response.body = await Deno.readFile(
      `${Deno.cwd()}/core/themes/bootstrap/assets/${folder}/${file}`,
    );
  });`

It will works fine!

**Comment by closet6** [comment]
thanks, im just sending something now because i haven't abandoned this, but i've been traveling.  I'll be trying to rework this this weekend.

**Comment by closet6** [comment]
tried it on Brave (chrome) and its telling me 404, so not sure if that's a red herring or not, Firefox is complaining about a mime type (above)

```
  <script type="module" src="modules/puller-web.js"></script>
  <script type="module" src="modules/header.js"></script>
  <script type="module" src="modules/footer.js"></script>
  <link rel="stylesheet" type="text/css" href="sh.min.css">
  <link rel="stylesheet" type="text/css" href="footer.css">
```

doesn't return the css either, but still sends the index.html, that's why im not sure its a 404

the modules folder and css files are in the same directory as the index.html

this is the oak output, the browser is making the requests correctly i believe:

```
api_1  | { middleware: "IF_CHANGE_HAVE_BODY", path: "/modules/puller-web.js", method: "GET" }
api_1  | { middleware: "IF_CHANGE_HAVE_BODY", path: "/modules/header.js", method: "GET" }
api_1  | { middleware: "IF_CHANGE_HAVE_BODY", path: "/modules/footer.js", method: "GET" }
api_1  | { middleware: "IF_CHANGE_HAVE_BODY", path: "/sh.min.css", method: "GET" }
api_1  | { middleware: "IF_CHANGE_HAVE_BODY", path: "/footer.css", method: "GET" }

```

console in brave:
```

GET http://localhost:8000/modules/puller-web.js net::ERR_ABORTED 404 (Not Found)
localhost/:10 
GET http://localhost:8000/modules/header.js net::ERR_ABORTED 404 (Not Found)
localhost/:11 
GET http://localhost:8000/modules/footer.js net::ERR_ABORTED 404 (Not Found)
localhost/:12 
GET http://localhost:8000/sh.min.css net::ERR_ABORTED 404 (Not Found)
localhost/:13 
GET http://localhost:8000/footer.css net::ERR_ABORTED 404 (Not Found)
```


running in container, Deno 1.0.0
if i couldn't resolve the index.html this would make more sense to me.

I took out the cookie code to just in case.

**Comment by closet6** [comment]
> Hi @closet6, I'm using https://deno.land/x/dejs and static files aren't called. So this is my solution:
> 
> ```
> router
>   .get("/core/themes/boostrap/assets/:folder/:file", async (context) => {
>     const folder = context.params.folder;
>     const file = context.params.file;
>     context.response.body = await Deno.readFile(
>       `${Deno.cwd()}/core/themes/bootstrap/assets/${folder}/${file}`,
>     );
>   });
> ```
> 
> ```
> <html>
> <head>
>   <meta charset="utf-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
>   <link href="/core/themes/boostrap/assets/css/bootstrap.min.css" rel="stylesheet">
>   <style>
>     body {
>       padding: 50px;
>     }
>   </style>
>   <title><%- title %></title>
> </head>
> <body>
> ```
> 
> It will works fine!

@GuilhermeVendramini , do i have the wrong expectations for oak server, e.g. loading multiple static files from same root directory?  Or is this a work around you are proposing?  thx

**Comment by closet6** [comment]
also if i make the send look like below, its serves the js no problem:

```
    await send(context, context.request.url.pathname, {
      root: `/app/web`,
      index: "modules/puller-web.js",
    });
```

**Comment by kitsonk** [comment]
I'm am not sure what is actionable here.  If there is still an issue, let's open a new report with a full reproduction.
