### ISSUE TITLE
How to throw error on bad type param ?

### ISSUE THREAD

**Issue by loic-roux-404** [oakserver/oak#145]
I see two issues by using the router: 
- In class/object context `this` isn't available during request, for example after `c = new Controller(); route.get('path/', c.getUser)`
- When a type error should appear with for example `userModel.exist(param.id: number)` the request continue normally

**Comment by kitsonk** [comment]
> - In class/object context `this` isn't available during request, for example after `c = new Controller(); route.get('path/', c.getUser)`

This is the behaviour of JavaScript, nothing to do with oak.  If you pass methods as references they lose their scope binding.  There are multiple solutions to this problem.

> * When a type error should appear with for example `userModel.exist(param.id: number)` the request continue normally

Again, there are sufficient JavaScript patterns for this, and not a concern for oak, but a concern for validating your data inputs.  All parameters are strings anyways, it is up to the use to attempt to coerce them into something that is meaningful.  There are lots of data abstraction and validation libraries out there, and not a concern for oak.

**Comment by loic-roux-404** [comment]
Thanks !
