### ISSUE TITLE
The second post JSON will result in 404 errors

### ISSUE THREAD

**Issue by manyuanrong** [oakserver/oak#15]
I started a server with the following code.

```ts
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

async function server() {
  const app = new Application();
  const router = new Router();
  router.post("/json", async ctx => {
    ctx.response.body = "test";
  });
  app.use(router.routes());
  await app.listen(`0.0.0.0:5000`);
}
server();
```

But when I submit requests using`POST` and `application/json`. The first time I get the right response, however, all subsequent requests will get 404 errors

However, when I use curl access, it seems normal. It only happens on the browser and postman. I guess it's related to the reuse of connections.

**Comment by bartlomieju** [comment]
This is most likely related to issues with http module in Deno standard library: denoland/deno_std#49

**Comment by kitsonk** [comment]
Sorry, I haven't been paying attention.  I will look into it, I think you are right @bartlomieju but does it mean that Oak should always consume the body when processing requests?

**Comment by bartlomieju** [comment]
@kitsonk no it shouldn't, it should be handled by `http` from standard library. I'll look into it and finish the PR.

**Comment by kitsonk** [comment]
I believe this is fixed upstream now.
