### ISSUE TITLE
Is there a way to have a SSE endpoint?

### ISSUE THREAD

**Issue by taigah** [oakserver/oak#150]
Hi, I was wondering if there is currently a good way to implement SSE using oak? I tried various hacky things like writing directly to `ctx.request.serverRequest.w` but it does not feel right.

**Comment by taigah** [comment]
I managed to pull it off but it seems rather unstable. All advice is welcome.

https://github.com/taigah/rest-api-deno/blob/6e69cbad501875a15e33ac808f6dbdd787487e1e/lib/http.ts#L10

**Comment by kitsonk** [comment]
oak should certainly abstract you from that.

I did some pondering on this.  I am going to add something like `ctx.response.getEventTarget()` which will close off the response and return an event target where `target.dispatchEvent()` would send an event to the client.

**Comment by taigah** [comment]
Seems good to me. Thanks 👍

**Comment by Starcounter-Jack** [comment]
@kitsonk 
Really looking forward to SSE support in Oak!

**Comment by kitsonk** [comment]
I have the code done, I am just writing tests.

**Comment by kitsonk** [comment]
Ok, the feature is there, including an example and documentation.  Basically:

```ts
router.get("/sse", (ctx) => {
  const target = ctx.sendEvents();
  target.dispatchMessage({ some: "data" });
});
```
