### ISSUE TITLE
How to sanitize Json with Oak?

### ISSUE THREAD

**Issue by damiantoczek** [oakserver/oak#152]
is there something similar to ExpressJS `app.use(express.json())` ?

**Comment by kitsonk** [comment]
How does `express.json()` "sanaitize" JSON?  The automatic body parsing of oak handles JSON bodies fine: https://github.com/oakserver/oak#request and an example: https://github.com/oakserver/oak/blob/master/examples/routingServer.ts#L55-L58.

Are there options of `express.json()` that you feel are missing in the automatic body parsing?

**Comment by damiantoczek** [comment]
I'm just asking because I'm worried about injection etc

**Comment by kitsonk** [comment]
What sort of injection?  `express.json()` doesn't sanitise anything.  If you are worried about `__proto__` type of injections (which I don't believe `express.json()` accounts for) then Deno doesn't suffer from that at all (see: https://github.com/denoland/deno/issues/4324).

oak doesn't currently support a "strict" mode or allows the passing of a custom reviver, like `express.json()` does, but those really don't have anything to do with "sanitising" JSON.
