### ISSUE TITLE
Is there a way to allow CORS?

### ISSUE THREAD

**Issue by LukasDrsman** [oakserver/oak#154]
Is there a way to allow cross origin resource sharing? Can I somehow set header "Access-Control-Allow-Origin" to all?

**Comment by wongjiahau** [comment]
Try this:
```
app.use((ctx, next) => {
  ctx.response.headers.set('Access-Control-Allow-Origin', '*')
})
```

**Comment by 1994619946** [comment]
@LukasDrsman @wongjiahau checkout this https://github.com/tajpouria/cors#cors
