### ISSUE TITLE
request.body().value returning a unint8array object instead of post object

### ISSUE THREAD

**Issue by ghulammustufa31** [oakserver/oak#163]
Hi, 

I am getting an issue when using router.post and retrieving request body. 

In the below code, I am getting a **Uint8array** which should be an **object** (which I'm sending through post) instead. 

`.post('/test', async (ctx) => {

        const data = await ctx.request.body();
        const val = data.value;

        console.log(val);

        ctx.response.status = 200;
        ctx.response.type = "application/json";
        ctx.response.body = val;
    })`

Please help.

**Comment by kitsonk** [comment]
To have the body parsed as JSON, the request needs to include a valid content type that gets mapped as JSON.  The content types that are there by default are: `"json"`, `"application/*+json"`, and `"application/csp-report"`.  Additional ones can be set using the `.body({ contentTypes: { json: [] } })` options.
