### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by TheFuriousSnail** [oakserver/oak#166]
First I would like to thank you for your great work and input.
Second, from my perspective directory structure is part of a project. It denotes logic and planning. oak's directory structure provides no such sense. I would suggest adding at least the following structure:
lib - for reusable components
src - oak specific code
test - tests (obviously)
This should make oak look a bit more polished with some thought put into design.

**Comment by kitsonk** [comment]
The flat structure does not indicate a lack of polish or design.
