### ISSUE TITLE
deno.land / x / oak = 404 Not Found

### ISSUE THREAD

**Issue by SquareMesh** [oakserver/oak#169]
Unable to reload Oak from master branch or visit X branch in deno land. Earlier branches are accessible i.e v5.2.0

Noticed error 12hrs before this but assumed it was my system.

**Comment by davidkhala** [comment]
This affect the basic usage document in README.md and should be marked as urgent.

**Comment by davidkhala** [comment]
With my deep investigation, the master branch has been renamed to main

BUT deno.land has not been aligned with this change. It still index it as master which response 404

**Comment by rhelenagh** [comment]
I have tried version 5.2.0, but in the end, a link is missing.


`
D:\Repository\react\server>deno run --reload   --allow-net server.js
Download https://deno.land/x/oak@v5.0.0/mod.ts
Download https://deno.land/x/oak@v5.0.0/application.ts
Download https://deno.land/x/oak@v5.0.0/context.ts
Download https://deno.land/x/oak@v5.0.0/helpers.ts
Download https://deno.land/x/oak@v5.0.0/cookies.ts
Download https://deno.land/x/oak@v5.0.0/httpError.ts
Download https://deno.land/x/oak@v5.0.0/middleware.ts
Download https://deno.land/x/oak@v5.0.0/request.ts
Download https://deno.land/x/oak@v5.0.0/response.ts
Download https://deno.land/x/oak@v5.0.0/router.ts
Download https://deno.land/x/oak@v5.0.0/send.ts
Download https://deno.land/x/oak@v5.0.0/types.d.ts
Download https://deno.land/x/oak@v5.0.0/util.ts
Download https://deno.land/x/oak@v5.0.0/deps.ts
Download https://deno.land/x/oak@v5.0.0/keyStack.ts
Download https://deno.land/x/oak@v5.0.0/isMediaType.ts
Download https://deno.land/x/oak@v5.0.0/negotiation/charset.ts
Download https://deno.land/x/oak@v5.0.0/negotiation/encoding.ts
Download https://deno.land/x/oak@v5.0.0/negotiation/language.ts
Download https://deno.land/x/oak@v5.0.0/negotiation/mediaType.ts
Download https://deno.land/std@0.53.0/hash/sha256.ts
Download https://deno.land/std@0.53.0/http/server.ts
Download https://deno.land/std@0.53.0/http/http_status.ts
Download https://deno.land/std@0.53.0/http/cookie.ts
Download https://deno.land/std@0.53.0/path/mod.ts
Download https://deno.land/std@0.53.0/testing/asserts.ts
Download https://deno.land/x/media_types@v2.3.3/mod.ts
Download https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts
Download https://deno.land/x/oak@v5.0.0/tssCompare.ts
Download https://deno.land/x/oak@v5.0.0/mediaTyper.ts
Download https://deno.land/std@0.53.0/fmt/colors.ts
Download https://deno.land/std@0.53.0/testing/diff.ts
Download https://deno.land/x/oak@v5.0.0/negotiation/common.ts
Download https://deno.land/std@0.53.0/datetime/mod.ts
Download https://deno.land/std@0.53.0/encoding/utf8.ts
Download https://deno.land/std@0.53.0/io/bufio.ts
Download https://deno.land/std@0.53.0/async/mod.ts
Download https://deno.land/std@0.53.0/http/_io.ts
Download https://deno.land/x/media_types@v2.3.3/db.ts
Download https://deno.land/x/media_types@v2.3.3/deps.ts
Download https://deno.land/std@0.53.0/path/win32.ts
Download https://deno.land/std@0.53.0/path/posix.ts
Download https://deno.land/std@0.53.0/path/common.ts
Download https://deno.land/std@0.53.0/path/separator.ts
Download https://deno.land/std@0.53.0/path/interface.ts
Download https://deno.land/std@0.53.0/path/glob.ts
Download https://deno.land/std@0.53.0/async/deferred.ts
Download https://deno.land/std@0.53.0/async/delay.ts
Download https://deno.land/std@0.53.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.53.0/path/_constants.ts
Download https://deno.land/std@0.53.0/path/_util.ts
Download https://deno.land/std@0.53.0/path/_globrex.ts
Download https://deno.land/std@0.53.0/io/util.ts
Download https://deno.land/std@0.53.0/textproto/mod.ts
Download https://deno.land/std@0.53.0/bytes/mod.ts
error: Das System kann den angegebenen Pfad nicht finden. (os error 3)`

OS: Windows 10
Deno version 1.0.3

**Comment by kitsonk** [comment]
@rhelenagh it looks like you need to clear your cache.

@SquareMesh as said, ideally you wouldn't use the main branch for code.

@davidkhala this is being address in denoland/deno_website2#1130

**Comment by rhelenagh** [comment]
@kitsonk Could you please tell me how I clean my cache?

**Comment by rhelenagh** [comment]
@kitsonk 
Workaround
- Update Deno to version 1.1.0
- Use import {Application} from https://deno.land/x/oak@v5.2.0/mod.ts;
- deno run --reload --allow-net server.js

Works!

**Comment by kitsonk** [comment]
I meant to say, reload (`deno run --reload`) as you discovered.

**Comment by MichelDiz** [comment]
none solutions found here and other places works
```
deno cache https://deno.land/x/oak/mod.ts
Download https://deno.land/x/oak/mod.ts
error: Import 'https://deno.land/x/oak/mod.ts' failed: 404 Not Found
```

oak@v5.2.0 works in part.
```
deno cache https://deno.land/x/oak@v5.2.0/mod.ts
```
but when I gonna start it...
```
npm start
opening browser...
Download https://deno.land/x/oak@v5.2.0/mod.ts;
Download https://deno.land/std/path/mod.ts
error: Import 'https://deno.land/x/oak@v5.2.0/mod.ts;' failed: 404 Not Found
```

**Comment by MatthiasKainer** [comment]
I created a pull request to help with the fact that the readme/docs are off at the moment, hoping to help people that try to play with `oak` for the first time like myself a few minutes ago

**Comment by lucacasonato** [comment]
Fixed upstream in deno.land/x now :-)
