### ISSUE TITLE
Oak website returning 404

### ISSUE THREAD

**Issue by captDaylight** [oakserver/oak#172]
Link is in the repo description: https://oakserver.github.io/oak/

**Comment by kitsonk** [comment]
Yes, I am aware (https://twitter.com/kitsonk/status/1273198753927753728).  It appears GitHub Pages uses a hardcoded branch name versus the default branch on the repository.  Trying to figure out the best way to deal with it.

**Comment by odziem** [comment]
Hey @kitsonk does changing the publishing source in the repo settings fix this?

https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

It does look like a bug with GitHub, probably related to not updating the publishing source when the default branch is updated?

**Comment by kitsonk** [comment]
They are going to fix it: https://github.community/t/publishing-with-pages-moving-master-to-main/118389.

Keeping a `gh-pages` branch is not something I want to do, I want the pages to exist in the default branch for the repo, so it doesn't require switching branches to update.  I will just restore the `master` branch for now so it publishes.

**Comment by kitsonk** [comment]
GitHub can now be published of any branch.
