### ISSUE TITLE
ctx.state consistent across all requests

### ISSUE THREAD

**Issue by los-ko** [oakserver/oak#176]
I would like to use ctx.state isolated for each request, is this possible without creating a "session" map?
for example:
`
ctx.state.session={
uuid_ses1:{val:1},
uuid_ses2:{val:1},
uuid_ses3:{val:3}
}
`
With this approach I will need to create a UUID for the current session, how could I achieve this without sending it like an auth token?

Sorry if this is a bad question.

**Comment by kitsonk** [comment]
You don't want state to be isolated for each request.  A session would be multiple requests.  The context itself is isolated to a single request.  Setting a cookie with a session identifier is the way you ensure that multiple requests get associated with the same session.

**Comment by los-ko** [comment]
What I mean by session is a single request (its not the right term sorry). How should I pass isolated data (from all other requests) to an other middleware without creating a session for that request?
for example:
`
app.use(middleware1, middleware2)
`
where middleware1 creates the right data format for middleware2

**Comment by gjuoun** [comment]
You can use type merging to define your own custom property in the context
