### ISSUE TITLE
Getting the ip of the client on each request

### ISSUE THREAD

**Issue by emrebicer** [oakserver/oak#177]
I want to get the client's IP address on each request to the server. In my routes, I have tried accessing the clients IP address as follow;
```javascript
.get('mycustompath', async (context) => {

    const CLIENT_IP = context.request.ip
    // Continue processing the request...

})
```
This method always returns an IP address, on the local server it returns 127.0.0.1 as expected, but when I deploy my application to a real server for hosting (currently I am using Heroku), according to my tests it doesn't get the correct IP address of the client. Also, the found IP address for the same client changes in a small amount of time (a minute or so). 
## My questions
* Is this expected behavior for "context.request.ip"?
* Why does this IP always change?
* Can I access the client's actual IP by another approach?

**Comment by kitsonk** [comment]
It is likely you are behind a proxy with workloads on Heroku.  `context.request.ip` by default it the IP reported by the connection.  If you pass `new Application({ proxy: true })` oak will try to use the request headers to determine the reported IP.
