### ISSUE TITLE
Publish oak to nest.land

### ISSUE THREAD

**Issue by MartonDev** [oakserver/oak#178]
[Nest.land](https://nest.land) is a growing ecosystem of Deno modules. It is a blockchain based package-registry, meaning that any pushed module will stay online, and no one will be able to remove it. This is especially useful and important regarding the url-based imports in Deno and most importantly, security. 
Even though Nest.land is in beta, it is really powerful and also faster than the github servers ([deno.land/x](https://deno.land/x)) just rewrites the module url to `raw.githubusercontent.com`.

More information is available on https://nest.land/docs

**Comment by kitsonk** [comment]
At this point in time, I am personally not interested.  Thank you.
