### ISSUE TITLE
Routes with accented characters in the path are not matched

### ISSUE THREAD

**Issue by taigah** [oakserver/oak#179]
# Minimal example

```javascript
import { Application, Router } from 'https://deno.land/x/oak/mod.ts'

const app = new Application()

const router = new Router()

router.get('/créer', async (ctx) => {
  ctx.response.body = 'foo'
})

app.use(router.routes())
app.use(router.allowedMethods())

await app.listen({ port: 8080 })
```

# Expected behaviour

We should receive `foo` on `http://localhost:8080/créer`.

# Actual behaviour

We get a 404 not found error.

# Fix

The bug lies in the fact that when one makes a request to `/créer` the path received is URL encoded as such: `/cr%C3%A9er` and thus is not properly matched by the regexp of the route.

We can fix it by replacing this line
https://github.com/oakserver/oak/blob/467346f75d270fe2564d1c74a378e0c3dc97ac9d/router.ts#L822

by

```typescript
const path = decodeURIComponent(this.#opts.routerPath ?? ctx.routerPath ?? pathname);
```

altough I don't know if that's the proper way to do. Maybe it's an issue with the std http server?

**Comment by taigah** [comment]
Ok so apparently, express and koa have the same issue

```javascript
const express = require('express')
const app = express()

app.get('/créer', function (req, res) {
  res.send('Hello World!')
})

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})

```

```javascript
const Koa = require('koa')
const app = new Koa()
const Router = require('koa-router')

const router = new Router()

router.get('/créer', ctx => {
  ctx.body = 'foo'
})

app.use(router.routes())
app.use(router.allowedMethods())

app.listen(4477)
```

So I guess that may not be considered a bug although it seems weird to me. So, what should one do to create a route with special characters? Should we encode the path when registering the route?

```typescript
router.get('/cr%C3%A9er', ...)
```

I couldn't find a definitive answer to that for express and koa.

**Comment by kitsonk** [comment]
I'm going to label it a bug, since in the browser it continues to display the unencoded chars as part of the route.  I am not sure the best solution yet.

**Comment by taigah** [comment]
If we decide to decode the path, we might consider this question:

Should `/` and `%2F` be equivalent? There are sites that seem to treat them equally

* Youtube [feed/subscriptions](https://www.youtube.com/feed%2Fsubscriptions), [ytimg](https://s.ytimg.com/yts/img%2Ffavicon_32-vflOogEID.png)
* Google [logo](https://www.google.com/images/branding/googlelogo/2x%2Fgooglelogo_color_272x92dp.png)
* Github Assets [logo](https://github.githubassets.com/images/modules/open_graph%2Fgithub-logo.png)
* Quora [about/privacy](https://www.quora.com/about%2Fprivacy)

and sites that treat them differently

* Twitter [i/bookmarks](https://twitter.com/i%2Fbookmarks)
* Github [oakserver/oak](https://github.com/oakserver%2Foak)
* Medium [article](https://medium.com/code-85%2Fgetting-started-with-deno-815cb40be0c2)
* Twitch [gmhikaru/about](https://www.twitch.tv/gmhikaru%2Fabout)

There might be other quirks to take into account.
