### ISSUE TITLE
Unpin deno_std dependencies

### ISSUE THREAD

**Issue by jeroenptrs** [oakserver/oak#18]
I'm not suggesting to disregard the deno_std version altogether, but ass of right now - without #19 -`oak` is incompatible with the latest version of Deno because all deps are pinned to v0.9.0.  Obviously there are major benefits to having releases pinned to the Deno runtime version it was developed for, but it would be nice to at least have a version of `oak` without the dependencies pinned to a specific Deno version.

This could be in the form of the `master` branch or a `latest`/`unpinned` tagged release that keeps getting updated.

**Comment by serverhiccups** [comment]
BTW, the std update pull has been moved into it's own branch so the pull is now #19.

**Comment by kitsonk** [comment]
I unpinned it before and there then are breaking changes in `deno_std`, so we need to pin, but I also need to keep updating with each release of Deno.

**Comment by jeroenptrs** [comment]
> I unpinned it before and there then are breaking changes in deno_std, so we need to pin
It would be nice to have releases as pinned but maybe an unpinned tag as well 😬 

> but I also need to keep updating with each release of Deno
maybe this could be automated? Something like renovate/greenkeeper but for deno pkgs

**Comment by kitsonk** [comment]
> It would be nice to have releases as pinned but maybe an unpinned tag as well 😬

I guess I could keep master unpinned and when when we cut a release, pin it.  I have been tagging releases with updates.

> maybe this could be automated? Something like renovate/greenkeeper but for deno pkgs

Not with the way the changes break at this stage.  Sometimes it is just `deno_std` <-> Deno, sometimes it is something in `deno_std` <-> `oak`, sometimes it is Deno <-> `oak`. 🤷‍♂ Also sometimes Ry isn't tagging a `deno_std` release quickly after a Deno release, and so sometimes upgrading is hard.  I think when things get more stable...

**Comment by jeroenptrs** [comment]
> lso sometimes Ry isn't tagging a deno_std release quickly after a Deno release

Case in point: https://deno.land/std@v0.10.0 is still untagged 😂 (which sparked this issue)

**Comment by kitsonk** [comment]
I think we just will need to keep pinning for a bit longer until Deno and std are merged at least.
