### ISSUE TITLE
How can I use regex while defining path match in Route component ?

### ISSUE THREAD

**Issue by mkkhedawat** [oakserver/oak#184]
Looking for something similar to 
```
router.all(/^yo.*$/, async (ctx: RouterContext) => {})
```

Type Error I get 
```
Argument of type 'RegExp' is not assignable to parameter of type 'string'.
```

**Comment by kitsonk** [comment]
I am not sure you want a raw regular expression to be honest, as there are some expectations and conventions about the parsing of the capturing groups and how the routes get done.

The underlying library that parses the route (https://github.com/pillarjs/path-to-regexp) supports effectively almost anything that you would want to express in a regular expression in a string format.  Is there something that it doesn't support you want to accomplish?

**Comment by kitsonk** [comment]
I am going to close this as `wontfix` for now, as I think there is enough matching capability in the expression of the `path-to-regexp` library to meet most matching needs and supporting a native RegEx would cause all sorts of challenges in the matching algorithm as the RegEx needs to be constructed in very specific ways to ensure that parameters in the path can be parsed out and returned in the context.

If there is a specific pattern that can't be expressed in the `path-to-regexp` syntax then it is worth debating.
