### ISSUE TITLE
Dispatching server-send events in quick succession causes a short write error

### ISSUE THREAD

**Issue by GitHubJasper** [oakserver/oak#185]
When dispatching two events it is possible for the second event to start writing before the first one was flushed.
This causes a difference in number of bytes used in the buffer and that were written, which is displayed as a short write error.

```
Error: Short write
    at BufWriter.checkBytesWritten (https://deno.land/std@0.58.0/io/bufio.ts:436:18)
    at BufWriter.flush (https://deno.land/std@0.58.0/io/bufio.ts:487:10)
    at async ServerSentEventTarget.#send (https://deno.land/x/oak@v5.3.1/server_sent_event.ts:114:7)
```

Think a solution would be to let `dispatchEvent`/`dispatchMessage` return a promise so that it can be awaited to make sure the previous event was flushed.

**Comment by kitsonk** [comment]
Thanks for raising this and the PR.  It should "just work" without needing to add APIs or require things to occur externally.  I have made a change that should resolve the issue.
