### ISSUE TITLE
.throw() cannot handle 500 error with custom message

### ISSUE THREAD

**Issue by killvung** [oakserver/oak#189]
I was using `context.throw()` in my middleware to handle errors, but seems like it does not process custom messages for 500 related errors 

Reproduce:
In my middleware, I have a try catch statement to catch any errors in the server 
```
app.use(async (context, next) => {
    try {
        await next();
    } catch (_) {
        context.throw(500, 'Oak sever error')
    }
});
```
Expected: Screen displays `Oak server error`
Instead: Screen displays `Internal Server Error`

**Comment by kitsonk** [comment]
This is working as designed.  Specifically with 5XX errors default to `.expose = false` to prevent accidental leaking of security information.  See the documentation: https://doc.deno.land/https/deno.land/x/oak/mod.ts#HttpError.  When `.expose = false` then the `.message` is not sent to the client.

**Comment by killvung** [comment]
I see. I learned something new.
Thanks for the info
