### ISSUE TITLE
add array of middleware in router

### ISSUE THREAD

**Issue by fauzan121002** [oakserver/oak#190]
add array of middleware so we can simply pass multiple middleware in one variable.

const onevar: any = [
  async (ctx: Context, next: any) => {
    console.log('mantap');
  
    await next();
  },
  async (ctx: Context, next: any) => {
    console.log('keren');
  
    await next();
  }
]

router.get('/percobaan',onevar,(ctx: Context) => {
  ctx.response.body = "percobaan";
});

**Comment by fauzan121002** [comment]
`/**
 * Expose compositor.
 */


/**
 * Compose `middleware` returning
 * a fully valid middleware comprised
 * of all those which are passed.
 *
 * @param {Array} middleware
 * @return {Function}
 * @api public
 */

export default function compose (middleware) {
  if (!Array.isArray(middleware)) throw new TypeError('Middleware stack must be an array!')
  for (const fn of middleware) {
    if (typeof fn !== 'function') throw new TypeError('Middleware must be composed of functions!')
  }

  /**
   * @param {Object} context
   * @return {Promise}
   * @api public
   */

  return function (context, next) {
    // last called middleware #
    let index = -1
    return dispatch(0)
    function dispatch (i) {
      if (i <= index) return Promise.reject(new Error('next() called multiple times'))
      index = i
      let fn = middleware[i]
      if (i === middleware.length) fn = next
      if (!fn) return Promise.resolve()
      try {
        return Promise.resolve(fn(context, dispatch.bind(null, i + 1)));
      } catch (err) {
        return Promise.reject(err)
      }
    }
  }
}`

**Comment by fauzan121002** [comment]
`ts
/**
 * Expose compositor.
 */


/**
 * Compose `middleware` returning
 * a fully valid middleware comprised
 * of all those which are passed.
 *
 * @param {Array} middleware
 * @return {Function}
 * @api public
 */

export default function compose (middleware) {
  if (!Array.isArray(middleware)) throw new TypeError('Middleware stack must be an array!')
  for (const fn of middleware) {
    if (typeof fn !== 'function') throw new TypeError('Middleware must be composed of functions!')
  }

  /**
   * @param {Object} context
   * @return {Promise}
   * @api public
   */

  return function (context, next) {
    // last called middleware #
    let index = -1
    return dispatch(0)
    function dispatch (i) {
      if (i <= index) return Promise.reject(new Error('next() called multiple times'))
      index = i
      let fn = middleware[i]
      if (i === middleware.length) fn = next
      if (!fn) return Promise.resolve()
      try {
        return Promise.resolve(fn(context, dispatch.bind(null, i + 1)));
      } catch (err) {
        return Promise.reject(err)
      }
    }
  }
}
`

**Comment by fauzan121002** [comment]
https://raw.githubusercontent.com/marcosc90/oak-compose/master/index.js maybe this gonna help

**Comment by kitsonk** [comment]
I am not sure why you would need that, since oak contains it itself: https://doc.deno.land/https/deno.land/x/oak/mod.ts#composeMiddleware

Maybe @marcosc90 wasn't aware that it already existed.

**Comment by marcosc90** [comment]
Indeed @kitsonk wasn't aware of it. I'll archive my fork of koa-compose.
