### ISSUE TITLE
request.body() should allow to access data in multiple ways

### ISSUE THREAD

**Issue by esquevin** [oakserver/oak#191]
Currently I cannot recover both the text value of the body and the parsed json.
As soon as I access the body once, it'll automatically returns what it thinks is best for me.

I'm trying to verify an API call with a signature based on a hash of the body text, even though this body is a json document.

I wanted to write a verify middleware that'd give me the body as plain text.
And after that I need a middleware that'll access the body as json.

Those 2 doesn't have to be aware of each other.

I have not been able to figure out a way to access this properly, in a clean and isolated way :/

In this repo, accessing the body always returned the body in multiple forms: https://github.com/deniosoftware/deno-slack/blob/master/util.ts#L40

**Comment by kitsonk** [comment]
The is the whole intent, to automatically process the body.  I would argue that is the main purpose of a framework, to abstract people from the gory details.

There is already the `await ctx.request.body({ asReader: true });` which will return a `Deno.Reader` interface to consume the body.  I think it makes sense to allow `await ctx.request.body({ asRaw: true });` which will return a `Uint8Array` of the body which can be left up to the consumer to do with as they wish.

That being said, it might make sense to make the `.value` actually be lazy, and provide some helper functions which would convert the body to other forms, but I would still want to keep the body return value as is at the moment, because not having to think about reading the body off the wire, the content-type, etc. is why people use frameworks.

**Comment by esquevin** [comment]
You are obviously right, framework should make things simpler.
My concern is that Oak currently is not abstracting but _removing_ details. Either that or I could not figure out how to do what I wanted…

I want to process a slack api request with 2 middlewares:
- the first one should verify the signature of the request
```javscript
  async (ctx, next) => {
    // FIXME We need the body text to verify the signature
    // https://api.slack.com/authentication/verifying-requests-from-slack     
    // QUESTION how can I get the body text ?
    const body_text = ????
    if (
      !verify(
        ctx.request.headers.get("X-Slack-Signature") || "",
        SIGNING_SECRET,
        ctx.request.headers.get("X-Slack-Request-Timestamp") || "",
        body_text,
      )
    ) {
      throw new Error("Invalid signature");
    }

    await next();
  };
```
- the second one should implement the logic of the api endpoint
```javscript
  async (ctx, next) => {
    // We want to access the parsed data
    // We don't need to be aware that the body has been read beforehand
    // Currently this'll return the cached this.#body from the request, or raise an error if it's been requested with a header.
    const body = ctx.request.body()

    // code goes here [...]

    ctx.response.body = {}
  };
```

I'm affraid that currently Oak removes too much control from me.

I came from a python/django background and what they did is expose the raw text on the body property and *added* properties for the parsed body. Whereas I felt that your `request.body()` is destructive and lose informations.
https://docs.djangoproject.com/en/3.0/ref/request-response/


Hopefully I've made my point clearer. I'd like to be able to access in a deterministic way both the text body and the json body.  

Accessing the Deno.Reader doesn't feel adequate to me since it'd mean that in order to read the text body w

**Comment by kitsonk** [comment]
I have refactored `ctx.request.body()` and I have it in the `release-6` branch (as it is a breaking change and I didn't want to break the main branch yet until I was ready to release potentially more breaking change in that branch).

Take a look at the documentation for `.body()` in the README on that branch: https://github.com/oakserver/oak/tree/release-6#request

You should be able to take it for a spin by import from: `https://deno.land/x/oak@release-6/mod.ts`

**Comment by greenya** [comment]
Hello. I'm not sure but for some reason the example on main page is not working. I installed Deno and trying to run the example:
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```
Gives me:
```
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
        sorted: true,
        ~~~~~~~~~~~~
    at https://deno.land/std@0.61.0/testing/asserts.ts:26:9
```
Thank you for any hints.
P.S.: and sorry if its not related to this issue (topic).

**Comment by kitsonk** [comment]
@greenya thanks, I forgot to update the examples there.
