### ISSUE TITLE
Calling router method dynamicaly

### ISSUE THREAD

**Issue by nicDamours** [oakserver/oak#193]
Hi, I'm trying to build a way to achieve routing via decorator, and I'm facing an issue while trying to call the router method dynamicaly.

I tried using the `call` function on the router with a dynamic property accessor : 
```Typescript
const router = new Router();
const method = 'get';
router[method].call({}, 'myRoute', (context) => { /* ... */ });
```
But I got a compilation error regarding the private method `#useVerb`.

I then tried to call the method in a more _basic_  way by casting it as `any` and then using parenthesis to call the function.
```Typescript
const router = new Router();
const method = 'get';
(router[method] as any)('myRoute', (context) => { /* ... */ });
``` 
While this did not throw compilation error, I was not able to register the route properly. When trying to access to the route, it does not execute the code.

Is there something I'm missing here ?

**Comment by kitsonk** [comment]
Why are you trying to pass an empty object as the `thisArg`? Does this not work?  

```ts
router[method].call(router, 'myRoute', (context) => { /* ... */ });
```

**Comment by nicDamours** [comment]
@kitsonk By passing the `router` as the `thisArg` of the `call` function, I was able to compile my code with no compilation error. However, the result is the same, i'm still having a 404 not found error.

**Comment by kitsonk** [comment]
I am totally unclear what you are trying to do, and you aren't providing any code that indicates how the 404 error occurs.  It is really hard to guess.

Those methods register middleware with the router, they don't "run" the middleware.  And also, route names invariably start with a `/`.

**Comment by nicDamours** [comment]
I understand, I'm having trouble explaining my situation aswell. I will try to do more tests and come back with something a little bit more easy to understand. Thank you very much for your time.
