### ISSUE TITLE
Middleware returning response status as 404 always

### ISSUE THREAD

**Issue by avudaiappan-cse** [oakserver/oak#197]
**app.js**

import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import { renderFileToString } from "https://deno.land/x/dejs/mod.ts";

const router = new Router();

router.get("/", async (ctx) => {
  ctx.response.type = "text/html";
  ctx.response.body = await renderFileToString(
    `${Deno.cwd()}/public/main.ejs`,
    {
      title: "Home",
    }
  );
});

router.get("/about", async (ctx) => {
  ctx.response.type = "text/html";
  ctx.response.body = await renderFileToString("./public/main.ejs", {
    title: "about",
  });
});

const app = new Application();

app.use(async (ctx, next) => {
  console.log(ctx.response.status); // returning 404
  console.log(ctx.request.method); // returning GET
  await next();
});

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 4000 });

**Comment by kitsonk** [comment]
The first middleware you register is the one where you are logging the status and then awaiting the rest of the middleware.  At that point of course the response is a 404.  If you want the final status, you should move `await next();` to the top of that first middleware so the logging happens _after_ all the other middleware processes.
