### ISSUE TITLE
🐞 Can't run examples

### ISSUE THREAD

**Issue by BevanR** [oakserver/oak#20]
Both of the [examples](https://deno.land/x/oak/README.md) fail with both Deno 0.10 and 0.11 with the following errors;

```
$ deno index.ts --allow-read --allow-net
Compile file:///Users/bevan/projects/denoworld/index.ts

error TS2694: Namespace 'Deno' has no exported member 'ReadResult'.

► https://deno.land/std@v0.9.0/io/bufio.ts:7:24

7 type ReadResult = Deno.ReadResult;
                         ~~~~~~~~~~

error TS2339: Property 'nread' does not exist on type 'number'.

► https://deno.land/std@v0.9.0/io/bufio.ts:134:19

134         assert(rr.nread >= 0, "negative read");
                      ~~~~~


Found 2 errors.
```

On macos 10.13.6 High Sierra;

```
$ deno version
deno: 0.12.0
v8: 7.7.200
typescript: 3.5.1
```

**Comment by kitsonk** [comment]
It looks like you haven't reloaded your cache.

Master would be using `std@0.12.0` and not `std@0.9.0` as pointed out in the bug.  If you had run the demos before, this would explain the behaviour.  Try `$ deno --reload --allow-read --allow-net index.ts `.
