### ISSUE TITLE
oak breaks in deno v1.2.0

### ISSUE THREAD

**Issue by buttercubz** [oakserver/oak#200]
I was trying to cache oak using the new version and I get this error.

![img](https://i.ibb.co/p3m3PJn/Capture.jpg)

**deno info:**
- deno 1.2.0
- v8 8.5.216
- typescript 3.9.2

**Comment by horihiro** [comment]
std@0.60.0 is referred at followings in oak and media_types.

  - https://github.com/oakserver/oak/blob/main/application.ts#L19-L20
  - https://github.com/oakserver/media_types/blob/main/deps.ts#L3

It seems that deno 1.2.0 works by fixing above

**Comment by kitsonk** [comment]
oak uses a pinned `std` and there were breaking changes.  Give me a few minutes since I woke up to push a new version with upgrades.

**Comment by kitsonk** [comment]
The main branch is working again.  I will tag some releases in a little bit.
