### ISSUE TITLE
typescript issue

### ISSUE THREAD

**Issue by blubbll** [oakserver/oak#202]
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
        sorted: true,
        ~~~~~~~~~~~~
    at https://deno.land/std@0.61.0/testing/asserts.ts:26:9


was trying out a basic example

```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const app = new Application();
const router = new Router();

app.use(router.routes());
app.listen({ port: 80 });
```

**Comment by srepollock** [comment]
I found this on the main denoland/deno](https://github.com):
> Replace
> 
> `import { assert } from "https://deno.land/std/testing/asserts.ts";`
> 
> with
> 
> `import { assert } from "https://deno.land/std@0.60.0/testing/asserts.ts";`
> 
> [reference](https://github.com/denoland/deno/issues/6705#issuecomment-657109090)

Which was changed in one of [today's commit's](https://github.com/oakserver/oak/commit/d8674d13ea61a56581b1d40ea692fcaab5f3de5a).

I have left a comment on the line with a link to the fix referenced.

**Comment by kitsonk** [comment]
The main branch only supports Deno 1.2.0.  What version of Deno are you using?

**Comment by blubbll** [comment]
1.0.0 sorry

**Comment by blubbll** [comment]
This worked, but the console now says

Check file:///app/index.ts.js 

in red (formatted as error). is this normal?

**Comment by kitsonk** [comment]
The `Check ...` is to be expected, but the colours are supposed to be green, but I doubt it is anything to do with oak.
