### ISSUE TITLE
How to support content ranges

### ISSUE THREAD

**Issue by mekwall** [oakserver/oak#203]
I am trying to implement support for [content ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) but I can't figure out how to stream only a part of a file. Since it needs to support large files copying to a buffer is not viable.

If anyone can give me any pointers I'd be happy to create a PR to add range support in the [send](https://github.com/oakserver/oak/blob/main/send.ts#L72).

**Comment by kitsonk** [comment]
Hmmm... that seems like an interesting feature to have.  I would have to think about it a bit to be able to give good advice on how to proceed with a PR.

Let's start with the use case first.  So you are responding to a request, what do you want to send in the body and what do the headers need to look like?  If you can tell me specifically what the body would look like, I can help you figure out how to make it happen.

**Comment by mekwall** [comment]
I want to be able to serve large video files to the browser in multiple chunks using content ranges and HTTP status 206. All current browsers support this out of the box and will try to utilize it if the server supports it. [koa-range](https://github.com/minaxorg/koa-range/blob/master/src/index.js) might give you some ideas.

What I'm struggling with is how to stream parts of a file directly to `response.body` using deno. The other stuff is pretty straight forward.

**Comment by kitsonk** [comment]
It is just that easy in Deno... if you look at `send.ts`.  Basically all files are "steams"/"buffers" in Deno by default.  While there is the abstraction of oak there, essentially we are just passing the `Deno.Reader` to the body and that goes out over the socket:

https://github.com/oakserver/oak/blob/2f7643a04460ce1b407066d04554ab787e967050/send.ts#L168-L170

So what we are talking about doing is chunking up the data a bit more and providing headers to indicate the "chunks" in the response.  Feels like it should just be built into `send` as an option, like `chunkSize: number` and that would do a state on the file being sent, figure out what the `Content-Range` headers need to be, set those, and then read the chunks from the file and write them out to a [BufWriter](https://doc.deno.land/https/deno.land/std/io/bufio.ts#BufWriter) which is what you return in the body (I think).

It is something that would be relatively straight forward for me to add now that I understand what you were aiming for and the feature is useful, so I would be glad to do the work myself, but I don't want to discourage others from contributing if they want.

**Comment by mekwall** [comment]
You don't need to provide a chunk size because the browser will decide that. Send should just support it out of the box imo. Basically, this is what would happen:

1) Browser does a normal http request to a resource. Let's say it's a mp4 video file in this case.
2) Server responds with status 200 and with [`Accept-Ranges`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges) header (probably set to `bytes`) to indicate to the browser supports content ranges.
3) The browser then download the necessary bytes (header) from the file to figure out what it is and if/how it can be split into chunks. Not all media can be split into even chunks but has to be split at keyframes, so the browser need to figure that out.
4) If the file format can support it the browser will then cancel the first request and do another request to the same resource with the [`Range`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) header set to what data it want to download
5) If the range is valid server responds with status 206 and `Content-Range` header indicating which chunk it is sending and the total size of the file.

I still don't know how to use `Deno.open` and `Deno.read` to just read a part of the file. Can you provide or point me to an example similar to how it is done with Node?

**Comment by kitsonk** [comment]
Great, I would then just bake the logic into `send` to return files that respect the `Accept-Ranges` header and automatically send back ranged content.

`Deno.open()` returns a [`Deno.File`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.File).  You pass it a Uint8Array that has a particular size (this is like a Node.js Buffer).  The `.read(arr)` will resolve with a promise that will give the number of bytes that were read into the Uint8Array (or `null` if it has reached the EOF).  So basically if you have a chunk size, create a Uint8Array of the size of the chunk and pass it to read.

The "mocks" in `send_test.ts` should be adjustable enough to be able to do testing, and there is a 50MB file which can be used for testing in `/examples/static/`.

**Comment by mekwall** [comment]
I've already tried that though and it will not work on large chunks. The problem is that it will read the chunk before passing it to `response.body` and if the chunk is too big you'll run out of memory. In Node, when doing `fs.createReadStream(filePath, { start, end })`, you can take that read stream and pipe it directly to the response body. I was hoping for something similar in deno.

**Comment by kitsonk** [comment]
[BufReader](https://doc.deno.land/https/deno.land/std/io/bufio.ts#BufReader) then... sort of like how the body is read in multipart: https://github.com/oakserver/oak/blob/main/multipart.ts#L125 but I had to use a custom `BufReader` because of the nature of how the multipart body needed to be read, but `BufReader` should be fine for reading a file in a memory management way and writing it out to the body.

**Comment by mekwall** [comment]
Ok, so I figured it out and it was actually way easier than I thought. This is how I got it working:

```ts
let bytesRead = 0;
await file.seek(startByte, Deno.SeekMode.Start);
response.body = {
  async read(p: Uint8Array) {
    if (bytesRead >= chunkSize) {
      // We got the requested chunk so stop reading
      return null;
    }
    const buf = new Uint8Array(p.length);
    const rb = await Deno.read(file.rid, buf);
    if (rb) {
      bytesRead += rb;
    }
    // Ensure that we do not send more than the requested chunk
    p.set(
      bytesRead >= chunkSize ? buf.slice(0, bytesRead - chunkSize) : buf
    );
    return rb;
  },
};
```
