### ISSUE TITLE
FormDataFile.content is undefined in BodyFormData -> FormDataBody

### ISSUE THREAD

**Issue by Schoude** [oakserver/oak#208]
Hi there!

**deno@v.1.2.0**
**oak@v6.0.0.**

I am trying to upload a file to the server with a `FormData` object and `multipart/form-data` content-type.

Before sending the post request i append the file to the formdata object:
```
let formData = new FormData();
formData.append("file", this.file);
```

Logging the file gives me this:
```
File {
  name: "git workfow visualisation.jpg",
  lastModifiedDate: Wed Apr 08 2020 23:12:38 GMT+0200 (Mitteleuropäische Sommerzeit) {}
  name: "git workfow visualisation.jpg"
  size: 154058
  type: "image/jpeg"
  webkitRelativePath: ""
}
```

In my post request in oak i retrieve the body like 
`const body = c.request.body({ type: 'form-data' });`

After that i read the value of the body
`const formData = await body.value.read();`

Having this object, I should have access to the file's metadata including its **content** as a Uint8Array that I would like to write as a file with `Deno.writeFile()`

To my surprise a log if `formData` showed this result:
```
{
  fields: {},
  files: [
    {
      content: undefined,
      contentType: "image/jpeg",
      name: "file",
      filename: "C:\\Users\\marc_\\AppData\\Local\\Temp\\be592974/2ae02c0c4cce0a32a385fdb5306bd8c86542dbd7.jpeg",        
      originalName: "git workfow visualisation.jpg"
    }
  ]
}
```

The `content` property is `undefined` but everything else matches the file that I am trying to upload and save.
Am I missing something when appending the file to the `FormData` object in the first place or is this even the wrong way to handle files if I want to upload and save them?

Thanks for the help and sorry if this is a kind of newbie question. I am pretty new to Deno and server-side JS in general,

PS: I already tried the [Upload-middleware-for-Oak-Deno-framework](https://github.com/hviana/Upload-middleware-for-Oak-Deno-framework) and found no luck because it seems like this middleware is atm incompatible with deno@v1.2.0.

**Comment by kitsonk** [comment]
`doc.deno.land` doesn't appear to be displaying the type properly/well, including the JSDoc (I didn't realise the type wasn't an interface and just a type which I think is part of the problem).  The code itself though documents what is going on: https://deno.land/x/oak/multipart.ts#L38

`content` is only filled in when the file is small enough to keep in memory, based on the [`FormDataOptions`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#FormDataReadOptions) that are passed which defaults to 1mb.  When the content size exceeds that, the file is written out to disk.  You can either change the size allowed to keep in memory, or use the `filename` attribute to open up the file again and do some buffered processing of the file.

**Comment by Schoude** [comment]
Thank you for the explanation!

I added a `maxSize` property to the `FormDataReader` and voilà there was the `Uint8Array` as the content!

**"FIX";**
`const formData = await body.value.read({ maxSize: 5000000 });` = 5MB maximum file size

@kitsonk Feel free to close this issue.

**Comment by zacharykravits** [comment]
@Schoude @kitsonk thank you so much for this! had the same issue!
