### ISSUE TITLE
How to extend Context?

### ISSUE THREAD

**Issue by ToWeLong** [oakserver/oak#209]
Now, I want to add some attributes to context,Whenever I want to return a JSON data, I need to write it ctx.response.body So I wanted to simplify the writing method. I checked the document roughly and found that there was no such content

**Comment by kitsonk** [comment]
[`.state`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#Context) is intended for storing of arbitrary data like that.  It can be strongly typed via the generic.

Duplicate of #113

**Comment by ToWeLong** [comment]
> [`.state`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#Context) is intended for storing of arbitrary data like that. It can be strongly typed via the generic.
> 
> Duplicate of #113

oh, Thanks,You are very fast in handling issues. I hope your framework will be better and better
