### ISSUE TITLE
Why do programs get stuck after I use the inspect-brk command?

### ISSUE THREAD

**Issue by ToWeLong** [oakserver/oak#210]
for example:
![Snipaste_2020-07-16_14-08-21](https://user-images.githubusercontent.com/41502558/87633370-d826b700-c76d-11ea-8a41-eb503a695ba8.png)

**Comment by kitsonk** [comment]
oak has no control over it, nor can it do anything the specifically help... it is something that needs to be opened with Deno as an example of a broken capability.  I suspect it has to do with the asynchronous nature of handling requests, but I don't know the inspector parts of Deno well.

**Comment by ToWeLong** [comment]
> oak has no control over it, nor can it do anything the specifically help... it is something that needs to be opened with Deno as an example of a broken capability. I suspect it has to do with the asynchronous nature of handling requests, but I don't know the inspector parts of Deno well.

all right!

**Comment by ToWeLong** [comment]
> oak has no control over it, nor can it do anything the specifically help... it is something that needs to be opened with Deno as an example of a broken capability. I suspect it has to do with the asynchronous nature of handling requests, but I don't know the inspector parts of Deno well.

all right!
