### ISSUE TITLE
Form data body is empty

### ISSUE THREAD

**Issue by osorito** [oakserver/oak#212]
Hello.

I'm using
`deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2`

If I send form data from the front end or postman,  the body comes empty. 
Here a glimpse of the code
`        if(!ctx.request.hasBody){
            throw new HttpError("Body not found",422);
        }
        const result = ctx.request.body();
        const body = await result.value;
        console.log(`body ${JSON.stringify(body)}`);`
This will give the following output
`Listening on: 5000
body {}
POST http://localhost:5000/feed/post - Thu Jul 16 2020 17:15:47 GMT-0400 (EDT)`

The only way I'm able to catch a glimpse of the data is this way
`       const result = ctx.request.body({
            contentTypes: {
              raw: ["multipart/form-data"],
            },
          });//form-data
        //const result = ctx.request.body({type:"form-data"});
        const body = await result.value;
          console.log(body);
       
        let str: string ="";
        for(let i = 0; i< body.length; i++ ){
            //console.log(`i ${i}`);
            str += String.fromCharCode(parseInt(body[i]));
        }  
        console.log(str);`

With this output
`------WebKitFormBoundaryZY7u1aDahbVCsw07
Content-Disposition: form-data; name="title"

Test Home
------WebKitFormBoundaryZY7u1aDahbVCsw07
Content-Disposition: form-data; name="content"

This is a test
------WebKitFormBoundaryZY7u1aDahbVCsw07
Content-Disposition: form-data; name="creator"

5f108b5e0016a94000826d85
------WebKitFormBoundaryZY7u1aDahbVCsw07--`

Is there a way, I can get the information sent over from the front end? If I only send json from the  front end it works great. But form data does not work, unless you play with said information. In this example i removed the file from the form. Otherwise i could not get the output.

**Comment by kitsonk** [comment]
I will assume you are using oak 6 (you didn't specify).

Bodies of type `form-data` have a value of of [`FormDataReader`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#FormDataReader), which provides two methods `.read()` and `.stream()`.  When you serialize that value, it will simply empty, but that is not what you are looking for.  Because of the nature of form data, files and fields have to be separated and the two methods provide different ways of accessing the information.  To "fix" what you have written, you want to do something like this:

```ts
       if(!ctx.request.hasBody){
            throw new HttpError("Body not found",422);
        }
        const result = ctx.request.body();
        const body = result.value;
        console.log(`body ${JSON.stringify(await body.read()).fields}`);
```

**Comment by osorito** [comment]
Thanks.  Made a small adjustment and it worked.

` 
       if(!ctx.request.hasBody){
            throw new HttpError("Body not found",422);
        }
        const result = ctx.request.body({type:"form-data"});
        const temp = await result.value;
        const body = (await temp.read()).fields;
        console.log(body);
        console.log(`title ${body.title}`);
        console.log(`content ${body.content}`);
        console.log(`creator ${body.creator}`);
`

Now I just have to test sending a file.

**Comment by osorito** [comment]
With the previous solution I can see all the form fields, except the file or image. If I try .stream() instead of .read() them the object comes empty .

**Comment by kitsonk** [comment]
As per the documentation, with `.read()`, files are in the `.files` property.  With `.stream` it is an an async iterable where you need to asynchronously iterate over the values, handling each one.

**Comment by osorito** [comment]
As you explained if I use .files I can see the output.
`Listening on: 5000
OPTIONS http://localhost:5000/feed/post - Mon Jul 20 2020 10:16:40 GMT-0400 (EDT)
[{"contentType":"image/png","name":"imageUrl","filename":"/var/folders/xm/p9th04cn7cj995yckbf9f7c40000gn/T/bf9e9395/f96cf9bdadfd157eb15254c82a9d29b445db122f.png","originalName":"Screen Shot 2019-11-29 at 10.08.51 AM.png"}]
POST http://localhost:5000/feed/post - Mon Jul 20 2020 10:16:40 GMT-0400 (EDT)`
But once you read the files, you can't see the fields.
Just to be on the safe side, I verified and indeed the file was created on the route filename , can you have both solutions at the same time? See all the fields from the form and get the file. And also can i specify my own path for said file output. If possible the files should be on a specified folder within the current project and not outside in the /var folder. Lets say an uploads or images folder, that way when you display the images on the frontend it will look for said folder. As of now i'm able to do it with a static image that i added. But it would be great that the image sent from the front end be stored in said folder. This way i'll be serving the image sent fron the frontend and not the one manually places on my images folder.

**Comment by kitsonk** [comment]
There are two properties on the object.  `.files` and `fields`.  As long as you maintain a reference to value, you can read both.

I really encourage you to read the documentation, as the documentation is clear that [`.read()`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#FormDataReader) takes an optional [`options`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#FormDataReadOptions) argument which controls how the files are handled.  It contains all the features you are looking for from what I can tell.

**Comment by osorito** [comment]
Thanks for the links. Now i'm able to store the file on the images folder. But once you call .read() for the files. It complains that the body is already being read.

        if(!ctx.request.hasBody){
            throw new HttpError("Body not found",422);
        }
        const result = ctx.request.body({type:"form-data"});
        const temp = await result.value;
        const files = (await temp.read({outPath:'images'})).files.filename;
        console.log(files);
        const body = (await temp.read()).fields;
        console.log(body);
        console.log(`title ${body.title}`);
        console.log(`content ${body.content}`);
        console.log(`creator ${body.creator}`);

gives me this output

Listening on: 5000
OPTIONS http://localhost:5000/feed/post - Mon Jul 20 2020 17:05:08 GMT-0400 (EDT)
undefined
Body is already being read.
POST http://localhost:5000/feed/post - Mon Jul 20 2020 17:05:08 GMT-0400 (EDT)

**Comment by kitsonk** [comment]
This is really basic TypeScript/JavaScript, I am afraid:

```ts
    if(!ctx.request.hasBody){
        throw new HttpError("Body not found",422);
    }
    const result = ctx.request.body();
    assert(result.type === "form-data");
    const { files, fields: body } = await result.value.read({outPath:'images'});
    console.log(files);
    console.log(body);
    console.log(`title ${body.title}`);
    console.log(`content ${body.content}`);
    console.log(`creator ${body.creator}`);
```

Because everything is working as expected, and I cannot continue to be your support department, I am going to close the issue.
