### ISSUE TITLE
Static content alongside API

### ISSUE THREAD

**Issue by domenichelfenstein** [oakserver/oak#214]
Hi

I want to create an oak app with two parts:
- Backend (JSON API)
- Frontend (static files from a folder)

I thought I could create two `Router`'s and set a different `prefix` for each of the routers.
The first router (with prefix `"/api"`) contains a bunch of routes/endpoints and is added to the Application with `app.use(apiRouter.routes())`

The second router (with prefix `"/frontend"`) contains a `use(...)` itself and pretty much follows this example: https://github.com/oakserver/oak/#static-content (but with `frontendRouter.use(context ...` instead of `app.use(context ...`)
I added the frontend router the same way as the API router (`app.use(frontendRouter.routes())`)

Unsurprisingly, my approach didn't work. Or more precise: The "static content delivery via a router"-part didn't work.

Is there another approach to this (e.g., sub-applications or something like that)?
Or is this use case just not covered at this phase of the project?

**Comment by domenichelfenstein** [comment]
To clarify things, this is what my little Application looks like:

```typescript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const apiRouter = new Router({ prefix: "/api" });
apiRouter
    .get("/", (context) => {
        context.response.body = { some: "object" };
    });

const frontendRouter = new Router({ prefix: "/frontend" });
frontendRouter.use(async (context) => {
    console.log("is not called");
    await context.send({
        root: `${Deno.cwd()}/static`,
        index: "index.html",
    });
});

const app = new Application();
app.use(apiRouter.routes());
app.use(frontendRouter.routes());

await app.listen({ port: 8000 });
```

**Comment by kitsonk** [comment]
Your use case seems valid, and on the surface nothing is obviously wrong, so need to investigate.

**Comment by sherjil** [comment]
Here is working solution I found by mixing and matching working codes

```
import { Application, send , Router } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

const apiRouter = new Router({ prefix: "/api" });
apiRouter
    .get("/", (context) => {
        context.response.body = { some: "object" };
    });

app.use(apiRouter.routes());

app.use(async (context) => {
    await send(context, context.request.url.pathname, {
      root: `${Deno.cwd()}/static`,
      index: "index.html",
    });
  });

await app.listen({ port: 8001 });
```

**Comment by domenichelfenstein** [comment]
Thanks @sherjil 
I will give this a try.
However, I wanted to have the static part in another sub route (instead of in the root, like in your example)

**Comment by domenichelfenstein** [comment]
I just realized I can put the `index.html` into a folder called `frontend`. If I do that, the app behaves precisely how I want it.

**Comment by sherjil** [comment]
OK ... i was looking something like this today ( just start learning Deno ) I found your code It was really helpful .. So I needed front end app in svelte and back end api in mongo ... So that is the solution i came up for now ...

**Comment by PandawanFr** [comment]
Although this is not what OP was asking about, it turns out this is the same issue:

It seems serving from a simple router (without prefix tho I'm not sure that matters) with `router.use` does not work, but the same middleware will work perfectly fine in `app.use`.

Here's a simple example:
```ts
import {
  Application,
  Router,
} from "https://deno.land/x/oak@v6.2.0/mod.ts";

const router = new Router();

router
  // If you call /example, it works fine
  .get("/example", (context, next) => {
    context.response.body = "Hello world from example";
  })
  // If you call any other path, nothing shows up
  .use(async (context) => {
    context.response.body = "Hello world from router.use middleware";
  });

const app = new Application();

app.use(router.routes());
app.use(router.allowedMethods());

/*
// On the other hand, using app.use rather than router.use works fine.
app.use(async (context) => {
    context.response.body = "Hello world from app.use middleware";
});
*/

await app.listen({ port: 8000 });
```

**Comment by MartinMuzatko** [comment]
@domenichelfenstein your approach to just put another folder "frontend" inside is good. But not good enough for me.

Theoretically, if the files are named like the rest of the API, this will possibly conflict (unless you put the API first)
If you don't do it in the correct order, you will possibly expose yourself to a security risk. In environments (like I work with) the frontend is flexible and can add whatever files it wants. So it would be great to have a happy path instead of a workaround.

My guess why the router does not work with the static server, is because the router does not allow dynamic patterns. router paths are always strict. My first approach was to do `router.use('/subpath', async context => {...})` but this strictly binds it to the subpath only and all files beneath are not allowed. Is there something like a dynamic matching? You can use `:id` for the part within the path, but if you want to match an entire path, something like `/subpath/*`  would be great.

**Comment by thorwebdev** [comment]
What's the best way to serve static content in sub folders? this is what I've ended up with, but wondering if there's a better/easier way?

```js
// static content
app.use(async (context, next) => {
  const paths = context.request.url.pathname.split("/");
  const fileName = paths.pop();
  const root = `${Deno.cwd()}/static${paths.reduce((a, v) => a + v + "/", "")}`;
  try {
    await context.send({ root, path: fileName });
  } catch {
    next();
  }
});
```
