### ISSUE TITLE
Add Eslint

### ISSUE THREAD

**Issue by cktang88** [oakserver/oak#219]
I couldn't find any documentation on how contributors can maintain a consistent formatting/code styling pattern. I think Deno's eslint config https://github.com/denoland/deno/blob/master/.eslintrc.json is a good default to have in place.

**Comment by kitsonk** [comment]
We will adopt `deno lint` in the near future.  I just want it to get more stable.

**Comment by kitsonk** [comment]
`deno lint` was added in 59782a5917c58187b27c490d0a3cb69b1a3aa7ac.
