### ISSUE TITLE
Sending Raw text - Server Crush

### ISSUE THREAD

**Issue by gungunfebrianza** [oakserver/oak#220]
If we try to use this code, and we send raw text via postman decode will fail. 

````js
app.use(async (ctx) => {
  const result = ctx.request.body(); // content type automatically detected
  if (result.type === "json") {
    const value = await result.value; // an object of parsed JSON
  }


here is the error :

error: Uncaught SyntaxError: Unexpected token a in JSON at position 0
          JSON.parse(decoder.decode(await this.#valuePromise()));

    at JSON.parse (<anonymous>)
    at value (body.ts:202:16)

we need internal handling to solve this issue.

**Comment by eniwez** [comment]
works for me

![image](https://user-images.githubusercontent.com/47905317/89005218-e1696500-d2d1-11ea-9383-d2887a5c8ba6.png)

**Comment by gungunfebrianza** [comment]
> 
> 
> works for me
> 
> ![image](https://user-images.githubusercontent.com/47905317/89005218-e1696500-d2d1-11ea-9383-d2887a5c8ba6.png)
> 
> or try with this
> ` async create(ctx: any): Promise < any > { const body = await ctx.request.body({ contentTypes: { text: ["application/json"], }, }); const value = await body.value; console.log(value) }`

try to send raw text... not object..

**Comment by kitsonk** [comment]
The only time the `result.type` would be set to JSON is when the `Content-Type` is set to `application/json`.  If you set that content type and then send a body that is invalid JSON, the behaviour you are seeing is to be expected (that an error throws).

If there is a risk that someone might try to send invalid JSON in the payload, you should write the code to handle that properly, in a way that is meaningful to your application.  For example:

```ts
app.use(async (ctx) => {
  const result = ctx.request.body(); // content type automatically detected
  if (result.type === "json") {
    try {
      const value = await result.value;
    } catch (e) {
      if (e instanceof SyntaxError) {
        ctx.throw(Status.BadRequest, e.message);
      } else {
        ctx.throw(Status.InternalServerError);
      }
    }
  }
});
```
