### ISSUE TITLE
add a "wildcard" GET route for static files? (hosting SPA)

### ISSUE THREAD

**Issue by RNR1** [oakserver/oak#221]
# oak@main

I successfully deployed a React SPA + Oak-Deno app to Heroku, the backend serves the React build and everything works fine, but when I refresh the page on a different route than '/' (I'm using react-router for frontend-routes) the server doesn't serve the index.html and I get a 404 "No such file or directory (os error 2)". 

I have been using the docs example for sending static content which works great for serving the react build on '/', but how can I add a wildcard(*) GET route for serving my SPA on any other non-api routes? I tried looking for other examples or repositories but couldn't find any match so far.

here's my app.ts code, you can also check the repository:
https://github.com/RNR1/Reflix/tree/master/backend

```
import { Application, send } from 'oak'
import * as path from 'path'
import { parse } from 'flags'
import { config as env } from 'dotenv'

import { movies, profiles } from './routes/index.ts'
import { connect } from './config/db_client.ts'

env()
connect()

const port = Number(Deno.env.get('PORT')!)
const { args } = Deno
const argPort = parse(args).port

const app = new Application()

app.use(async (ctx, next) => {
	ctx.response.headers.set('Access-Control-Allow-Origin', '*')
	ctx.response.headers.set(
		'Access-Control-Allow-Methods',
		'GET, POST, PUT, DELETE'
	)
	ctx.response.headers.set('Access-Control-Allow-Headers', 'Content-Type')
	await next()
})

app.use(movies.routes())
app.use(movies.allowedMethods())
app.use(profiles.routes())
app.use(profiles.allowedMethods())

app.use(async (ctx) => {
	const filePath = path.join(Deno.cwd(), '..', 'build')
	await send(ctx, ctx.request.url.pathname, {
		root: filePath,
		index: 'index.html'
	})
})

await app.listen({ port: argPort ? Number(argPort) : port })

```

**Comment by RNR1** [comment]
I ended up hosting the client and server separately, but are there any suggestions?

**Comment by kaleidawave** [comment]
_Only just seeing this now._

The issue is around your `send`. The default for `send` is to pull a file out of your file system based on `ctx.request.url.pathname`. See [this](https://github.com/oakserver/oak/blob/7df0e23905d390b5cc49ec852db8751b6836f355/context.ts#L21).

You can override that behaviour by setting `path` to the file:

```
await ctx.send({ path: pathToIndexHtmlFile });
```

This will however cause the `index.html` to be served when requesting other static files e.g. `bundle.js`, so you would have to take account for that etc:

```
if ([".js", ".css", ".json", ".ico"].some(extension => ctx.request.url.pathname.endsWith(extension))) {
  await ctx.send({ root: filePath });
} else {
  await ctx.send({ path: pathToIndexHtmlFile });
}
```

**Comment by RNR1** [comment]
Thanks for your answer! I will try it next time I am trying to host static content
Saving and closing this issue.
