### ISSUE TITLE
Sharing state between middlewares using the context

### ISSUE THREAD

**Issue by domenichelfenstein** [oakserver/oak#223]
I've created a simple session middleware for oak (https://github.com/domenichelfenstein/oak-sessions) because I couldn't find anything similar in the oak project itself (maybe I just didn't get the application state right, but I'd like to think, I did).

For the most part, I'm pretty happy with my middleware. But I've encountered one problem:
- When the user starts a new session (no `sessionId` created so far), my middleware has to create a new session id and store it in the cookies.
- But unfortunately, this cookie isn't available in router handling during the same request. (the context gets altered by my middleware but the context-changes from my middleware aren't available in the context of the router handling)
- I was able to solve this by introducing a (application-wide) temp variable in my middleware. But I don't think this can work when requests get processed in parallel

Is there any pattern or process to share data between two middlewares via the context?

Some code to help:
```ts
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import { Session } from "https://raw.githubusercontent.com/domenichelfenstein/oak-sessions/master/mod.ts";

const session = new Session(() => ({ counter: 1 }));
const router = new Router()
    .get("/", async (context) => {
        // 2. here we want to read the session state by using the context
        const state = await session.getState(context);
        context.response.type = "text/html";
        context.response.body = `Counter: ${state.counter}`;

        await session.storeState(context, { counter: state.counter + 1});
    })

const app = new Application();
// 1. This middleware creates a sessionId and initializes a session state
app.use(session.sessionHandling);
app.use(router.routes());
await app.listen({ port: 8000 });
```

Without my hacky application-wide variable (inside of Session) this code wouldn't work during the first request (where the session id isn't known in the request itself).

**Comment by kitsonk** [comment]
[`context.state`](https://doc.deno.land/https/deno.land/x/oak/mod.ts#Context)?  Which can be strongly typed using generics?

**Comment by domenichelfenstein** [comment]
Please correct me, if I‘m wrong, but:
- context.state seems to be an application-wide (not context-wide) state
- I can‘t specify the Type of context.state in my middleware (and hide it from the user)

**Comment by kitsonk** [comment]
Normally you don't want to grab a reference to the context, but instead have a middleware that does pre and post processing before other middleware that needs that occurs.  It could set something in the `.state` per request, like:

```ts
app.use(async (context, next) => {
  context.state.session = "whatever";
  await next();
  delete context.state.session;
});
```

If you are obsessed about hiding it, use a symbol that only you have reference to as the key.

But if you are really obsessed about hiding it:

```ts
const myPrivateData = new WeakMap();
myPrivateData.set(context, "something");
```

The context object is the same object through the handling of the request.

**Comment by domenichelfenstein** [comment]
Hi @kitsonk 
First of all, thanks for taking the time to help me!
Second, it's not about an obsession about hiding things, it's about the fact that I'm the middleware provider. I'm not necessarily the developer who will implement the application itself. Therefore I can't define how the application state should look like.

To further illustrate what's happening, here is the code of my Session manager:
```ts
export class Session<T> {
    private tempKey: string | undefined;

    constructor(
        private initState: () => T,
        private cookieOptions: CookiesSetDeleteOptions = {},
        private repo: ISessionRepository<T> = new InMemorySessionRepository<T>()) {}

    public sessionHandling = async (context: Context, next: () => Promise<void>) => {
        if (context.cookies.get(SESSION_ID) == undefined) {
            const initialState = this.initState();
            const uuid = v4.generate();
            await this.repo.set(uuid, initialState);
            context.cookies.set(SESSION_ID, uuid, this.cookieOptions);
            this.tempKey = uuid;
        }
        await next();
    };

    public getState = async (context: Context): Promise<T> => {
        const sessionId = await this.getKey(context);
        const state = await this.repo.get(sessionId);
        if(state) {
            return state;
        } else {
            const newState = this.initState();
            await this.repo.set(sessionId, newState);
            return newState;
        }
    };

    public storeState = async (context: Context, state: T) => {
        const sessionId = await this.getKey(context);
        await this.repo.set(sessionId, state);
    };

    private getKey = (context: Context) => {
        const sessionIdFromCookies = context.cookies.get(SESSION_ID);
        const sessionId = sessionIdFromCookies ?? this.tempKey;
        return new Promise<string>((resolve, reject) => {
            if(sessionId) {
                resolve(sessionId);
            } else {
                reject();
            }
        });
    }
}
```

If you take a look at this method:
```ts
public sessionHandling = async (context: Context, next: () => Promise<void>) => {
        if (context.cookies.get(SESSION_ID) == undefined) {
            const initialState = this.initState();
            const uuid = v4.generate();
            await this.repo.set(uuid, initialState);
            context.cookies.set(SESSION_ID, uuid, this.cookieOptions);
            this.tempKey = uuid;
        }
        await next();
    };
```
You see that I'm setting a cookie for the session id. However, this cookie isn't available in the router handler of my initial post:
```ts
const router = new Router()
    .get("/", async (context) => {
        // this will be undefined:
        const sessionId = context.cookies.get(SESSION_ID);
        const state = await session.getState(context);
        context.response.type = "text/html";
        context.response.body = `Counter: ${state.counter}`;

        await session.storeState(context, { counter: state.counter + 1});
    })
```
This makes me question your "The context object is the same object through the handling of the request" statement.

If the context object was the same object, I should be able to read that newly set cookie (in the router handler, because the router handler gets executed after `sessionHandling`). Then I wouldn't need my hacky `tempKey` and I would be happy :)

**Comment by kitsonk** [comment]
The `context` is the same, trust me.

Why you don't think it is the same is that `.cookies.get()` only looks at cookie values in the `request` and not anything in the `response`.  Because of the support for verified keys, I am not too keen on changing the behaviour, it would make it appear that the cookie is actually part of the request, when it isn't.

I would simply have the middleware move the session state in and out of the `context.state`...  So something like this:

```ts
let sessionId = context.cookies.get(SESSION_ID);
let state;
if (!sessionId) {
  sessionId = // new guid
  context.cookies.set(SESSION_ID, sessionId);
  // init state
}
context.state.session = // get state 
await next();
// whatever other cleanup, persistence, whatever
delete context.state.session;
```

That way, consumers of your middleware don't have to even think about it, they will simply use:

```
context.state.session.whatever
```

**Comment by domenichelfenstein** [comment]
Thank you so much @kitsonk!

You helped me get rid of the `tempKey`. I've changed my middleware and the corresponding example based on your suggestion.
The result can be found here: https://github.com/domenichelfenstein/oak-sessions
