### ISSUE TITLE
Typing Error with deno latest version 1.2.1 |  'string | URL' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by deepakshrma** [oakserver/oak#224]
**Code:**
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const body = "Hello World"
const app = new Application();

app.use((ctx) => {
  ctx.response.body = `<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    ${body}
  </body>
  </html>`;
});

await app.listen({ port: 8000 });

```

`deno --version`

**Output:**
```
deno 1.2.1
v8 8.5.216
typescript 3.9.2
```

**Error:**

```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.56.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.56.0/path/posix.ts:438:18
```

**Note:** It is working file with `deno@1.1.3`

**Comment by kitsonk** [comment]
You need to reload your cache `deno run --reload whatever.ts`.

Please don't use an unpinned version of oak, as it will lead to this very specific issue and is clearly mentioned in the [README](https://github.com/oakserver/oak#oak):

> _Warning_ The examples in this README pull from `main`, which may not make
> sense to do when you are looking to actually deploy a workload. You would want
> to "pin" to a particular version which is compatible with the version of Deno
> you are using and has a fixed set of APIs you would expect.
> `https://deno.land/x/` supports using git tags in the URL to direct you at a
> particular version. So to use version 3.0.0 of oak, you would want to import
>`https://deno.land/x/oak@v3.0.0/mod.ts`.

Currently you should use `https://deno.land/x/oak@v6.0.1/mod.ts` which is the latest release.

**Comment by deepakshrma** [comment]
Thanks.. i almost forget about `--reload`
