### ISSUE TITLE
Main page shows wrong version as latest, and no changelog

### ISSUE THREAD

**Issue by David-Else** [oakserver/oak#225]
![oak](https://user-images.githubusercontent.com/12832280/89285917-26cac100-d649-11ea-88fd-5e02efd49b9b.png)

I see that Oak is very much maintained and up-to-date, but on casual inspection, the latest version was released in May. With Deno's rapid development this is very discouraging for potential users. It is very misleading, can it be corrected?

Also, I can't find a changelog, is there one? Cheers.

**Comment by kitsonk** [comment]
That is a behaviour of "releases" in GitHub and it cannot be controlled (like a lot of things on GitHub).  Please refer to the tags to determine the latest release.  I may "release" every tag in the future, but I am not sure.

There is no change log at this point.  Something I will consider in the future.
