### ISSUE TITLE
v6.+ request value always show 'Promise { <pending> }'

### ISSUE THREAD

**Issue by chioio** [oakserver/oak#226]
When I write a request api, post a json value and log the value in console. Its always print Promise { <pending> }
`
const login = async (ctx: RouterContext) => {
  const body = await ctx.request.body();
  console.log(body.value);
  ctx.response.body = 'success';
};
`
-------------------------
Listening on port: 4000...
Promise { <pending> }

**Comment by aditya612** [comment]
> ## When I write a request api, post a json value and log the value in console. Its always print Promise { }
> `const login = async (ctx: RouterContext) => { const body = await ctx.request.body(); console.log(body.value); ctx.response.body = 'success'; };`
> 
> Listening on port: 4000...
> Promise { }

Hi @chioio, I am also today facing the same problem as you but, I figure out after reading doc that you only need to change the `await` position because I think API changes. Now below you see what needed to change.

```javascript
const login = async (ctx: RouterContext) => { 
  const body = ctx.request.body();  // instead of ` await ctx.request.body() `
  console.log(await body.value);  // and also ` body.value `
  ctx.response.body = 'success'; 
};
```

**Comment by kitsonk** [comment]
As mentioned, this was a breaking change introduced in #201 and released in v6.  The [README](https://github.com/oakserver/oak#request) makes it clear how the body is to be consumed in v6+.
