### ISSUE TITLE
Unable to catch HTTP exceptions.

### ISSUE THREAD

**Issue by andreespirela** [oakserver/oak#233]
**[Details] (Vague example)**
Right now, Oak is **not** throwing any error for non-existent routes. Even though the response code **is set** to _404_, it is not interpreted as an error, thus it never gets to the error handling middleware.

**[Error handling middleware] (Vague + pseudocode)**
```typescript
try {
await next()
} catch(error) {
response.body = `This is an error ${error.toString()}`
}
```
In theory, if an error was thrown because of the 404 route, it would return a response as shown above, but as an error is never thrown this never happens.

On the other hand, when I do this middleware:
```typescript
await next();
console.log(context.response.status);
```
I can clearly see how it logs a 404 in the console.

**Comment by andreespirela** [comment]
I’m curious about the best approach for this, because it may be too broad (unless I’m doing something wrong and it’s already figured out), I expose the case of a 404, but there are many HTTP codes that are not “success” per se, and throwing an error sounds like really traumatizing in terms of the system. Wdyt? @kitsonk

**Comment by infinityart** [comment]
You could use a middleware to throw an error after your router middleware as a temporary solution to this.

```ts
app.use(async (context, next) => {
    try {
        await next();
    } catch (err) {
        if (isHttpError(err)) {
            switch (err.status) {
                case Status.NotFound:
                    console.log("Not found"); // This will trigger
                    break;
                default:
                // handle other statuses
            }
        } else {
            throw err;
        }
    }
});

app.use(routes.routes());
app.use(routes.allowedMethods());

app.use(async (context) => {
    context.throw(404, "Not found");
});
```

**Comment by andreespirela** [comment]
@infinityart yeah that’s an option, it seems like a little too much, but that’s the way to go as of right now

**Comment by kaleidawave** [comment]
It could maybe implemented as a opt in. I don't think it would be _too hard_ to implement support for `new Application({throwOnNotFound: true})` or something like that

**Comment by kitsonk** [comment]
Having thought about this (yeah, I know, long time) and how the koa-router handles this, I think the current behaviour is what is expected, and that users should have a middleware that handles non-matched routes, as that is ultimately what stacked middleware should do, so having a 404 middleware that sets the right behaviours for the application at the end should be a common pattern.  There are several examples of this in both koa and express.
