### ISSUE TITLE
Best way to handle 'URIError: URI malformed'

### ISSUE THREAD

**Issue by markuskobler** [oakserver/oak#235]
We have just gone to production with a deno/oak app and are hitting a fairly strange issue caused by malformed urls.

Hitting the following app with a url like `curl 'http://localhost:8000/?start=Sep203,202020&end=Sep%2'` causes it to throw an `URIError: URI malformed`

```
import {Application, Context} from "oak";

const app = new Application();
app.use((ctx: Context) => {
  try {
    console.log(ctx.request.url.pathname);
  } catch (err) {
    console.log("caught", err);
  }
  ctx.response.body = "Hello World!";
});
await app.listen({port: 8000});
```

Is there anyway to gracefully parse the url without throwing a hard error?

**Comment by kitsonk** [comment]
What do you expect the behaviour of a malformed URL to be?  If it is a malformed URL, it is a malformed URL.

**Comment by markuskobler** [comment]
It’s valid question and maybe my example was not the best. Ideally we would at least be able to get the path. The query params are meant to help with seeding a booking flow and passed through from an enterprise app that are unfortunately not able to fix it their end.

**Comment by markuskobler** [comment]
We managed to work around this with something in front of deno.
