### ISSUE TITLE
maxAge on Cookies treated as milliseconds rather seconds

### ISSUE THREAD

**Issue by kaleidawave** [oakserver/oak#236]
The `maxAge` value on cookies is treated as seconds https://tools.ietf.org/html/rfc6265#section-5.2.2. Oak condenses the `maxAge` property by setting the `expires` property.

https://github.com/oakserver/oak/blob/1d4030fdddd73f9238e0a361765c836a31948698/cookies.ts#L115

However the `Date` constructor argument is in terms of milliseconds not seconds. So passing `{maxAge: 60}` to `ctx.cookies.set`  will cause the cookie to timeout in 60 milliseconds not 60 seconds.

`this.maxAge` should be multiplied by 1000 to make it in terms of milliseconds.

**Comment by limcheehean** [comment]
Looks like maxAge is being treated a milliseconds again.
