### ISSUE TITLE
Feature Request: Accept an optional callback in app.listen()

### ISSUE THREAD

**Issue by ducaale** [oakserver/oak#238]
Currently, a basic example requires attaching an event handler to the app

```javascript
const port = 8000;
const app = new Application();
 
app.addEventListener('listen', () => {
  console.log(`Listening on localhost:${port}`);
});
 
await app.listen({port});
```

it would be nice if oak supported passing a callback as a second argument to `app.listen`

```javascript
const port = 8000;
const app = new Application();
await app.listen({port}, () => console.log('server started at port', port));
```

**Comment by kitsonk** [comment]
Thanks, but I don't want to introduce callbacks. Ideally we have one way of doing things, and the event listener is sufficient and aligned to the way browsers and Deno deal with event type situations.
