### ISSUE TITLE
Property X does not exist on type 'Promise<any> | Promise<URLSearchParams> | FormDataReader | Promise<string> | Promise<Uint8Array>'

### ISSUE THREAD

**Issue by rwieruch** [oakserver/oak#239]
Hello everyone,

this [minimal project runs with Deno + Oak](https://github.com/the-road-to-deno/deno-oak-rest-api) with the following version without problems:

```
deno --version
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```

After upgrading it to 

```
deno --version
deno 1.3.3
v8 8.6.334
typescript 4.0.2
```

I had to upgrade the cached dependencies for using the newest std libraries:

```
deno run --reload https://deno.land/std/uuid/mod.ts
deno run --reload https://deno.land/x/oak/mod.ts
```

At the end of this journey, I get the following error when using `deno run --allow-net --allow-read server.ts` on this project:

```
deno run --allow-net --allow-read server.ts
Check file:///Users/mydspr/Developer/Repos/deno-oak-rest-api/server.ts
error: TS2532 [ERROR]: Object is possibly 'undefined'.
    text: value.text,
          ~~~~~
    at file:///Users/mydspr/Developer/Repos/deno-oak-rest-api/server.ts:80:11

TS2339 [ERROR]: Property 'text' does not exist on type 'Promise<any> | Promise<URLSearchParams> | FormDataReader | Promise<string> | Promise<Uint8Array>'.
  Property 'text' does not exist on type 'Promise<any>'.
    text: value.text,
                ~~~~
    at file:///Users/mydspr/Developer/Repos/deno-oak-rest-api/server.ts:80:17

Found 2 errors.
```

I checked the source code and narrowed it down to the following block, which uses the **context's request body**:

```
router.post('/messages', async (ctx) => {
  const id = v4.generate();

  const {
    value: { text },
  } = await ctx.request.body();

  messages.set(id, {
    id,
    text,
    userId: ctx.state.me.id,
  });

  ctx.response.body = messages.get(id);
});
```

Did something change for how body is implemented in Oak?

**Comment by kaleidawave** [comment]
Was changed around #201 

- `ctx.request.body()` is no longer async so you can drop `await`
- Now accepts argument for type of body
- `value` is now a promise so needs to be awaited (which is what the ts issue highlights)

Not sure what body type you were using before but here are some usages in the latest version

```ts
// for JSON:
const { value } = ctx.request.body({ type: "json" });
const { text } = await value;

// for FormData:
const { value } = ctx.request.body({ type: "form-data" });
const formData = await value.read();
const { text } = formData.fields;
```

**Comment by rwieruch** [comment]
Wow, thank you for the quick reply @kaleidawave Issue resolved 👍 ❤️
