### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [oakserver/oak#240]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by kitsonk** [comment]
At the moment, GitHub Pages is sufficient for our needs.  Thanks for the suggestion though.
