### ISSUE TITLE
Support http and https at same time

### ISSUE THREAD

**Issue by developeer** [oakserver/oak#241]
Hi,

Working on small test project.  Read docs but can't figure out how to configure oak/deno to allow http and https to site.  

```
await app.listen({ port: 443, 
      certFile: '/etc/letsencrypt/live/codeisla.com/fullchain.pem', 
      keyFile: '/etc/letsencrypt/live/codeisla.com/privkey.pem', 
      secure: true });
```

forces https but is http support at the same time without launching another deno?  

is it possible to call app.listen twice? once without await?

**Comment by kaleidawave** [comment]
Have got this working using `Promise.all`

```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
    ctx.response.body = `Connection running over "${ctx.request.secure ? "https" : "http"}"`;
});

await Promise.all([
    app.listen({ port: 8000 }),
    app.listen({
        port: 8001,
        secure: true,
        certFile: './certificate.crt',
        keyFile: './privateKey.key',
    })
]);
```

_One thing to note is that they cannot listen on the same `port`_

**Comment by developeer** [comment]
Thank you. This is great!  Next thing I am trying to get running is websockets (ws) with what you have below
.


________________________________
