### ISSUE TITLE
Using Oak for Deno v1.4.0

### ISSUE THREAD

**Issue by PaulFish-Radius** [oakserver/oak#245]
Hi, 
How do we update our existing projects to use the latest Oak which was updated for Deno v1.4.0? 
On deno.land I only see `https://deno.land/x/oak@v6.1.0` which doesn't look like its working for v1.4

Thanks for the information.

**Comment by kitsonk** [comment]
oak v6.1.0 should work with Deno v1.4 (just not with the `--unstable` flag).

I will tag a new release in a few minutes, as a PR landed which resolve the problem with `--unstable`.

**Comment by kitsonk** [comment]
oak v6.2.0 is available now: https://deno.land/x/oak@v6.2.0
