### ISSUE TITLE
Run application failed with Deno version: 1.0.0 on Ubuntu 20.04.1 LTS (Focal Fossa) (WSL2)

### ISSUE THREAD

**Issue by SomboChea** [oakserver/oak#248]
Hi, all there! I have problem with Deno that using oak application.

**This my problem errors:**
```
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
      sorted: true,
      ~~~~~~~~~~~~
    at https://deno.land/std@0.73.0/testing/asserts.ts:26:7
```
### Oak version
**Oak latest version (v6.3.1)
From https://deno.land/x/oak/mod.ts**
### Deno version
**deno 1.0.0
v8 8.4.300
typescript 3.9.2**
### OS version
**Ubuntu 20.04.1 LTS
on WSL 2 (Windows 10 latest version)**

**Comment by kaleidawave** [comment]
Likely because old version of deno. Try `deno upgrade` and run again

**Comment by SomboChea** [comment]
@kaleidawave thank you, it's work!
