### ISSUE TITLE
Error listener triggers error when there is no error when importing static files like css

### ISSUE THREAD

**Issue by salemalem** [oakserver/oak#259]
When I enable error listener using:
```js
app.addEventListener('error', event => {
  console.log(event.error);
});
```
and when I try to use static files like css
```js
app.use(async (ctx,next) => {
  await send(ctx, ctx.request.url.pathname,{
    root: `${Deno.cwd()}/static`
  });
  next();
});
```
It gives me an error:
```bash
NotFoundError: The system cannot find the file specified. (os error 2)
    at createHttpError (httpError.ts:131:10)
    at send (send.ts:148:13)
    at async file:///C:/Users/KryaKrya/Desktop/deno%20blog/server.js:20:3
    at async dispatch (middleware.ts:41:7)
    at async oak.ts:67:5
    at async dispatch (middleware.ts:41:7)
    at async Application.#handleRequest (application.ts:252:9)
```
However, when I disable error listener
Static files work without any error.

**Comment by lideming** [comment]
@salemalem I guess it's caused by the `/favicon.ico` request from the browser.
You can prepend a simple middleware to verify that:
```ts
app.use(async (ctx,next) => {
  console.info(`Request: ${ctx.request.url.toString()}`);
  await next();
});
```
You can also print the request in the error listener:
```ts
app.addEventListener('error', event => {
  console.info(event.context?.request, event.error);
});
```

**Comment by kitsonk** [comment]
I believe @lideming is correct.

It feels like `send` should simply return a 404 though instead of blindly trying to access the file.

**Comment by salemalem** [comment]
@kitsonk thanks once I added favicon.ico the error disappeared. Why it tries to search for favicon even if I didn't turn it on?
It doesn't happen in Node js. Also, we can close this issue :)

**Comment by kitsonk** [comment]
> Why it tries to search for favicon even if I didn't turn it on?

That is the behaviour of the browser/client connecting to your server.  It has nothing to do with Deno, oak, or Node.js.

**Comment by kitsonk** [comment]
Also, it wasn't a bug, it was "working as designed" and was throwing a 404 error, the application was just not trapping it and responding to it like demonstrated in the example static application: https://github.com/oakserver/oak/blob/main/examples/staticServer.ts#L19-L53
