### ISSUE TITLE
Backlog of releases?  Is this no longer maintained?

### ISSUE THREAD

**Issue by flemux** [oakserver/oak#263]
I've raised some issue with Oak version 4, but looking at the releases it looks like there is a huge backlog.  

![image](https://user-images.githubusercontent.com/67560754/101907933-2d4ae580-3bb3-11eb-854b-a3fb9c246886.png)

I can't seem to import github repos directly:
```

export {
  Application,
  Context,
  Router,
} from "https://raw.githubusercontent.com/oakserver/oak/mod.ts";
```
or this format either:
`export type { Middleware } from "https://github.com/oakserver/oak/mod.ts";`

Any clarification on how to do this would be great.  But it would be even better if the releases could be available via Deno Land?

I'm more than happy to contribute and help if you need it.

**Comment by ducaale** [comment]
>deno.land/x downloads and stores your repository contents every time you create a git tag. We only do this once for every tag. This ensures that the contents we serve for a specific version can never change.

So It should be possible to use unreleased tags like this
```javascript
import {Application, Router, helpers} from 'https://deno.land/x/oak@v6.3.2/mod.ts';
const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

Although I am getting some TS errors which I am not sure how to resolve
```
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
      sorted: true,
      ~~~~~~~~~~~~
    at https://deno.land/std@0.77.0/testing/asserts.ts:26:7
```

**Comment by kitsonk** [comment]
You should not rely on GitHub releases for accessing oak. I really don't use them. `https://demo.land/x/oak/` is the best place to import oak from, which is what is used in the examples.
