### ISSUE TITLE
How can I protect particular endpoints

### ISSUE THREAD

**Issue by FSou1** [oakserver/oak#276]
Hi,

I'd like to implement a JWT Authentication.

The endpoints are:
* /auth - generate a token (anonymous)
* /list - for authorized access only (the access is verified within a middleware)

In order to do that, I use multiple routers now:

```
const app = new Application();

const anonymousRouter = new Router();

anonymousRouter
  .post("/auth", auth);

app.use(anonymousRouter.routes());

app.use(authorized);

const router = new Router();

router
  .get("/list", list);

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

The `authorized` middleware is straightforward: proceed with `next` if the extracted token is valid.

Is there a better way how it can be implemented?

**Comment by pmprosociety** [comment]
@FSou1 check out https://github.com/pmprosociety/authcompanion for some implementation ideas on this auth topic. Hope it helps.

**Comment by FSou1** [comment]
@pmprosociety 

Ok, I see you can use multiple middlewares:

```
router
  .post("auth/recovery/token", recoverToken)
  .post("auth/users/me", authorize, updateUser)
```

Thank you.

p.s. Is it safe to use the `ctx.state` for auth [information](https://github.com/pmprosociety/authcompanion/blob/10bf9f0d9ce5b7bea297d1b8e579c9bd83680579/middlewares/authorize.ts#L21)? Sounds like the state is global and shared between multiple HTTP requests.

**Comment by pmprosociety** [comment]
@FSou1 thanks for the heads up on that - was not aware until now. Removing this.

**Comment by justinmchase** [comment]
So where do you store the state of the middleware then?

**Comment by FSou1** [comment]
> So where do you store the state of the middleware then?

I didn't get your question

**Comment by justinmchase** [comment]
You asked if it was safe to use the `ctx.state` and gave some reasons why it wasn't safe, then @authcompanion seemed to be saying he wasn't aware that it wasn't safe and was going to remove his code sample....

So if `ctx.state` is not safe where are you supposed to actually store the request context state?
