### ISSUE TITLE
Support Deno Deploy

### ISSUE THREAD

**Issue by kitsonk** [oakserver/oak#290]
Add support for Deno Deploy: https://deno.com/deploy

I will be working on this very soon.

**Comment by kitsonk** [comment]
Available in oak v7.1.0 and later.

**Comment by brainless** [comment]
Hello @kitsonk, was there an update in documentation for this? I searched in docs and commits but could not find anything. Sorry if I missed it somewhere.

**Comment by kitsonk** [comment]
It "just" works, though I should add some docs for sure. It doesn't work with `deployctl` at the moment unless you use `--no-check`.

**Comment by brainless** [comment]
Ahh OK. I thought `addEventListener` was the only API for Deno Deploy while Oak was setting up a regular TCP server. Thanks, will try it out.

**Comment by brainless** [comment]
For anyone's reference, `Application` has a `fetchEventHandler` which you pass as the handler for `addEventListener` in Deno Deploy. @kitsonk thanks, it worked.

https://github.com/oakserver/oak/blob/main/application.ts#L347

**Comment by kitsonk** [comment]
@brainless and some more formal documentation: https://oakserver.github.io/oak/deploy

**Comment by brainless** [comment]
Thanks @kitsonk, this would immensely help those who are looking to deploy on Deno Deploy. As I understand this would work without change on CloudFlare Workers (it seems the API is same). Perhaps you can add that information too.

**Comment by kitsonk** [comment]
@brainless it would require a few more steps, like using `deno bundle`, and I don't want to do that until it is tested and known as working.
