### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by marktyers** [oakserver/oak#297]
Just pulled the latest version into a project and getting multiple errors when I start the server:

```
TS2729 [ERROR]: Property 'boundary' is used before its initialization.
```

These seem to have been introduced in a recent update.

**Comment by kitsonk** [comment]
Could you provide a more complete reproduction and more complete output.

**Comment by marktyers** [comment]
I have discovered the issue is due to the latest version of Deno. It works fine if I use version 1.7.1 but it breaks with version 1.9.

**Comment by kitsonk** [comment]
> Could you provide a more complete reproduction and more complete output.

**Comment by kitsonk** [comment]
No response on a more complete reproduction, not enough information to diagnose, closing.
