### ISSUE TITLE
oak version track using git tag

### ISSUE THREAD

**Issue by Gumichocopengin8** [oakserver/oak#298]
Hello, thank you for the great framework. 
My suggestion is that using `git tag` to record version updates would be better than recording updates on `CHANGELOG.md`. 
Here's an example https://github.com/denoland/deno/releases
It's much easier to track version update and commits.
Are there any reasons using `CHANGELOG.md`? 
Thanks

**Comment by kitsonk** [comment]
I dislike the GitHub releases. For something that is often not accessed via GitHub (https://deno.land/x/oak), having the information checked into the repo as a standalone document makes more sense to me.
