### ISSUE TITLE
Live reload for Oak

### ISSUE THREAD

**Issue by Gumichocopengin8** [oakserver/oak#299]
Hello, 
I want a feature of live reload if any files changed. 
There is a way to do this with [denon](https://github.com/denosaurs/denon), but users need to setup every project. 
That would be helpful if oak has the live reload watcher internally.
Thanks!

**Comment by kitsonk** [comment]
This is not something I would do anytime soon. Why it is theoretically possible, it would always be a better idea to use some tooling external to the project that is designed for this purpose.

If someone wanted to contribute something well written, I would consider it.

**Comment by brainless** [comment]
@Gumichocopengin8 from what I understand `denon` is installed at the user level and available to any project. What is the setup that users have to do on every project?

**Comment by Gumichocopengin8** [comment]
@brainless You can check https://github.com/denosaurs/denon.
You probably want to setup config for denon. That's what I meant. Of course you can still use denon without config tho.

**Comment by dgpgdev** [comment]
hello you can use the watch deno flag

```
deno run --unstable --watch  yourserverfile.ts
```

**Comment by kitsonk** [comment]
I don't think it is an appropriate feature for oak.
