### ISSUE TITLE
Pass through Reader response body type to Deno's HTTP server

### ISSUE THREAD

**Issue by dbohdan** [oakserver/oak#30]
Deno's [current `Response` interface](https://github.com/denoland/deno/blob/11a29fdb44f5c07f4bc7aa49a136b695ee17f0c3/std/http/server.ts#L569) allows `Reader` as the body type.

```typescript

/**
 * Interface of HTTP server response.
 * If body is a Reader, response would be chunked.
 * If body is a string, it would be UTF-8 encoded by default.
 */
export interface Response {
  status?: number;
  headers?: Headers;
  body?: Uint8Array | Reader | string;
}
```

This would be convenient to have in oak since, for example, [dejs](https://github.com/syumai/dejs/) renders its templates to a `Reader`.

**Comment by kitsonk** [comment]
Resolved in a380e1242422ca24f9d62565e3f59fc18e3a49c5.

Now you can do the following to get the `Deno.Reader` interface returned.:

```ts
app.use(async (ctx) => {
  const body = await ctx.response.body(true);
});
```

**Comment by dbohdan** [comment]
:tada: :tada: :tada:

**Comment by dbohdan** [comment]
Oops, the party horns were premature.  a380e12 doesn't actually affect this issue.

The code example in your comment is incorrect.  `ctx.response.body` is not a function; `ctx.`**`request`**`.body` is.  The commit implements an option to handle the Request body as a Reader, but the Response body only remains a Uint8Array.

```
> cat demo.ts
import {
  Application,
} from "https://deno.land/x/oak/mod.ts";

const app = new Application();
app.use(async (ctx) => {
  const body = await ctx.response.body(true);
});
await app.listen('localhost:3000');

> deno run --allow-net demo.ts
this.url.protocol http:
error: Uncaught TypeError: ctx.response.body is not a function
  const body = await ctx.response.body(true);
                                  ^
    at demo.ts:7:35
    at dispatch (middleware.ts:33:14)
    at composedMiddleware (middleware.ts:35:12)
    at Application.#handleRequest (application.ts:99:11)
    at Application.listen (application.ts:109:26)
    at async demo.ts:9:1
```

**Comment by kitsonk** [comment]
Ah, my head was in request land.  Let me relook at how best to handle reponses.

**Comment by kitsonk** [comment]
Ok, I do believe it is finally fixed.  `response.body` can take a `Deno.Reader` which is just passes through to the http server.

**Comment by dbohdan** [comment]
How do you use this feature?  It treats a `Reader` differently than `http/server.ts` does.

## server.ts

```ts
import { serve } from "https://deno.land/std@0.51.0/http/server.ts";
import { StringReader } from "https://deno.land/std@0.51.0/io/readers.ts";

const srv = serve({ port: 3000 });
for await (const req of srv) {
  const body = req.url === "/reader"
    ? new StringReader("Hello, Reader!")
    : "Hello, world!";
  req.respond({ body });
}
```
```sh
> deno run --allow-net server.ts &
> curl localhost:3000/
Hello, world!⏎
> curl localhost:3000/reader
Hello, Reader!⏎
```

## oak.ts

```ts
import {
  Application,
} from "https://deno.land/x/oak/mod.ts";
import { StringReader } from "https://deno.land/std@0.51.0/io/readers.ts";

const app = new Application();
app.use(async (ctx) => {
  ctx.response.body = ctx.request.url.pathname === "/reader"
    ? new StringReader("Hello, Reader!")
    : "Hello, world!";
});
await app.listen("localhost:3000");
```

```sh
> deno run --allow-net oak.ts &
> curl localhost:3000/
Hello, world!⏎
> curl localhost:3000/reader
{"s":"Hello, Reader!","offs":0,"buf":{"0":72,"1":101,"2":108,"3":108,"4":111,"5":44,"6":32,"7":82,"8":101,"9":97,"10":100,"11":101,"12":114,"13":33}}⏎
```

**Comment by kitsonk** [comment]
Hrmmm... thanks for the reproduction... I have a test that just passes it through, but something else seems to be going on.  Grrr...

**Comment by kitsonk** [comment]
@dbohdan I think you need to do a `--reload`.  Using your example works for me.

```shell
$ curl localhost:3000/reader
Hello, Reader!%                                                                                                         
```

**Comment by dbohdan** [comment]
Oh, you're right.  I'm closing the issue since it works now.  Thanks for implementing this feature!

(To prevent this sort of confusion maybe you could aggressively version oak like Deno's `std` is versioned?  I am not actually sure it would be worth it.)

**Comment by kitsonk** [comment]
> (To prevent this sort of confusion maybe you could aggressively version oak like Deno's `std` is versioned? I am not actually sure it would be worth it.)

I am/do.  I just wanted to try to get as many bug fixes into before cutting a version.
