### ISSUE TITLE
Why only `void` type for routes?

### ISSUE THREAD

**Issue by lowlighter** [oakserver/oak#302]
Is there a particular reason that requires router middlewares to return `Promise<void>` instead of `Promise<unknown>`?
https://github.com/oakserver/oak/blob/969676083dffb9848275592e09b496baf64801aa/router.ts#L167

It's preventing the use of inline arrow functions:
```ts
router.get("/test", async ({response}) => response.body = "hello world")
```

Of course it's not a big deal and I can stick with additional brackets since it's just a stylistic issue, but it would still be nice for "simple routes"

**Comment by kitsonk** [comment]
Mostly because no one pointed it out before.
