### ISSUE TITLE
Abort signal not working with native HTTP server

### ISSUE THREAD

**Issue by cmorten** [oakserver/oak#304]
It appears that providing an `AbortController` `signal` to an Oak server for Deno `^1.9.0` while providing the `--unstable` flag ( so to use the native HTTP bindings ) does not work as intended, namely invoking `.abort()` does not resolve the returned promise from `app.listen({ ..., signal })`.

This can be demonstrated via the [`./examples/closeServer.ts`](https://github.com/oakserver/oak/blob/main/examples/closeServer.ts) example in this repository:

1. Run the example, providing the `--unstable` flag to use native bindings. Notice that the example logs that the server time is `native`:

    ```console
    $ deno run --allow-net --unstable ./closeServer.ts
    
    Start listening on 127.0.0.1:8000
      using HTTP server: native
    ```

1. In a browser, navigate to `http://localhost:8000/close` to invoke the code path which should abort the server, note that the logs display `GET /close - 1ms` but not `Finished.` as would expect.

1. Hitting the `/close` endpoint a second time results in the `Finished.` log statement as well as a `Bad resource ID` error. See below for the final set of full logs:
    
    ```console
    $ deno run --allow-net --unstable ./closeServer.ts

    Start listening on 127.0.0.1:8000
      using HTTP server: native
    GET /close - 1ms
    Finished.
    error: Uncaught (in promise) BadResource: Bad resource ID
                  listener.close();
                           ^
        at unwrapOpResult (deno:core/core.js:99:13)
        at opSync (deno:core/core.js:113:12)
        at Object.close (deno:core/core.js:121:5)
        at Listener.close (deno:runtime/js/30_net.js:121:12)
        at accept (file:///Users/craigmorten/git/oakserver/oak/http_server_native.ts:187:24)
    ```

Expected behaviour: calling `.abort()` should successfully close the native server, resolve the `.listen()` promise and not allow for the above error path whereby one is able to call `.close()` on what I presume is an already closed `listener` ( or similar, hence the resource ID error ).

**Comment by cmorten** [comment]
Having a quick dive around, it appears that the current native server code is only attempting to close the server on the subsequent request - assume implies the `await nativeRequest.donePromise` has already resolved by the time `server.close()` is called in `application.ts` ( in either the `#handleRequest` or `abort` event listener ).

The other curiousity is that the `return` within the async iter loop of `httpConn` does not appear to break the loop as one might expect, so a request or 2 after the server does finally close, it still attempts to handle the request and that causes issues as well. 🤔

**Comment by kitsonk** [comment]
Yeah, I just didn't test for it.  I will try to fix it tomorrow my time.
