### ISSUE TITLE
Server randomly crashes with "invalid HTTP method parsed"

### ISSUE THREAD

**Issue by konsti219** [oakserver/oak#306]
I have been running oak in a semi production environment and have encountered this crash multiple times. It seems to basically occur at random, and I have not found a way to trigger it.

Full error:
```
Uncaught (in promise) Http: invalid HTTP method parsed
for await (const requestEvent of httpConn) {
                 ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at async HttpConn.nextRequest (deno:runtime/js/40_http.js:33:23)
    at async Object.next (deno:runtime/js/40_http.js:83:26)
    at async serve (https://deno.land/x/oak@v7.3.0/http_server_native.ts:161:28)
```

The problem might be in deno itself but some error handling on the oak level could be added? Or is there some way I can handle this myself? I tried putting `.listen()` into a try catch, but it still crashed the entire server.

My deno version
```
deno 1.9.2 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
```

**Comment by kitsonk** [comment]
I think it s a bug with oak, will take a look.

**Comment by konsti219** [comment]
Been running it for some time, and it has been running without problems. Thanks for fixing quickly!

**Comment by luisvilches** [comment]
At least it happens to me when the content-length property is not present in the request header

**Comment by absolute-quantum** [comment]
I'm having this issue with very simple code of Oak in Deno

```
import { Application } from 'https://deno.land/x/oak/mod.ts'

const app = new Application()

app.use((ctx) => {
  ctx.response.body = 'Hello World!'
})

await app.listen({ port: 9000 })
```

The code works when run just with Deno, but when put inside a docker container behind a reverse proxy (nginx proxy manager) I get the error:

```
[uncaught application error]: Http - invalid HTTP method parsed

    at async HttpConn.nextRequest (ext:deno_http/01_http.js:93:21)
    at async serve (https://deno.land/x/oak@v12.1.0/http_server_native.ts:112:34)
```

**Comment by kitsonk** [comment]
This isn't an issue with oak. Deno is receiving an invalid HTTP method, oak is just ensuring that it doesn't crash the server. If oak wasn't in the way, it would be terminating your application.  You need to determine why invalid requests are being sent to the Deno runtime.

**Comment by absolute-quantum** [comment]
> This isn't an issue with oak. Deno is receiving an invalid HTTP method, oak is just ensuring that it doesn't crash the server. If oak wasn't in the way, it would be terminating your application. You need to determine why invalid requests are being sent to the Deno runtime.

I recently transitioned back to using Node, as it seems like a more fitting choice for something as straightforward as this project. I'll patiently look forward to its increased stability in the future. Thank you for your input, I appreciate it!

**Comment by joshcancode** [comment]
> I'm having this issue with very simple code of Oak in Deno
> 
> ```
> import { Application } from 'https://deno.land/x/oak/mod.ts'
> 
> const app = new Application()
> 
> app.use((ctx) => {
>   ctx.response.body = 'Hello World!'
> })
> 
> await app.listen({ port: 9000 })
> ```
> 
> The code works when run just with Deno, but when put inside a docker container behind a reverse proxy (nginx proxy manager) I get the error:
> 
> ```
> [uncaught application error]: Http - invalid HTTP method parsed
> 
>     at async HttpConn.nextRequest (ext:deno_http/01_http.js:93:21)
>     at async serve (https://deno.land/x/oak@v12.1.0/http_server_native.ts:112:34)
> ```

I've have this same issue with every single website I deploy with Oak, I simply ignore it as it doesn't seem to be correct.

**Comment by Almenon** [comment]
Same issue. MacOS. I installed deno via nix, ran the getting started code via `deno cache` and then `deno run --allow-net server.ts`, went to `localhost:8000` but it failed to load and I got the error. I restart it, same issue. 

But now every time I run it, it works. It's the weirdest thing.

**Comment by ebrahimkarimi** [comment]
i have the same issue it happens when i call `http` server with `https` protocol
