### ISSUE TITLE
staticServer example returns 404

### ISSUE THREAD

**Issue by jsjoeio** [oakserver/oak#307]
## Steps to Reproduce

1. Copy [`staticServer.ts`](https://github.com/oakserver/oak/blob/main/examples/staticServer.ts) and [`examples/static`](https://github.com/oakserver/oak/tree/main/examples/static)
2. Run `deno run --allow-net --allow-read staticServer.ts`
3. Navigate to [`http://localhost:8000`](http://localhost:8000)

## Expected

See `index.html` content 

## Actual

Shows 404 page
`404 - No such file or directory (os error 2)`

## Logs

```print
deno run --allow-net --allow-read staticServer.ts
Start listening on 127.0.0.1:8000
  using HTTP server: std
```

```javascript
GET http://localhost:8000/index.html 404 (Not Found)
```

## Screenshot

![image](https://user-images.githubusercontent.com/3806031/116823804-8227d200-ab3b-11eb-88fd-2a3376d51991.png)

# System Information

## System:
 - OS: macOS 11.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 783.73 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Deno:
- deno 1.9.0 (release, x86_64-apple-darwin)
- v8 9.1.269.5
- typescript 4.2.2
## Browser:
 - Chrome: 90.0.4430.93

**Comment by kitsonk** [comment]
The `staticServer.ts` is an example application (as indicted by `example`, in an attempt to help you build something suitable yourself.

In the code it has a hard-wired assumption to the root of the static files:

https://github.com/oakserver/oak/blob/b86f1da9840c36cce35f6032b52c6aa772df7da1/examples/staticServer.ts#L79

Where was `examples/static` located to the CWD where you started the server?

**Comment by jsjoeio** [comment]
> The staticServer.ts is an example application (as indicted by example, in an attempt to help you build something suitable yourself.

Yes! I gathered that, and I'm thankful they're there. Very helpful way to get started quickly.

🤦‍♂️ I think I put the files in `/examples` and not `/examples/static`. It's working as expected (user error on my side)

![image](https://user-images.githubusercontent.com/3806031/116887842-9de4b400-abdf-11eb-9a7d-768caf9a8691.png)

![image](https://user-images.githubusercontent.com/3806031/116887877-a6d58580-abdf-11eb-9cbc-8f7f528aba9a.png)

Apologies for the noise!
