### ISSUE TITLE
Is it possible to handle BrokenPipe errors?

### ISSUE THREAD

**Issue by dbohdan** [oakserver/oak#31]
There doesn't seem to be a way to handle `BrokenPipe` errors thrown in `std/http/server.ts` for individual requests from oak without modifying the `Application` class.  The error occurs if the HTTP client closes the connection prematurely.

Here is an example.
```TypeScript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

console.log("Starting...");

const router = new Router();
const veryLong = "foo bar baz qux ".repeat(1000000);

router.get("/demo", async ctx => {
  ctx.response.type = "text/html; charset=utf-8";
  ctx.response.body = `<h1>Hello!</h1>\n${veryLong}`;
});

const app = new Application();
app
  .use(router.routes())
  .use(router.allowedMethods())
  .listen("localhost:8080");
```

Save the code above as `demo.ts` and run the following shell commands to reproduce the error.

```fish
> deno --version
deno 0.31.0
v8 8.1.108
typescript 3.7.2
> deno --allow-net demo.ts &
> Compile file:///home/dbohdan/demo.ts
Starting...
> curl http://localhost:8080/demo & sleep 0.1; killall curl
> error: Uncaught BrokenPipe: Broken pipe (os error 32)   
► $deno$/dispatch_minimal.ts:59:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_minimal.ts:59:11)
    at sendAsyncMinimal ($deno$/dispatch_minimal.ts:102:10)
fish: Job 2, “curl http://localhost:8080/demo…” terminated by signal SIGTERM (Polite quit request)
Job 1, 'deno --allow-net demo.ts &' has ended
```

**Comment by omarzion** [comment]
I ran into a similar issue recently although it was a slighlty different error

This happens when chrome closes the connection during streaming audio with send

```
error: Uncaught ConnectionReset: Connection reset by peer (os error 104) 
► $deno$/dispatch_minimal.ts:59:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_minimal.ts:59:11)
    at sendAsyncMinimal ($deno$/dispatch_minimal.ts:102:10)
```

**Comment by hayd** [comment]
Is there a way to catch an error in middleware?

**Comment by kitsonk** [comment]
I guess there should be!

**Comment by kitsonk** [comment]
Catching this type of error in the middleware wouldn't work upon reflection, as the response is being sent, which is after all the middleware ran.

Instead, `Application` now extends `EventTarget` and errors thrown in the processing of the response (or in the middleware) now cause a `ErrorEvent` to be dispatched on the application instance.  If you wanted to respond to this:

```ts
const app = new Application();
app.addEventListener("error", (evt) => {
  evt.error; // contains the thrown error
});
```

**Comment by hayd** [comment]
> Catching this type of error in the middleware wouldn't work upon reflection, as the response is being sent, which is after all the middleware ran.

What about other types of error, for example some user thrown `Error`. Would it be possible to catch this? I was imagining something like this in the middleware:
```ts
try { await next() } catch (err) { /* render pretty error page */ }
```
Upon reflection, I can see it wouldn't be as easy as that / that won't work. But that was the usecase I was imaging...

**Comment by kitsonk** [comment]
I believe that already works @hayd.  I don't have a test for it I think but should.
