### ISSUE TITLE
Nested Router example doesn't work.

### ISSUE THREAD

**Issue by mmarkmos** [oakserver/oak#312]
I use Big Sur v.11.1 with Deno v.1.9.2.

I exactly copied the nested router example. When accessing the given urls, I get an empty pages.

Then I simplified the example. 
```ts
import {  
    Application,
    Router,
    Status,
    Context
} from "https://deno.land/x/oak@v7.3.0/mod.ts";


const posts = new Router()
  .get("/", (ctx) => {
    ctx.response.body = "r2";
  });

const forums = new Router()
  .get("/", (ctx) => {
    ctx.response.body = "r1";
  })
  .use("/r2", posts.routes(), posts.allowedMethods());

await new Application()
  .use(forums.routes())
  .use(async ({ request, response }: Context) => {
    response.status = Status.NotFound;
    response.body = { error: `${request.url} not found` };
})
  .listen({ port: 8000 });
```

When I access "localhost:8000/" the response is r1, but when I access "localhost:8000/r2/" I get the self written 404 Not Found Error.

**Comment by gcocatre** [comment]
I was just about to post the same issue. macOS 11.3.1, deno 1.9.2, importing "https://deno.land/x/oak/mod.ts".

**Comment by kitsonk** [comment]
Sub-routers are not part of 7.3.0. I have yet to tag a release with it in there.

**Comment by mmarkmos** [comment]
Ah, ok. Thanks for the quick response. 😄 From my point of it shouldn't be in the documentation, if it isn't in the code, or at least be marked.

**Comment by kitsonk** [comment]
The documentation in the registry you used for the version you used (https://deno.land/x/oak@v7.3.0) does not include the example, nor does the README include it. 🤷
