### ISSUE TITLE
How to handle shared state between requests

### ISSUE THREAD

**Issue by cryptogohan** [oakserver/oak#318]
I have a server that wants to share a cache between requests. i.e. work done by one request means another can skip work if some key is found in the shared cache.

I don't want to use global singleton because I like testing.

I thought I'd use `app.state` but I just noticed this state is cloned for every request, I tried to pass a getter but as those cannot be serialized that fails.

Something like this:
```ts
const cache = new LRU();
const state = {
	getCache: () => cache,
};
const app = new Application({ state });
```

Is there a way to share state between requests with Oak?

(Going to use closures with my request handlers now but that feels good not great.)

Thanks for an awesome web framework!

**Comment by halvardssm** [comment]
Hi @cryptogohan ! I asked the same question not too long ago in the discussions, here you go 😃 
https://github.com/oakserver/oak/discussions/305

**Comment by kitsonk** [comment]
Sure!
