### ISSUE TITLE
"TypeError: Cannot read property 'router' of undefined" in router.ts

### ISSUE THREAD

**Issue by martijnvanschie** [oakserver/oak#319]
I'm receiving the following error when running Deno on a Docker image `hayd/ubuntu-deno:latest`.
The same service runs local from the command line.

```javascript
paint-manager_api  | error: Uncaught (in promise) TypeError: Cannot read property 'router' of undefined
paint-manager_api  |       if (!middleware.router) {
paint-manager_api  |                       ^
paint-manager_api  |     at Router.#register (https://deno.land/x/oak@v7.4.1/router.ts:404:23)
paint-manager_api  |     at Router.#useVerb (https://deno.land/x/oak@v7.4.1/router.ts:492:19)
paint-manager_api  |     at Router.options (https://deno.land/x/oak@v7.4.1/router.ts:741:18)
paint-manager_api  |     at file:///app/brands/brands.routes.ts:7:4
```

`deno 1.9.0`

dept.ts

```typescript
export { Application, Router } from 'https://deno.land/x/oak/mod.ts';
export type { RouterContext } from 'https://deno.land/x/oak/mod.ts';

export { oakCors } from 'https://deno.land/x/cors/mod.ts';
export type { CorsOptions } from 'https://deno.land/x/cors/mod.ts';

export { Bson, MongoClient } from "https://deno.land/x/mongo@v0.22.0/mod.ts";
```

**Comment by kitsonk** [comment]
You will need to provide a more complete reproduction. Specifically what is at `file:///app/brands/brands.routes.ts:7:4`, it is really hard to guess. You say it works not in a container but breaks in a container? Why does that make you think it is an issue with oak?

Also you should use a pinned version of oak, as any changes to oak could easily break compatibility.

**Comment by martijnvanschie** [comment]
Well... the reason I thinks it oak is because the stack trace goes to this x/oak​@v​7.4.1/router.ts:404:23

I checked the source and there is an if statement for a property router which is on a instance which seams to be undefined.

The deno app works when running from my local machine command line but when build with the same sources I get this error in docker. Both will get the same packages I guess as in use deno cache prio to running... both would take v7.4.1 right?

**Comment by martijnvanschie** [comment]
Anyways... this is the code

```typescript
import { Router } from 'https://deno.land/x/oak/mod.ts'

import { getAllBrands, getBrand } from './brands.controller.ts'; 

const brandRouter = new Router();

brandRouter
  .options("/brands")
  .get("/brands", getAllBrands)
  .get("/brands/:id", getBrand)

export default brandRouter;
```

**Comment by kitsonk** [comment]
> both would take v7.4.1 right?

I don't know my crystal ball us broken. 😃

You are calling `.options("/brands")` without passing any middleware and that isn't [valid](https://doc.deno.land/https/deno.land/x/oak/mod.ts#Router). Because oak relies upon the type checking to validate usage, the runtime error occurs at a lower level. You should have gotten a type error and I can't see how the code could possibly work locally.

**Comment by kitsonk** [comment]
Ok, so again, I am not sure how it could possible work locally, but because of the spread operator on the middleware, the overload is not erroring, and that needs to be fixed, but all it will do is give you an error when type checking, versus the error at runtime.

**Comment by martijnvanschie** [comment]
Thank @kitsonk. The middleware for .options fixed it. I removed the .option and rebuild the docker image to test and the container runs fine. 

I know this is not a docker post but just as a reference just so you can see the difference.

Here is the command line version. Runs till the end and start listening:

![image](https://user-images.githubusercontent.com/8370550/118234819-2d1d8180-b494-11eb-92b6-85e37b8fa7b4.png)

And this is the docker version. Directly after the command line was run. This one fails.

![image](https://user-images.githubusercontent.com/8370550/118234925-4f170400-b494-11eb-9c4b-b607313de5ce.png)

I don't know why the docker one behaved different.... but it does....
