### ISSUE TITLE
Option to not use native API when trying to use .upgrade()?

### ISSUE THREAD

**Issue by Clive-Ward-Cron** [oakserver/oak#320]
Is there a way to optionally disallow the native API **without** omitting the --unstable flag?

I'm trying to achieve WebSocket functionality in my project, but another portion of code requires me to use the unstable flag. 
My sockets were working fine using the std/http bindings but it seems that having the unstable flag used for another portion of code is forcing Oak to use native bindings instead and throwing errors.

**Comment by pjvf17** [comment]
Running into this issue to. Going to have to downgrade for now. 6.5.1 works

**Comment by kitsonk** [comment]
The fundementals where there, but I hadn't exposed it.  I've added it and documented it in the main branch and will create a new release in a few hours.

**Comment by Clive-Ward-Cron** [comment]
Thank you @kitsonk that's exactly what I was looking for.

Just in case someone else runs into a similar issue:

If applying this option **after** setting up middleware functions that pass the Context or RouterContext type as a parameter, make sure to reload your cache or the linter in VSCode may give you warnings. It took me a few minutes to realize what was happening.
