### ISSUE TITLE
Limit queue size for SSE dispatchMessage?

### ISSUE THREAD

**Issue by al6x** [oakserver/oak#325]
The `target.dispatchMessage` for SSE uses in-memory buffer to keep the message before it's sent to the Browser.

There could be situation when messages added faster than they are delivered, causing memory oveflow.

Is there a way to somehow handle that situation, like set limit for max in-memory queue size for `target` or maybe something else?

**Comment by kitsonk** [comment]
That would be a lot of heap space and a very slow client, but I should consider looking at using/allow WHATWG Streams for dispatching the messages, this would give the implementor the ability to deal with back pressure.

**Comment by al6x** [comment]
Maybe properly implementing it with things like back-pressure would be an overkill. Possible simple option could be to just count the number of messages (or memory taken by those messages) in the queue, just as a single number, and reject the new `target.dispatchMessage` with the error if that number is greater than N.

**Comment by kitsonk** [comment]
I looked at this.  There is no in memory buffer.  When using `std/http` it writes to the `w` buffer on the connection and immediately flushes it.  While writer for `std/http` is a bufwriter, that is a `std/http` thing and only one message is ever pending before it gets flushed.  Using the native requests, each event is queued as a chunk in the response body, and it is up to the native HTTP server in Deno to determine when to send that to the client, not something oak can control.

So effectively, oak deals with the event immediately and doesn't buffer it.
