### ISSUE TITLE
ctx.request.body() is not working

### ISSUE THREAD

**Issue by chris-carrington** [oakserver/oak#33]
Thank you for this beautiful work!

Anyway I call `ctx.request.body()` forces the endpoint to Error out and not console.log() or add a response body

```
import { Application, Router } from "https://deno.land/x/oak/mod.ts"

let port = 8084,
    router = new Router(),
    app = new Application()

router
  .post('/wtf', async ctx => {
    let body = await ctx.request.body()
    console.log(body)
    ctx.response.body = { hello: 'world' }
  })

app.use(router.routes())
app.use(router.allowedMethods())

app.listen(`0.0.0.0:${ port }`)

**Comment by johnsonsamuel** [comment]
> Thank you for this beautiful work!
> 
> Anyway I call `ctx.request.body()` forces the endpoint to Error out and not console.log() or add a response body
> 
> ```
> import { Application, Router } from "https://deno.land/x/oak/mod.ts"
> 
> let port = 8084,
>     router = new Router(),
>     app = new Application()
> 
> router
>   .post('/wtf', async ctx => {
>     let body = await ctx.request.body()
>     console.log(body)
>     ctx.response.body = { hello: 'world' }
>   })
> 
> app.use(router.routes())
> app.use(router.allowedMethods())
> 
> app.listen(`0.0.0.0:${ port }`)
> ```

Just curious. Are you just trying to use `post` method? because `get` method works.

**Comment by linhub15** [comment]
When sending the `POST` request are you passing in any data?
Try: `curl -X POST http://0.0.0.0:8084 -d '{"name": "alice"}' -H 'content-type: application/json'`

You should see `{"type":"json","value":{"name":"alice"}}` in the console.

**Comment by chris-carrington** [comment]
It's working now! False alarm, thank you everyone & thank you oak team!

**Comment by reach2tarak** [comment]
I have tried the above code and it's not working properly...
``
import { Application, Router } from "https://deno.land/x/oak/mod.ts"

let port = 8084,
    router = new Router(),
    app = new Application()

router
  .post('/wtf', async ctx => {
    let lbody = await ctx.request.body()
    console.log(lbody)
    ctx.response.body = lbody;
  })

app.use(router.routes())
app.use(router.allowedMethods())

app.listen(`0.0.0.0:${ port }`)
``
![oak](https://user-images.githubusercontent.com/13413784/90035594-98f17480-dcdf-11ea-8715-50c19911e007.jpg)

Any help?
