### ISSUE TITLE
internal server error when upgrading from 6.5.0 to 7.5.0

### ISSUE THREAD

**Issue by Srabutdotcom** [oakserver/oak#334]
Dear All,

I just trying to use https server with the following code :

~~~javascript
await app.listen({ 
  hostname: domain, 
  port: port,
  secure: true,
  certFile: "./Private/aicone.crt",//"./localhost.pem",//
  keyFile: "./Private/aicone.key",//"./localhost-key.pem",//
  // This broadcasts that we can support HTTP/2 and HTTP/1.1 connections.
  //alpnProtocols: ["h2", "http/1.1"],
});
~~~

and with some depedencies module ...

~~~javascript
export { assert, assertArrayIncludes } from "https://deno.land/std@0.93.0/testing/asserts.ts";
export { existsSync } from "https://deno.land/std@0.93.0/fs/exists.ts";
//etc
~~~

But the internal server error arises when i upgrade oak from 6.5.0 to 7.5.0
What are the causes of this problem?

Thanks

**Comment by kitsonk** [comment]
> But the internal server error arises when i upgrade oak

What error, hard to guess what the error is or what causes it unless provide it?

Also what version of Deno and what does your command line look like to run your server?

**Comment by Srabutdotcom** [comment]
Hi @kitsonk ,

tks for quick response.,

the error message are just "Internal Server Error" in the browser and
message from my console.log on home path \: 
~~~javascript
TLS alert received: Message {
type: Alert,
version: TLSv1_3,
payload: Alert(
   AlertMessagePayload {
       level: Fatal,
       description: CertificateUnknown,
},},}
~~~

Deno version 1.10.2 (release, x86_64-pc-windows-msvc)
cli:
~~~javascript
deno run --allow-net --allow-read --allow-write --allow-run .\bin\www
~~~

note: error message in console.log are arises in both version 6.5.0 and 7.5.0 but only in version 6.5.0 the server are running well using https on port 443.

Thanks

**Comment by kitsonk** [comment]
I suspect there was some change to better handle errors on a connection instead of just swallowing it.

Can you add the following before your `app.listen()`?  It should log out the internal error which will make it a bit easier to figure out what is going on:

```ts
app.addEventListener("error", (err) => {
  console.log(err);
});
```

**Comment by Srabutdotcom** [comment]
This is the error when i changed to oak ver-7.5.0

~~~javascript
TypeError: Cannot destructure property 'conn' of 'serverRequest' as it is undefined.
    at writeLogInfo (logger.js:75)
    at mainrouter.js:14
    at dispatch (middleware.ts:46)
    at router.ts:1059
    at dispatch (middleware.ts:46)
    at composedMiddleware (middleware.ts:46)
    at dispatch (router.ts:1059)
    at dispatch (middleware.ts:46)
    at allowedMethods (router.ts:1059)
    at dispatch (middleware.ts:46)
~~~
why no serverrequest.conn in version 7.5.0? making the process stopped in WriteLogInfo.

I also wonder with the error message on both version.
~~~javascript
TLS alert received: Message {
type: Alert,
version: TLSv1_3,
payload: Alert(
   AlertMessagePayload {
       level: Fatal,
       description: CertificateUnknown,
},},}
~~~

but my ssl are genuine and verified. how come the error above arises.

thanks

**Comment by kitsonk** [comment]
> but my ssl are genuine and verified. how come the error above arises.

I believe it is actually your browser rejecting the certificate because it is issued by an unknown CA? You might want to look at: https://github.com/denoland/deno/issues/5760

Ok, I know where the problem is. I'm sort of surprised it worked in 6.5.0, but I think I can restore the behaviour.

**Comment by Srabutdotcom** [comment]
Hi @kitsonk 

My problem with certificate have been resolved by adding intermediate certificate.

How about the error from oak version 7.5.0 any update or progress?
For a while i stick on version 6.5.0 for safety, instead catching that error.

Thanks
