### ISSUE TITLE
Oak server hang strangely when run in command window sometimes?

### ISSUE THREAD

**Issue by xnsua** [oakserver/oak#336]
Oak server hang strangely when run in command window occasionally。

What surprise me is when Press "Enter" in the command window, Oak server resume, and everything is OK.

I found this because when I press 'Enter', a lot of log info of my project flush out. and then I visit Oak server in browser, everything is OK.

**Comment by kitsonk** [comment]
I doubt this is an oak issue.  What version of Deno are you using? What does your command line look like for running your oak application?  What operating system are you using?

**Comment by xnsua** [comment]
>C:\Users\cqhme\.deno\bin\deno.exe run --watch --allow-all --unstable D:\GitRepo\stock-site2\a_my_tools\my_http_server.mjs

deno --version
deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2

I will update deno and remove --unstable to find if this is the problem.

**Comment by kitsonk** [comment]
And what version of oak?

The release of Deno is somewhat "old".  Does the issue reoccur with the latest release of Deno, 1.10.3?

**Comment by xnsua** [comment]
I use **import {Application, helpers, Router, send} from 'https://deno.land/x/oak/mod.ts',**
So I do not know the version(I do not how to find).
But I reload the cache, and It now use **https://deno.land/x/oak@v7.5.0/mod.ts**.
I do not use this server every day, and The problem happens occasionally，
So it will take some time to find if this problem disappear.

**Comment by kitsonk** [comment]
You shouldn't use an unpinned version of oak like that.  From the [README](https://github.com/oakserver/oak/#oak) for the project:

> ⚠️ Warning The examples in this README pull from main, which may not make sense to do when you are looking to actually deploy a workload. You would want to "pin" to a particular version which is compatible with the version of Deno you are using and has a fixed set of APIs you would expect. https://deno.land/x/ supports using git tags in the URL to direct you at a particular version. So to use version 3.0.0 of oak, you would want to import https://deno.land/x/oak@v3.0.0/mod.ts.

When you don't use a specific tag, the version can float around, and newer versions can and do introduce incompatibilities with older versions of Deno.  v7.5.0 is designed to be used with Deno version 1.10 or later, not 1.8.0.

If you do happen to use an untagged version like this in the future: `deno info D:\GitRepo\stock-site2\a_my_tools\my_http_server.mjs` will output a dependency graph of what you are using.

All that said, it is unlikely a oak issue, as oak isn't doing anything special other than writing to `console.log()` and it sounds like it might be some sort of issue with long running stdout/stdin buffers on windows with Deno or the shell you are using.

**Comment by xnsua** [comment]
Thank you for your long post and I have learn something. I believe  " it is unlikely a oak issue". I will close the issue. I will make new issue if I found something new.

**Comment by xnsua** [comment]
I fount the reason:
The is a win10 feature:
[https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10](https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10)
