### ISSUE TITLE
How can I load wasm?

### ISSUE THREAD

**Issue by nabezokodaikon** [oakserver/oak#337]
If you write code like the following, you will get an error.
```typescript
import {
  Application,
  Context,
  send,
} from 'https://deno.land/x/oak@v7.5.0/mod.ts';

const app = new Application();

app.use(async (context: Context)=> {
  await send(context, context.request.url.pathname, {
    root: `${Deno.cwd()}/public`,
    index: 'index.html'
  });
});

await app.listen({ hostname: '127.0.0.1', port: 8080 });
```

<img width="752" alt="スクリーンショット 2021-06-07 21 16 37" src="https://user-images.githubusercontent.com/3197942/121015202-ada27a00-c7d5-11eb-9a0a-d6e8a066973b.png">

How can I load wasm?

**Comment by kitsonk** [comment]
This has nothing to do with oak. Oak us properly serving up the media types for the files you are statically hosting. You need to load wasm in a way supported by your browser.

**Comment by nabezokodaikon** [comment]
I understand. I'll think about it.
