### ISSUE TITLE
Registering middleware using the spread operator doesn't type check

### ISSUE THREAD

**Issue by itohatweb** [oakserver/oak#339]
Eg: I have an array of middleware functions:
![image](https://user-images.githubusercontent.com/72305210/121818678-eab0b580-cc88-11eb-994c-2d4aca5e6297.png)

Now when I try to use it I get an TypeScript error:
![image](https://user-images.githubusercontent.com/72305210/121818705-116eec00-cc89-11eb-8986-e8695e804dec.png)

With earlier versions of oak I did not have this problem, also when I run the code with no-check it works like a charm so my guess is that somewhere the types are invalid.

oak version: v7.5.0
Deno version: 1.11.0

**Comment by kitsonk** [comment]
I suspect we are missing a spread argument overload on the router methods.  Should be a straight forward change.  I will try to do it later today.

**Comment by kitsonk** [comment]
Actually, investigating, it was to fix another issue that "broke" this: https://github.com/oakserver/oak/commit/29326efacfd8475f97d5b365d31305251f42fa7c

It is a limitation of TypeScript it appears.  I can't find a way to create a type that requires at least 1 value but allows arbitrary spreading of values, and I think people getting type errors with no middleware is more useful than those trying to spread middleware.  There is a solution though for the end user though.  If you did something like:

```ts
export const signup: [RouterMiddleware, ...RouterMiddleware] = [
  // the array of middleware
];
```

That type annotation will allow you register the middleware using spread without any type errors, like:

```ts
apiv1.post("/signup", ...signup);
```

**Comment by itohatweb** [comment]
Thinking of it (I will try it later I'm not home rn) but would it work if the type is being changed to eg this? 
```ts
router.post(path: string, ...middlewares: [RouterMiddleware, ...RouterMiddleware[]))
```

**Comment by kitsonk** [comment]
> Thinking of it (I will try it later I'm not home rn) but would it work if the type is being changed to eg this?
> 
> ```ts
> router.post(path: string, ...middlewares: [RouterMiddleware, ...RouterMiddleware[]))
> ```

Nope, already tried that. The error `A spread argument...` still persists. It is due to the length not being tracked/inferred in the argument being passed.  `signup` is _n_ number of `RouterMiddleware` and that could mean it is `0` or `1` or more than `1` elements.

The other option is to do this:

```ts
const signup = [
  // ...middleware...
] as const;
```

And then that will assign a tuple type to `signup` which then is spreadable.

**Comment by itohatweb** [comment]
Hmm yea you are right, thanks for the help. I think ima use `as const` or a function which hacks the tuple together for me. 
Everything working now feel free to close the issue.
