### ISSUE TITLE
Splitting the Cookie header string on comas fails because of Expires date value

### ISSUE THREAD

**Issue by gcocatre** [oakserver/oak#343]
Hello,

Thank you for fixing [#327](https://github.com/oakserver/oak/issues/327). However there is a new issue with the way the cookie string is split: when a date value is set for the `expires` parameter, which produces a date string with a coma in it, then the cookie string is erroneously split on that coma. Example:

What should be:
```
set-cookie: a=1; path=/; expires=Tue, 22 Jun 2021 10:09:02 GMT
```

becomes:
```
set-cookie: a=1; path=/; expires=Tue
set-cookie: 22 Jun 2021 10:09:02 GMT
```

The following code is responsible:
```
if (this.expires) {
    header += `; expires=${this.expires.toUTCString()}`;
}
// […]
const headers = existingSetCookie ? existingSetCookie.split(/,\s+/) : [];
```

It seems to me that the coma character (`,`) should not be used internally as a separator for multiple `Set-Cookie` headers.

**Comment by gcocatre** [comment]
Actually, multiple headers should not be stored internally as a single string, because there is no character that you could use as a separator, that is guaranteed not to be present as data in one of the headers. In the case of cookies for instance, one of the values could include a coma, or a pipe, or pretty much anything. Trying to split a string containing multiple headers is bound to fail seemingly randomly.

**Comment by kitsonk** [comment]
The challenge is that `Set-Cookie` is special.  The WHATWG Headers allows multiple `Set-Cookie` headers to be set, but the headers spec will return the value with `.get()` comma delimitated.

What I need to do here is iterate over the values of the headers instead of using `.get()` so we simply get the unique entries instead of having to try to split the value.
