### ISSUE TITLE
Socket upgrades are not yet supported on native Deno requests.

### ISSUE THREAD

**Issue by justinmchase** [oakserver/oak#345]
Why not?

https://github.com/oakserver/oak/blob/main/context.ts#L190

What would be involved with making this work?

**Comment by kitsonk** [comment]
This is mentioned in the [README](https://github.com/oakserver/oak#deno-stdhttp-versus-native-bindings).

Limited by Deno supporting it (see: denoland/deno#10211)

**Comment by justinmchase** [comment]
Great, I am not totally sure what I did I think I must have started using the `--unstable` flag for a different reason and now its working.

It would be really great if the error it throws on line 190 would include a link to that document and / or a brief description of how to fix it such as maybe:

```ts
throw new TypeError(
   "Socket upgrades are not yet supported on native Deno requests. Try adding the --unstable flag or for alternate solutions please visit https://github.com/oakserver/oak#deno-stdhttp-versus-native-bindings",
);
```
