### ISSUE TITLE
Router post does not work.

### ISSUE THREAD

**Issue by johnsonsamuel** [oakserver/oak#35]
Hi,

I am new to `deno` and `oak`.  

The below code doesnt work for `post` method but WORKS for `get`.

```js 
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const router = new Router();
router
  .post("/", context => {
    context.response.body = "Hello world Johnson!";
  });

const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());

await app.listen("127.0.0.1:8000");
```

Any thoughts on this? Thanks in advance.

**Comment by wujingquan** [comment]
It's OK for me！
![image](https://user-images.githubusercontent.com/22289015/73739509-50318f80-4781-11ea-952c-dbf1b767d146.png)

**Comment by johnsonsamuel** [comment]
It is throwing error when I run from command line :|

> It's OK for me！
> ![image](https://user-images.githubusercontent.com/22289015/73739509-50318f80-4781-11ea-952c-dbf1b767d146.png)

**Comment by wujingquan** [comment]
What error message ?

**Comment by johnsonsamuel** [comment]
> What error message ?

I get
<img width="1363" alt="Screen Shot 2020-02-05 at 8 26 39 AM" src="https://user-images.githubusercontent.com/4627394/73807082-40ea2a80-47f1-11ea-8821-99e2991d839e.png">
 HTTP ERROR 405

**Comment by linhub15** [comment]
If you use Chrome it defaults to a `GET` request.
Try using `curl -X POST http://127.0.0.1:8000`

**Comment by johnsonsamuel** [comment]
> If you use Chrome it defaults to a `GET` request.
> Try using `curl -X POST http://127.0.0.1:8000`

Oh yeah, it does work with curl but not through browser.  Any thoughts ?

**Comment by wujingquan** [comment]
AJAX or form set method="POST"

**Comment by johnsonsamuel** [comment]
> AJAX or form set method="POST"

The code I have posted is the one I am trying to use.

**Comment by wtho** [comment]
Just to add a small detail to the explanation:
If you put a URL in any browser's URL Bar, it will always run GET against that URL endpoint.
To run POST you need to use a form submit or an ajax call.
Cheers!

**Comment by ryhinchey** [comment]
I think this issue can be closed 😄

**Comment by wujingquan** [comment]
> I think this issue can be closed 😄

+1
