### ISSUE TITLE
Consider removing `asserts` from return type of `Context.assert`

### ISSUE THREAD

**Issue by schuelermine** [oakserver/oak#351]
## Problem

Deno places restrictions on the usage of `assert`, requiring that the function call is **100% explicitly typed**. Because of this, usage like this:
```ts
app.use((context, next) => {
    context.assert(false);
}
```
is **disallowed**, because the type of `context` is not _explicitly_ stated.
However, adding the linted type explicitly will require importing the `Context` class, and **also prompts a complaint** about the `any` type in in `Context<Record<string, any>, Record<string, any>>`.

## Screenshots

Note: While this has been done in VS Code with the Deno extension, the missing explicit type declaration error is also thrown when running the script with Deno.

![deno-oak-explicit-type-required](https://user-images.githubusercontent.com/48802534/123694364-8af60500-d859-11eb-9b83-5186a79d7751.png)
![deno-oak-inferred-type](https://user-images.githubusercontent.com/48802534/123694455-a6611000-d859-11eb-86b3-de298d1a5b18.png)
![deno-oak-context-not-found](https://user-images.githubusercontent.com/48802534/123694537-c0025780-d859-11eb-9a9d-02306dfed20d.png)
![deno-oak-any-forbidden](https://user-images.githubusercontent.com/48802534/123694549-c395de80-d859-11eb-897e-8917406a02d2.png)

**Comment by kitsonk** [comment]
Maybe removing the `assert` in the return type would help, but there is an easy work around:


```ts
import { Application } from "https://deno.land/x/oak/mod.ts";
import type { Context } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx: Context, next) => {
  ctx.assert(false);
  return next();
});

app.listen({ port: 8000 });
```

**Comment by kitsonk** [comment]
I have thought about this, and I don't see the specific type annotation being too burdensome to allow the use of context's `assert()`. Taking away the annotation would mean that type narrowing would not happen, and that is one of the most useful features of assertion functions is to get the type narrowing, and it is more of a pain to add it back if someone wants that feature than it is to require a specific type annotation.
