### ISSUE TITLE
Oak server unexpectedly stops responding to requests

### ISSUE THREAD

**Issue by schuelermine** [oakserver/oak#366]
I’m running an Oak server that I’ve not finished developing on an AWS Lightsail instance, and it fails after continuous operation of 1½–3 days. I can’t see any other reason for it. The Date object isn’t overflowing, I think—I’ve checked in the REPL.

The code for the server is here: https://gist.github.com/schuelermine/814135caa432cf3aeaded4401d48fa22

I assume this isn’t enough information to diagnose any issue on Oak’s side, but I’m not sure how I would gather more diagnostic information.

**Comment by kitsonk** [comment]
What version of Deno are you using and how are you starting your server?

**Comment by kitsonk** [comment]
Also when you say "fails" can you be more specific?

**Comment by schuelermine** [comment]
I’m running 1.11.5 on Debian 10. It’s started by a shell script, `start.sh`, that is run in the background and then disowned. However, the starting method is likely irrelevant, as the behaviour was also present when manually starting Deno in a tmux or screen session. The server continues to run and produces no errors but simply does not respond to requests—they hang indefinitely. I’ve added a logging middleware to the server to gather more info as soon as this behaviour reoccurs. A restart of the server fixes it.

**Comment by kitsonk** [comment]
>  It’s started by a shell script, start.sh, that is run in the background and then disowned.

Sorry, I mean what command line arguments you are using. Also what version of oak?  Is your server over TLS?

Could this be denoland/deno#10419?

**Comment by schuelermine** [comment]
There is currently no TLS set up. The script goes as follows:
```sh
#!/usr/bin/sh
cd /www
DENO_DIR=/www/deno-cache/ sudo /www/deno run --allow-net --allow-read=/www --allow-write=/www /www/index.ts >> /www/logfile
```
As per the linked code, the Oak version is v7.7.0.

**Comment by kitsonk** [comment]
@schuelermine is it possible to use the `--unstable` flag to the server to see if the issue goes away.  Currently, when `deno` is run without the unstable flag, the native HTTP server is not available, and instead the `std` library HTTP server is used.  When the `--unstable` flag is provided, oak will use the native HTTP server.  Adding the `--unstable` flag would help narrow down where the problem is.

**Comment by schuelermine** [comment]
That’s a good idea, I will restart the server with `--unstable`

**Comment by kitsonk** [comment]
Also, you might want to add logging for any error events encountered by the app... something like:

```ts
mainApp.addEventListener("error", (evt) => {
  if (evt.error instanceof Error) {
    console.error(evt.error.message, evt.error.stack);
  } else {
    console.error(evt.error);
  }
});
```

Then any internal oak errors that aren't handled properly get logged. oak just "swallows" them by default, but there are a few that might cause oak to stop listening (like an error being thrown when accepting a connection).

**Comment by schuelermine** [comment]
Oh, that's good to know. I will insert that. Please keep in mind that, so far, this has happened after a few days of operation, so it might take a while to report back.

**Comment by schuelermine** [comment]
I believe that has fixed it. I still don’t know why it hung w/o `--unstable`.
