### ISSUE TITLE
How to "teach" oak the content type for a file extension

### ISSUE THREAD

**Issue by jaydenseric** [oakserver/oak#367]
How do you "teach" oak what the right content type is for a certain file extension?

Out of the box, [`send()`](https://github.com/oakserver/oak#static-content) doesn't make the `Content-Type` for `.importmap` files `application/importmap+json`:

https://github.com/WICG/import-maps#installation

How can this be configured? There doesn't appear to be a relevant `send()` option.

While this question urgently applies to `send()`, it could potentially also apply to [automatic response body handling](https://github.com/oakserver/oak#automatic-response-body-handling).

**Comment by kitsonk** [comment]
The media type database is located in [media_types](https://github.com/oakserver/media_types/), though the DB is a "copy/paste" of [mime-db](https://github.com/jshttp/mime-db/blob/master/db.json).  I wouldn't want to maintain something different from that, so if the media type is "official" it should get added to `mime-db` and would work its way into oak eventually.

That of course doesn't solve the problem where you have something custom or you specifically want to assert.  I can it would be useful to have a custom extensions mapping option for `send()`.  I will try to add it soon.

Automatic response handling has a media type field.  The response body handling shouldn't/can't work off extensions. It already has options that deal with custom content types or allow overriding how they are decoded.

**Comment by kitsonk** [comment]
Ok, in main, I added the option `contentTypes` to `send()` so you can do something like this:

```ts
app.use((ctx) => {
  send(ctx, ctx.request.url.pathname, {
    root: ".",
    contentTypes: {
      ".importmap": "application/importmap+json",
    }
  });
});
```

I should be doing a release soon.

**Comment by jaydenseric** [comment]
That solves my particular use case, but what if for example you need `foo.json` to be a particular content type, without modifying the content type for all `.json` files?

Maybe a more flexible design would be:

```js
app.use((ctx) => {
  send(ctx, ctx.request.url.pathname, {
    root: ".",
    contentTypes: {
      "*.importmap": "application/importmap+json",
    }
  });
});
```

**Comment by jaydenseric** [comment]
`send()` is a bit too magical sometimes, it would be nice if there was a function that tells you if a request URL matches a file in a public directory, a function that figures out the cache headers, etc. so you can compose a solution with custom logic to set the response content type the normal middleware way instead of having to learn configuration that has to accommodate every use case, which is pretty difficult.

Also, I don't need any code to run that has anything to do with serving public directory contents via index files, so that could be isolated functionality too.

**Comment by kitsonk** [comment]
`send()` caters to simple use cases. I think if you have an advanced use case, you probably don't want to use `send()`. Overriding particular content types on a server for only certain files seems very much like an advanced use case to me. Most of the APIs send uses, like the range and the etag are seperate modules already with their APIs exposed.

The design for the `contentTypes` option leverages the underlying APIs without putting in a huge amount of functionality.

At this point, I am not minded to add more functionality.
