### ISSUE TITLE
Malformed request can crash server

### ISSUE THREAD

**Issue by dyedgreen** [oakserver/oak#386]
When a server is running and publicly accessible, automated bots will attempt to abuse it with malicious input. This can include malformed requests, so oak should be somewhat resilient to this. I recently got the following error:

```
error: Uncaught (in promise) TypeError: The server request URL of "http:///" is invalid.
        throw new TypeError(
              ^
    at Request.get url (https://deno.land/x/oak@v8.0.0/request.ts:113:15)
    at Application.logErrorListener (https://deno.land/x/oak@v8.0.0/application.ts:198:28)
    at innerInvokeEventListeners (deno:extensions/web/02_event.js:751:9)
    at invokeEventListeners (deno:extensions/web/02_event.js:790:5)
    at dispatch (deno:extensions/web/02_event.js:660:11)
    at Application.dispatchEvent (deno:extensions/web/02_event.js:997:14)
    at Application.#handleError (https://deno.land/x/oak@v8.0.0/application.ts:332:10)
    at Application.#handleRequest (https://deno.land/x/oak@v8.0.0/application.ts:370:26)
```

**Comment by ericls** [comment]
Yep, this is very easy to reproduce
```typescript
import { Application, HttpServerStd, Router} from "https://deno.land/x/oak/mod.ts";

const app = new Application({
  serverConstructor: HttpServerStd,
});


const router = new Router();
router
  .get("/", (context) => {
    context.response.body = "Hello world!";
  })

app.use(router.routes());
app.use((ctx) => {
  ctx.response.body = "404";
});

await app.listen({ port: 8000 });
```

and then 
```
curl -H 'Host;' http://127.0.0.1:8000
```
would crash it

**Comment by ericls** [comment]
All calles to `Request.url` should be wrapped inside a try-catch block.
And preferably expose `Request.path` without requiring `Request.url` and replace some `Request.url` with `Request.path`

**Comment by dyedgreen** [comment]
This does reproduce the exact issue @ericls, thanks for adding the steps to reproduce 😊

I would hope there might be a more general way to prevent such issues though. Afaik, if any error is thrown in user-code that handles a request, the server will not crash but rather return 500 for that request. (Requiring that any user of the given function performs a try catch would be a rather brittle solution imo.)

**Comment by ericls** [comment]
> This does reproduce the exact issue @ericls, thanks for adding the steps to reproduce 😊
> 
> I would hope there might be a more general way to prevent such issues though. Afaik, if any error is thrown in user-code that handles a request, the server will not crash but rather return 500 for that request. (Requiring that any user of the given function performs a try catch would be a rather brittle solution imo.)

I agree, however, I might be wrong, but the missing try-catch seems to be in oak's lib code, it tried to log the errored out url (which would not crash the server?), but getting the url crashed it.

**Comment by dyedgreen** [comment]
The error is thrown inside the lib code as far as I can tell 😅

**Comment by ericls** [comment]
@kitsonk Thank you!
