### ISSUE TITLE
SSE Disconnect Throwing Error

### ISSUE THREAD

**Issue by coreybutler** [oakserver/oak#387]
Oak throws the following error when a client disconnects from an SSE endpoint:

```sh
[uncaught oak error]: Http - connection closed before message completed

    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:216:15)
```

To recreate, use the code found at https://github.com/oakserver/oak/issues/326#issuecomment-869357262

**Setup:**
```
deno 1.13.0 (release, x86_64-pc-windows-msvc)
v8 9.3.345.11
typescript 4.3.5
```

**Detail:**
SSE works as expected until a client disconnects (close a tab, refresh the browser, etc). I also added an event handler for the `error` event in an attempt to intercept the error, but it appears to be rooted elsewhere. 

---

Given the comments in the closed issue cited above, I'm unsure if this is expected behavior. I would not expect Oak to throw an error on every disconnect, but if this is intended behavior, how can this error be caught/handled?

cc @kitsonk

**Comment by alextes** [comment]
Same for me. Not sure whether it is the GCP load balancer or the Google sheets data fetching module closing the connection, but regardless, if either closes the connection (because it has hit a timeout limit somewhere), I do not expect an error. I could see how in other cases this would be an error, but then can we have some way to catch and ignore the error?

**Comment by kitsonk** [comment]
The label is a bit mis-leading... maybe I should change the default logger to `[uncaught application error]`.  It is something that is coming from the internal's of Deno, and could be an indicator to an application that something it thought it had done, didn't complete (that a whole body was not sent).

Too many people were ignoring errors in an oak application, by not implementing middleware that managed them, and so added the logging by default.

It could be meaningful or not depending on the workload.  In this case it seems the environment it runs in causes connections to drop before the body can be fully flushed.  So it feels safe to ignore, but oak doesn't know that.

**Comment by kitsonk** [comment]
I've renamed it and added a section to the FAQ explaining it all a bit better.

**Comment by coreybutler** [comment]
Ah, so the true event emitter is the application, not the context passed to the middleware or the `target` (i.e. not `ctx.sendEvents()`). That makes sense, as does the `logErrors` setting.

This resolves my use case (thanks for clarifying @kitsonk!) and I'll close the issue. 

**Food for thought/future:**

Server sent events will never flush a connection unless the server initiates the termination process. That's just the behavior of SSE, which is essentially an open stream. I'm pointing this out because it is a unique type of connection relative to pretty much everything else you'd do with a web server. It may be nice to have another configuration option to silently ignore specific errors on specific endpoints (like SSE endpoints). Some folks will stream logs to a remote collection service, but these kinds of errors would clog up the logs unnecessarily. Some people may not want to disable error logging entirely, but they may wish to ignore known/acceptable errors like this one. Of course, this could also be done by listening for events and ignoring what you don't want, but this would save some effort on the more peculiar use cases.
