### ISSUE TITLE
Having a crypto key error

### ISSUE THREAD

**Issue by lukaskretzschmer** [oakserver/oak#397]
Hello, I just want to report this error

error: TS2304 [ERROR]: Cannot find name 'CryptoKey'.
export function importKey(key: Key): Promise<CryptoKey> {
                                             ~~~~~~~~~
    at https://deno.land/x/oak@v9.0.0/util.ts:395:46

TS2339 [ERROR]: Property 'importKey' does not exist on type 'SubtleCrypto'.
  return globalThis.crypto.subtle.importKey(
                                  ~~~~~~~~~
    at https://deno.land/x/oak@v9.0.0/util.ts:402:35

TS2304 [ERROR]: Cannot find name 'CryptoKey'.
export function sign(data: Data, key: CryptoKey): Promise<ArrayBuffer> {
                                      ~~~~~~~~~
    at https://deno.land/x/oak@v9.0.0/util.ts:414:39

TS2339 [ERROR]: Property 'sign' does not exist on type 'SubtleCrypto'.
  return crypto.subtle.sign("HMAC", key, data);
                       ~~~~
    at https://deno.land/x/oak@v9.0.0/util.ts:420:24

TS2304 [ERROR]: Cannot find name 'CryptoKey'.
  #cryptoKeys = new Map<Key, CryptoKey>();
                             ~~~~~~~~~
    at https://deno.land/x/oak@v9.0.0/keyStack.ts:12:30

TS2304 [ERROR]: Cannot find name 'CryptoKey'.
  async #toCryptoKey(key: Key): Promise<CryptoKey> {
                                        ~~~~~~~~~
    at https://deno.land/x/oak@v9.0.0/keyStack.ts:15:41

**Comment by kitsonk** [comment]
What version of Deno are you using. V9 of oak requires Deno v1.13 or later.

**Comment by heweicong** [comment]
use deno upgrade before

**Comment by kitsonk** [comment]
Information not provided. Respectfully closing.
