### ISSUE TITLE
Crash while trying to resolve the request body

### ISSUE THREAD

**Issue by Noxdor** [oakserver/oak#410]
My REST API keeps crashing when I'm trying to resolve the promise of `request.body()` and I can't figure out why.

Versions:
deno 1.14.0 (release, x86_64-unknown-linux-gnu)
v8 9.4.146.15
typescript 4.4.2
oak@v9.0.0

This is my controller function signature, where the crash happens (though I tested it also in a GET controller and the same crash happens, it's definitely the resolve of the request body):
```js
export const handleCredentials = async ({ request, response } : Context)
```
This is the function body and the code that breaks the server: 
```js
if (request.hasBody) {
		const data = request.body()
		if (data.type === "json") {
			const json = await data.value
		}
	}
```
It crashes in the line
```js
const json = await data.value
```
The error message is:
> error: Uncaught (in promise) BadResource: Bad resource ID
>     at deno:core/01_core.js:106:46
>    at unwrapOpResult (deno:core/01_core.js:126:13)
>    at async Object.pull (deno:ext/http/01_http.js:309:24)

Can anybody help me with this? I'm happy to provide further information if I forgot to mention something useful.

**Comment by kitsonk** [comment]
What version of oak are you using?

**Comment by kitsonk** [comment]
Can you try `oak@9.0.1`?

**Comment by Noxdor** [comment]
Thank you for your quick reply! I just changed the version to `oak@9.0.1`, unfortunately the same error remains. Is there anything else I could try? Is this a know bug?

**Comment by Noxdor** [comment]
I solved it! The error wasn't caused by oak but by the order of middleware.
Before, causing error:
```js
app.use(parseJSON)
app.use(allowCORS)
app.use(router.routes())
app.use(router.allowedMethods())

```

After, not causing any errors:
```js
app.use(router.routes())
app.use(router.allowedMethods())
app.use(parseJSON)
app.use(allowCORS)
```

The parseJSON and allowCORS middlewares I wrote myself, maybe I made some mistakes or it really matters in which order these are called. In any case, thank you for the suggestion, the error is resolved.

**Comment by kitsonk** [comment]
It is likely the middleware chain got "dropped" by not awaiting the `next()` appropriately.  Need to investigate how to better highlight when that occurs.

**Comment by HPaulson** [comment]
@kitsonk I'm having a similar issue as described in this issue, however I only have the `app.use(router.routes())` & `app.use(router.allowedMethods())` middleware. Are there any other origins that could cause this error?

Src:
```ts
req.body({type: "json"}).value.then((v) => {
  console.log("\nVALUE:", v)}).catch((e) => {
  console.log("\nERROR:", e)});
// ERROR: BadResource: Bad resource ID at async Object.pull (deno:ext/http/01_http.js:299:24)
```
