### ISSUE TITLE
how do I access request headers in oak?

### ISSUE THREAD

**Issue by ralyodio** [oakserver/oak#412]
I tried `request.headers.Authorization` but its not defined.

**Comment by ralyodio** [comment]
this gives error about value possibly being null:

```
  const auth = await request.headers.get('Authorization');
  const jwt = auth.replace(/Bearer /, "");
```

**Comment by ralyodio** [comment]
I"m trying to get the bearer token from the Authorization header

**Comment by aapoalas** [comment]
Check against null and only do the RegExp matching if the value truly is a string.
