### ISSUE TITLE
%2F is being decoded as part of the URI path

### ISSUE THREAD

**Issue by briandoesdev** [oakserver/oak#427]
### Issue
As of at least the latest version of Oak (v9.0.1), the encoded forward slash "%2f" is being treated as part of the URI. This means that the following URLs would both return the same response:
`http://localhost:8000/user/1`
`http://localhost:8000/user%2f1`

Is this expected behavior from Oak? From my (minimal) research W3 does not recommend that they be treated the same:
https://www.w3.org/Addressing/URL/4_URI_Recommentations.html

### Code example
```
import { Application, Router } from 'https://deno.land/x/oak/mod.ts'

const app = new Application()
const router = new Router()

router.get('/user/:id', async (ctx) => {
    ctx.response.body = `user account ${id}`;
});

app.use(router.routes())
app.use(router.allowedMethods())

await app.listen({ port: 8000 })
```
### Expected Behavior
`http://localhost:8000/user%2f1`  is not treated the same as `http://localhost:8000/user/1`

**Comment by kitsonk** [comment]
Looking at how express handles it (https://forbeslindesay.github.io/express-route-tester/) it does no match `/user/:id` against `/user%2f1`, therefore we should treat it differently.
