### ISSUE TITLE
TypeError - Cannot set properties of undefined (setting 'onmessage')

### ISSUE THREAD

**Issue by Srabutdotcom** [oakserver/oak#428]
I Just trying to use native http server but got the following error message when upgrading to Oak 9.0.1 from 9.0.0 while Deno version is 1.16.0.

~~~js
[uncaught oak error]: TypeError - Cannot set properties of undefined (setting 'onmessage')
logErrorListener @ VM106 application.ts:19
innerInvokeEventListeners @ VM14 02_event.js:749
invokeEventListeners @ VM14 02_event.js:788
dispatch @ VM14 02_event.js:658
dispatchEvent @ VM14 02_event.js:989
#handleError @ VM106 application.ts:122
#handleRequest @ VM106 application.ts:155
await (async)
listen @ VM106 application.ts:323
await (async)
(anonymous) @ VM80 www.js:61
~~~

my application start without any option like this
~~~js
const app = new Application()
~~~

while using HttpServerStd, no error arises., the code without error is like this.
~~~js
const app = new Application({serverConstructor: HttpServerStd})
~~~

the code in www.js:61 is as follow:
~~~js
await app.listen(serverConfig());
~~~
while config of server written with the following code

~~~js
const serverConfig = ()=>{
  const config = {
    hostname: hostname, 
    port: port,
  }

  const secureConfig = {
    ...config,
      secure: true,
      certFile: certFilePath[hostname],
      keyFile: keyFilePath[hostname],
  }
  if(port===443){
    return secureConfig
  } else {
    return config
  }
}
~~~

Can anyone help me.

**Comment by Srabutdotcom** [comment]
Sorry. after restarting several times the errors is gone.
I don't know it is related to cache or something...??

**Comment by kitsonk** [comment]
This looks like it might have been an issue with Deno and not oak.

If the problem is still persisting, please provide a complete reproduction.
