### ISSUE TITLE
Q&A: How to get list of implemented routes for router?

### ISSUE THREAD

**Issue by Soremwar** [oakserver/oak#43]
How can I get a list of all the routes that my router has available?
Guiding myself from the self question in Koa something like this can be done:

```typescript
router.get('/', async (context: RouterContext) => {
  context.response.body = "This is a response";
});

router.stack.map(i => i.path);
```

**Comment by kitsonk** [comment]
`Router` instances now have an iterable interface which returns information about the routes registered with the router.

**Comment by Soremwar** [comment]
Thanks @kitsonk !
