### ISSUE TITLE
Request.hasBody always returns true

### ISSUE THREAD

**Issue by rracariu** [oakserver/oak#430]
With Deno 1.16.1 when a Request with method 'DELETE', without body, is done, Oak will report it as having a body.

This comes from the fact that latest Deno `Request` will have a `ReadableStream` as a body.

The issue comes form `this.#request.body instanceof ReadableStream`

**Comment by kitsonk** [comment]
Using Deno 1.16.1 with:

```
> curl --request DELETE --url http://localhost:8000/ 
```

Is setting `.body` to `null` on the `Request` as expected, and therefore reporting `.hasBody` false.

**Comment by rracariu** [comment]
Looks that it is a Windows only issue...

Test program:
```typescript
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
    if (ctx.request.method === 'DELETE' && ctx.request.hasBody) {
        console.log("DELETE Has body")
    }
  ctx.response.body = "42";
});

console.log(`Server running on Deno version: ${Deno.version.deno}`)
console.log(`Os : ${Deno.build.os}, Arch: ${Deno.build.arch}`)

await app.listen({ port: 8085 });
```

Query: `curl --request DELETE --url http://${ip}:8085/`


Windows:
```
Server running on Deno version: 1.16.1
Os : windows, Arch: x86_64
DELETE Has body
```

Linux:
```
Server running on Deno version: 1.16.0
Os : linux, Arch: x86_64
```

**Comment by kitsonk** [comment]
I had a build from Deno main, but it was a cached build, I cleared my cache and rebuilt and can see the behaviour in Deno 1.6.1.

I believe Deno has a regression.  I opened denoland/deno#12741.
