### ISSUE TITLE
Type '{}' is not assignable to type 'RouteParams<R>'

### ISSUE THREAD

**Issue by rabbitkiller-dev** [oakserver/oak#438]
![image](https://user-images.githubusercontent.com/28952169/145960515-72d98c1a-1a7c-4e2d-9adb-637ab6050642.png)

> deno 1.16.4+c9d32e0 (canary, x86_64-pc-windows-msvc)
> oak 10.0.0

**Comment by kitsonk** [comment]
Already fixed in 2e76d128364c5f666873e3676dc94d64fe8e6dd2. Will release a version concurrently with 1.17.

**Comment by sisou** [comment]
v1.17 is out now: https://deno.com/blog/v1.17

**Comment by kitsonk** [comment]
Yeah, I know. I helped release it.
