### ISSUE TITLE
`Transfer-Encoding:chunked` in request headers causes `UnexpectedEOFError`

### ISSUE THREAD

**Issue by horihiro** [oakserver/oak#47]
I tried to send `HTTP GET` request with `Transfer-encoding: chunked` in the request header such as following command then. 
```sh
$ curl "http://localhost:8000" -H "Transfer-encoding: chunked"
```

Then http server process faced `UnexpectedEOFError`.

```sh
error: Uncaught UnexpectedEOFError: Unexpected EOF
► io.ts:66:34

66     if (line === Deno.EOF) throw new UnexpectedEOFError();
                                    ^

    at UnexpectedEOFError (bufio.ts:28:5)
    at read (io.ts:66:34)
```

server.ts is following.
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use(ctx => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

**Comment by horihiro** [comment]
Current workaround I'm using is to remove `transfer-encoding` header from request headers when the request method is `GET`.

I'm not sure if this is appropriate workaround...

```ts
app.use(async (context, next) => {
  await next();
  if (context.request.method.toLowerCase() !== 'get') return;
  context.request.headers.delete('transfer-encoding');
});
```

**Comment by kitsonk** [comment]
Should support transfer encoding

**Comment by kitsonk** [comment]
I've believe that this was due to upstream issue not handling chunked content encoding that is now resolved.

I have tested with the `example/echoServer.ts` with the following which appears to work as expected:

```shell
$ curl -H "Transfer-Encoding: chunked" -H "Content-Type: text/plain" -d "10\r\noak server\r\n0\r\n\r\n" http://localhost:8000/
```
