### ISSUE TITLE
Doesn't sent body with Deploy to browsers

### ISSUE THREAD

**Issue by natebowang** [oakserver/oak#484]
My project is using the following snippet from the [Readme](https://better-world-app-hnf603jpnd3g.deno.dev/) to serve static files:
```ts
import { Application, Context, Router } from "https://deno.land/x/oak@v10.4.0/mod.ts"

app.use(async (context: Context) => {
	await context.send({
		root: `${Deno.cwd()}/public`,
	});
})
```

It works well with localhost. But when it got [deployed](https://better-world-app-85pgdx6ej0bg.deno.dev/), several strange behaviours happens: 
* In Chrome, Firefox and Safari, it serves correct response headers like `cache-control`, `content-type`, `content-length` and `etag`. However, it doesn't send the body most of the time. 
* The **only** file it serves correctly is the `favicon.png`. All the other files, like `favicon.svg`, `index.css`, `reset.js`, `robots.txt`, no body as described above. 
* With `curl`, it works well. 
* When I disabled compression, the response headers still contains `content-encoding: gzip`
```diff
app.use(async (context: Context) => {
	await context.send({
		root: `${Deno.cwd()}/public`,
+		gzip: false,
+		brotli: false,
	});
})
```

I didn't get any logs from the Deploy. 

Thank you ver much for maintaining this project. Please let me know if I can provide any further information.

**Comment by kitsonk** [comment]
This was an issue with automatic body compression that was occurring with Deploy and didn't specifically have anything to do with oak. The underlying issue has been fixed, and this should be working now.

**Comment by natebowang** [comment]
Thanks for the reply, It works now.
