### ISSUE TITLE
support app.listen()

### ISSUE THREAD

**Issue by ry** [oakserver/oak#485]
In Deploy users are encouraged to do `app.listen({ port: 0 });` the `{ port: 0 }` is boilerplate. It would be good if Oak supported `app.listen()`

**Comment by kitsonk** [comment]
This is because the options extends `Deno.ListenOptions` which also requires a port number. I can change it for oak, but we should consider defaulting `Deno.ListenOptions` to 0 as well.

**Comment by kitsonk** [comment]
Closed in 5bd4e2baf18e2149afcbe5887ab586eab1bd292d
