### ISSUE TITLE
Router Context Type

### ISSUE THREAD

**Issue by Teddy-Schmitz** [oakserver/oak#507]
Hello,

I'm adding context types to my handlers like so 

`handler(ctx: Context<RequestContext>)` and everything works great, but when I add an application context to it like `handler(ctx: Context<RequestContext, ApplicationContext>)` the Router throws up a type error.  I'm pretty new to Typescript so I might be missing something obvious but I couldn't figure out the right combination of generics to give to the router to get it to work.  Example error

```
S2345 [ERROR]: Argument of type '(ctx: Context<RequestContext, AppContext>) => Promise<void>' is not assignable to parameter of type 'RouterMiddleware<"auth/refresh", Record<string | number, string | undefined>, RequestContext>'.
  Types of parameters 'ctx' and 'context' are incompatible.
    Type 'RouterContext<"auth/refresh", Record<string | number, string | undefined>, RequestContext>' is not assignable to type 'Context<RequestContext, AppContext>'.
      Types of property 'app' are incompatible.
        Type 'Application<Record<string, any>>' is not assignable to type 'Application<AppContext>'.
  .post("auth/refresh", refresh)
```

Reading through the Router code it wasn't obvious to me how exactly to get it all to work correctly.  If you can point me in the right direction that would be helpful and I'm sure helpful to others who run into this as well.

Thank you

**Comment by bodograumann** [comment]
You shouldn’t have to define explicit parameter types for your middlewares. They are automatically inferred from method where you use them.

If you really want to define reusable middlewares, you can do it like this:
```
async function checkWriteAccess<
  R extends string,
  P extends { param: string }
>(context: RouterContext<R, P, AppState>, next: () => Promise<unknown>) {
  …
}
```
