### ISSUE TITLE
error: Uncaught PermissionDenied: network access to "127.0.0.1:8000", run again with the --allow-net flag

### ISSUE THREAD

**Issue by peidrao** [oakserver/oak#51]
Hey, guys, how are you?
I'm starting my studies with the deno and I came across the following message: what could be wrong?

```
peidrao in deno on  master [?] took 11s 
❯ sudo deno helloDenos.ts
Compile file:///home/peidrao/deno/helloDenos.ts
error: Uncaught PermissionDenied: network access to "127.0.0.1:3000", run again with the --allow-net flag
► $deno$/ops/dispatch_json.ts:43:11
    at PermissionDenied ($deno$/errors.ts:81:5)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at listen ($deno$/ops/net.ts:50:10)
    at listen ($deno$/net.ts:168:18)
    at serve (server.ts:251:20)
    at listen (application.ts:29:25)
    at helloDenos.ts:8:5
```

**Comment by matt-landers** [comment]
@peidrao Deno is secure by default, so you need to tell Deno to allow network access. Try:
```
deno --allow-net helloDenos.ts
```
Other flags you will want to be aware of are: 
- Environment Variables: `--allow-env`
- Read filesystem: `--allow-read`
- Write filesystem: `--allow-write`

There are a few others, but those should get you rolling.

**Comment by peidrao** [comment]
That's it. Thanks!

**Comment by alinaserinet** [comment]
`deno --allow-net helloDenos.ts` not work 
i think use `deno run --allow-net helloDenos.ts`

**Comment by kitsonk** [comment]
It was valid at the time the bug was reported.  Deno has changed since then.
