### ISSUE TITLE
Params property in Context type

### ISSUE THREAD

**Issue by marcosadriano05** [oakserver/oak#516]
I have been make an adapter to integrate my controllers with Oak Router, but i can't get the route params because Context type don't have params property. For exemple:

On adpater, instructions like this works:
`const body = context.request.body({ type: "json"}).value`
`const headers = context.request.headers`

But the route params don't work:
`const params = context.params` don't work because `context: Context` don't have params property.

The adapter is like:
`const adapter => (controller: Controller) => (context: Context) => {}`

And its use on router definition, for exemple:
`router.get("/car/:id", adapter(getCarController())`

Any sugestions to resolve this problem? My sugestion is to implement params property in Context type too.

**Comment by abdulrahman1s** [comment]
I had the same issue :disappointed_relieved:

**Comment by abdulrahman1s** [comment]
okay solved by using the `RouterMiddleware` instead of `Middleware`

**Comment by sonickseven** [comment]
Use like this:

```typescript
import { RouterContext } from 'https://deno.land/x/oak@v12.1.0/mod.ts';

const adapter => (controller: Controller) => (context: RouterContext<strig>) => {}

```


It works for me :)

**Comment by nik-kita** [comment]
> Use like this:
> 
> ```ts
> import { RouterContext } from 'https://deno.land/x/oak@v12.1.0/mod.ts';
> 
> const adapter => (controller: Controller) => (context: RouterContext<strig>) => {}
> ```
> 
> It works for me :)
Thanks!
(only add some notes, showing my custom case)

if i correctly understand, it works as type-checker.
try to use with incorrect route:
![image](https://github.com/oakserver/oak/assets/53253722/b09671c5-2622-49fc-8e94-23a9a495846b)
change to correct spelling:
![image](https://github.com/oakserver/oak/assets/53253722/aa8e4b4c-0f17-4202-a3b2-5018d6353cf0)
