### ISSUE TITLE
It's not run

### ISSUE THREAD

**Issue by idanran** [oakserver/oak#518]
```js
export * as oak from "https://deno.land/x/oak@v10.5.1/mod.ts"
```
```
Download https://raw.githubusercontent.com/jshttp/mime-db/v1.52.0/db.json
error: error sending request for url (https://raw.githubusercontent.com/jshttp/mime-db/v1.52.0/db.json): error trying to connect: dns error: 请求的名称有效，但是找不到请求的类型的数据。 (os error 11004)
    at https://deno.land/x/media_types@v3.0.2/mod.ts:32:16
```
It means "the name of the request is valid, but the data of the requested type cannot be found"

OS: Windows 11
Deno: 1.21.1
Oak: 10.5.1

**Comment by git136975643** [comment]
export * as from "https://deno.land/x/oak@v10.5.1/mod.ts"

**Comment by kitsonk** [comment]
You are experiencing issues related to the [Great Firewall of China](https://en.wikipedia.org/wiki/Great_Firewall) which blocks access to raw github.
