### ISSUE TITLE
拿不到哈希值

### ISSUE THREAD

**Issue by git136975643** [oakserver/oak#522]
http://localhost:8090/test?a=1&b=2#a2

oak好像拿不到hash值

**Comment by kitsonk** [comment]
> Can't get hash value

> oak doesn't seem to get the hash value

Hash parts of URL tend to be client side constructs and do not appear in the HTTP request, therefore because they don't appear in the HTTP request, they are not available in the `Request.prototype.url`, and therefore are not parsed out by oak.
