### ISSUE TITLE
how to destroy db using oak?

### ISSUE THREAD

**Issue by ralyodio** [oakserver/oak#526]
I need a way to create `const db new DB('database.sqlite')` somehow and share the `db` object.

I also need a way to call `db.close()` when oak is done executing all the code.

What's the best way to do this?

**Comment by Ericarthurc** [comment]
You can pass the db object to the ctx.state. object from a middleware that you set at the top level, above all your routers. 
This will give you access to the db object on like `ctx.state.db` (or whatever you name it) on all your controllers/handlers/middleware.

You will also probably have to pass a generic state type object to your oak.app object, because it has to be aware of the object your adding to ctx.state.

```ts
const db = new DB('database.sqlite')

app.use(ctx => {
    ctx.state.db = db
})
```

**Comment by Ericarthurc** [comment]
Scroll to the bottom of: https://oakserver.github.io/oak/FAQ

This is example of global state and it shows how to set the custom State interface on the oak.app object

**Comment by ralyodio** [comment]
So I get this error now:

```
error: TS2347 [ERROR]: Untyped function calls may not accept type arguments.
    const user = await db.query<any[]>(
                       ^
    at file:///home/ettinger/www/grazily.com/grazily-api/src/controllers/users.ts:25:24

TS2347 [ERROR]: Untyped function calls may not accept type arguments.
      await db.query<any[]>(
            ^
    at file:///home/ettinger/www/grazily.com/grazily-api/src/controllers/users.ts:93:13

TS2347 [ERROR]: Untyped function calls may not accept type arguments.
      await db.query<any[]>(
            ^
    at file:///home/ettinger/www/grazily.com/grazily-api/src/controllers/users.ts:116:13

TS2347 [ERROR]: Untyped function calls may not accept type arguments.
      const query = db.prepareQuery<unknown[]>(
                    ^
    at file:///home/ettinger/www/grazily.com/grazily-api/src/controllers/users.ts:154:21

Found 4 errors.
```

when trying to use it.

```
async update(context: any) {
    const { db }: { db: any } = context.state;
...
}
```

**Comment by ralyodio** [comment]
```
const user = await db.query<any[]>(
      "INSERT INTO users (id, email, username, hashed_password, created_at, updated_at, contactme, phone, location) VALUES (?,?,?,?,?,?,?,?, ?)",
      [
        Users.getRandomId(),
        body.email.toLowerCase(),
        body.username.toLowerCase(),
        hashedPassword,
        Users.getCurrentTime(),
        Users.getCurrentTime(),
        body.contactme,
        body.phone,
        body.location,
      ]
    );
```

here's where the error is thrown.

**Comment by ralyodio** [comment]
Any ideas?

**Comment by ralyodio** [comment]
I don’t know how to do this. I’m new to typing. Can you give example?

**Comment by ralyodio** [comment]
Sorry I’m asking how to properly type my db functions to avoid the error

**Comment by Ericarthurc** [comment]
@ralyodio 
What's the sqlite package your using? What the URL to it? I'll take a look and try it help you get the type

**Comment by ralyodio** [comment]
https://deno.land/x/sqlite@v3.4.0

**Comment by ralyodio** [comment]
any info would be helpful

**Comment by Ericarthurc** [comment]
@ralyodio 

```ts
import { DB } from 'https://deno.land/x/sqlite/mod.ts';
import { Application } from 'https://deno.land/x/oak/mod.ts';

const db: DB = new DB('test.db');
db.query(`
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT
  )
`);

interface MyState {
  database: DB;
}

const app = new Application<MyState>();

app.use(async (ctx, next) => {
  ctx.state.database = db;
  await next();
  ctx.state.database.close();
});

app.use((ctx, next) => {
  console.log('here');

  const { database }: { database: DB } = ctx.state;
  const user = database.query(
    'INSERT INTO users (username) VALUES (?) RETURNING *',
    ['Test user']
  );
});

app.listen({ port: 4000 });
```

**Comment by ralyodio** [comment]
this caused too many problems. db getting closed before queries finish.

**Comment by ralyodio** [comment]
`[uncaught application error]: Http - connection closed before message completed`

**Comment by Ericarthurc** [comment]
@ralyodio 

Remove the delete line
And dont do `new DB` in the function. 

Make it a constant outside the function then reference it in the function like:

```ts
const db: DB = new DB('test.db');

app.use(async (ctx, next) => {
  ctx.state.database = db;
  await next();
  ctx.state.database.close();
});
```

**Comment by ralyodio** [comment]
you still can't use db if you close it.

Only this seems to work for me:

```
//Db
app.use(async (ctx, next) => {
  const db = await new DB("database.sqlite");
  const mongo = await client.connect("mongodb://127.0.0.1:27017");
  ctx.state.db = db;
  ctx.state.mongo = mongo;
  await next();
  ctx.state.db.close();
  client.close();
});
```

**Comment by ralyodio** [comment]
Well this doesn’t work either. Db is still being closed before queries are finished.

**Comment by Ericarthurc** [comment]
@ralyodio 

Your app.use() function isn't right

```ts
app.use(async (ctx, next) => {
  const db = new DB("database.sqlite");
  const mongo = await client.connect("mongodb://127.0.0.1:27017");
  ctx.state.db = db;
  ctx.state.mongo = mongo;
  await next();
  ctx.state.db.close();
  client.close();
});
```
Lets take a look at this. Every time your web server is 'hit' by a request this app.use() function is going to run. So as of right now, you have the lines:
```ts
const db = new DB("database.sqlite");
const mongo = await client.connect("mongodb://127.0.0.1:27017");
```

These lines are inside your app.use() function, so every time your web server is hit by a web request your creating a new database connection. This isn't going to work. So that's issue 1. Pull the `db` and `mongo` variables out of this function at put them at the global level like this:

```ts
const db = new DB("database.sqlite");
const mongo = await client.connect("mongodb://127.0.0.1:27017");

app.use((ctx, next) => {
     ctx.state.db = db;
     ctx.state.mongo = mongo;
})
```


Second issue, after the `await next();` you have:
```ts
ctx.state.db.close();
client.close();
```
These are again inside this app.use() function that is called on every request. You can actually just get rid of them completely. The better bet it to target the deno event listener for the close event on the server and then close the database connections there. 

```ts
interface MyState {
    db: DB;  (these types you need to get from your imports)
    mongo: mongo.Database; (these types you need to get from your imports)
}

const db = new DB("database.sqlite");
const mongo = await client.connect("mongodb://127.0.0.1:27017");

const app = new oak.Application<MyState>();

app.use((ctx, next) => {
     ctx.state.db = db;
     ctx.state.mongo = mongo;
     await next();
})
```

**Comment by ralyodio** [comment]
yeah but if you never close it (the process never ends) eventually server runs out of ram. That was the whole reason I went down this road.

There's need to be a "we're done, now close the db connections" feature.

**Comment by Ericarthurc** [comment]
@ralyodio

I am not sure what you mean by the server runs out of ram. What server? Looks like your trying to make a local .sqlite file and also a call to a mongoDB database. The point of the Deno web server is to never end, you want 100% uptime right? If you manually close the deno process running your webserver, everything will be cleaned up. 

If you keep creating your database objects in your app.use() middleware, this is just going to keep recreating your connection over and over which will use all your ram. You need to make your database initializations in the global scope once. So right when the Deno process starts it will create a connection to the database, then you can pass that connection object around your file. This is handled like a pointer in your program, it doesn't keep making a new connection everytime using ram. When you make that `const db = new DB("database.sqlite");`, the `db` object is a class object of type `DB`. When you then assign it to `ctx.state.db` (or whatever you name it) this isn't making a new `db` object everytime. Its passing it as a reference or also know as a pointer. JavaScript uses garbage collection and you can't manually manage the memory, but things can still be set on the memory heap verses the stack. Objects are placed on the heap meaning when you call them the variable isn't recreated in memory everytime, the runtime points to the pointer that points to the underlying data.

If you want to clean up your database objects before the web server itself closes then you can look into close event listeners for Deno, then hook into it and call your database close methods. 

If you are using a database pool then you would make a new pool at the start of a handler, then close the pool conenction at the end of the http handler function, but thats closing one of the pools not the the whole database connection itself.

**Comment by ralyodio** [comment]
Apparently even wit your suggestions it’s making more than one connection. I don’t know why.

**Comment by ralyodio** [comment]
so i figured out why. i have a model User.ts which was connecting to its own DB.

I had to write all models to have a constructor i can pass in `ctx.state.db` to and then models will use the one setup in the middle.

I deployed this and haven't had any problems in 24 hours so I'm closing this issue.

Thanks for the help!

**Comment by Ericarthurc** [comment]
> so i figured out why. i have a model User.ts which was connecting to its own DB.
> 
> I had to write all models to have a constructor i can pass in `ctx.state.db` to and then models will use the one setup in the middleware instead of creating a new connection to db.
> 
> I deployed this and haven't had any problems in 24 hours so I'm closing this issue.
> 
> Thanks for the help!

Awesome! Glad to help 😀
