### ISSUE TITLE
Oak can not handle concurrent HTTP/2 requests on the same connection

### ISSUE THREAD

**Issue by lucacasonato** [oakserver/oak#528]
In HTTP/2 multiple requests can be sent on the same connection concurrently. Oak does not support this, as all HTTP/2 requests are handled sequentially.

This can be observed in this code:

https://github.com/oakserver/oak/blob/c4fe8b35c0362b9b153e1cf8af4081c7a3905834/http_server_native.ts#L112-L132

The current requests is awaited (line 122) before the next one is accepted. This is a bad assumption, only valid for HTTP/1.1.

@kitsonk Have you considered using `std/http#serve` instead of re-implementing it here in Oak?

**Comment by KyleJune** [comment]
Here is what sparked this issue. If I refreshed multiple times my deployment would end up hanging.
https://github.com/denoland/deploy_feedback/issues/212

**Comment by JeDaYoshi** [comment]
This is a considerable issue in Deno Deploy, where you can only serve 1 request at a time, and things like Server-Sent Events makes any other new requests hang indefinitely.

**Comment by cmorten** [comment]
> Have you considered using std/http#serve ...

Worth noting that the std lib doesn't currently support h2 afaik - see https://github.com/denoland/deno_std/blob/main/http/server.ts#L238

**Comment by lucacasonato** [comment]
@cmorten It does if you use `serveListener` and set up the listeners yourself

**Comment by cmorten** [comment]
> @cmorten It does if you use `serveListener` and set up the listeners yourself

Very true!
