### ISSUE TITLE
[Proposal] Make `Router.useVerb` public

### ISSUE THREAD

**Issue by ayakovlenko** [oakserver/oak#531]
I'm building a server that is generated based on an external definition, something like:

```ts
const server: Server = [
  {
    method: "GET",
    path: "/foo",
    action: doSomething,
  },
  {
    method: "POST",
    path: "/foo",
    action: doSomethingElse,
  },
]
```

It would be helpful if `Router` would expose `useVerb` method directly.

**Comment by kitsonk** [comment]
I wouldn't want to expose `#useVerb` directly, but I have recently added `Router.prototype.add()` in b8d0e8005835b84d641589a91a4c72dc8d2bfe46 which I think effectively meets this use case.
