### ISSUE TITLE
Should change media_types to std/media_types?

### ISSUE THREAD

**Issue by jiawei397** [oakserver/oak#532]
The package referenced in recent versions references [media_types](https://deno.land/x/media_types@v3.0.3/mod.ts) , but it uses a resource on GitHub, which some times my network may fetch fail.

```ts
import db from "https://raw.githubusercontent.com/jshttp/mime-db/v1.52.0/db.json" assert {
  type: "json",
};
```

Now the media_types has been deprecated because [this](https://deno.land/std@0.142.0/media_types):
> This package is deprecated, as the fundamentals of this package were integrated into the Deno standard library under [std/media_types](https://deno.land/std/media_types) as of Deno std version 0.142.0. You can view the documentation [here](https://doc.deno.land/https://deno.land/std/media_types/mod.ts).

So could you make a replacement?

**Comment by kitsonk** [comment]
Yes. It is in progress.  I maintain/own both projects and am the one who moved it to `std`.

**Comment by jiawei397** [comment]
That would be great. I hope the good news will come soon. thank!
