### ISSUE TITLE
Remove `vary` header from response

### ISSUE THREAD

**Issue by aabedraba** [oakserver/oak#538]
I'm using a gateway and need my requests to be cached by the gateway, but oak is adding a `vary` header to the response (most probably added by the http std library) which I need not to be there for the request to be cached. 

From the Envoy docs: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/cache_filter

> HTTP Cache respects Cache-Control directive from the upstream host. For example, if HTTP response returns status code 200 with Cache-Control: max-age=60 **and no vary header,** it will be cached.

Is there a way to remove the `vary` from the response?

**Comment by cmorten** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/cache/v3/cache.proto#envoy-v3-api-msg-extensions-filters-http-cache-v3-cacheconfig

> allowed_vary_headers
> (repeated [type.matcher.v3.StringMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/string.proto#envoy-v3-api-msg-type-matcher-v3-stringmatcher)) List of matching rules that defines allowed Vary headers.
>
> The vary response header holds a list of header names that affect the contents of a response, as described by https://httpwg.org/specs/rfc7234.html#caching.negotiated.responses.
>
> During insertion, allowed_vary_headers acts as a allowlist: if a response’s vary header mentions any header names that aren’t matched by any rules in allowed_vary_headers, that response will not be cached.
>
> During lookup, allowed_vary_headers controls what request headers will be sent to the cache storage implementation.

By the looks of the docs caching based on `vary` headers is supported. This is linked to from your link in the first section as “v3 API reference”.

**Comment by kitsonk** [comment]
Actually it is unlikely oak setting the `vary` header. It is likely being set by Deno.

**Comment by cmorten** [comment]
Unable to find any explicit reference in Oak so suspect you’re right.

@aabedraba would recommend giving the envoy `allowed_vary_headers` allowlist a go 😊

**Comment by kitsonk** [comment]
It is specifically a feature of [Deno CLI and Deploy](https://github.com/denoland/deno/blob/5e0fa5dd887ab05efef16ecc54491bd657410377/ext/http/lib.rs#L637-L640):

```rust
// Set Vary: Accept-Encoding header for direct body response.
// Note: we set the header irrespective of whether or not we compress the data
// to make sure cache services do not serve uncompressed data to clients that
// support compression.
```

It is because they both support automatic body compression and as the comment states, the header is set to ensure the correct behaviour of cache services.

**Comment by aabedraba** [comment]
Thank you so much @cmorten @kitsonk for the detailed help. I should've noticed the allowlist in Envoy, I'll give that a go! 

Happy to close this issue 😊
