### ISSUE TITLE
Support for performing redirect.

### ISSUE THREAD

**Issue by brianraila** [oakserver/oak#54]
Is there currently support for redirects from the server side? Can't find it anywhere in the code or documentation.

**Comment by kitsonk** [comment]
@brianraila you would simply respond with a `302`, `303`, or `307` (see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections or other resources).

It might make a good example or a good tutorial, but basic HTML "stuff" isn't really an issue with oak per-say, so closing.

**Comment by clfhhc** [comment]
Here's my hack:
```js
router.get("/some-route", (ctx) => {
  const newRoute = ctx.request.url.origin + "/some-new-route";
  ctx.response.headers.append("Location", newRoute);
  // or ctx.response.headers.set("Location", newRoute);
  ctx.response.status = 302; // or 303, 307, 308
})
```

**Comment by kitsonk** [comment]
There is now support for `ctx.response.redirect()` in 385bdc66f73fd153fbebe64fdd1375a229789ed3.
