### ISSUE TITLE
OPTIONS request returns non standard 'Allowed' instead of 'Allow' header in Router.allowedMethods middleware

### ISSUE THREAD

**Issue by Momics** [oakserver/oak#554]
I was experimenting with this package and noticed OPTIONS requests returning an 'Allowed' header instead of 'Allow'. As far as I am aware this is non-standard. [Reference to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow)

I checked Koa's implementation and they use an 'Allow' header:
https://github.com/koajs/router/blob/d2ad8491fd8484aab465d30d1f9a18a49ecf4fe1/lib/router.js#L509

The line that would need changing:
https://github.com/oakserver/oak/blob/79197530128d5f28161ead20761cbcb524be53a3/router.ts#L707

**Comment by kitsonk** [comment]
First person in years to catch this, wow.
