### ISSUE TITLE
Custom HTTP Methods?

### ISSUE THREAD

**Issue by tclzcja** [oakserver/oak#558]
Hi there, just wonder is there a way to accept custom HTTP Methods/Verb in Oak? Like "LOGIN", "SIGN", etc. 

According to:

https://www.rfc-editor.org/rfc/rfc9110.html#name-methods

Custom HTTP Methods are allowed in HTTP.

**Comment by kitsonk** [comment]
I have expanded the methods that are strongly typed in b8d0e80 which now matches what Node.js `http` module supports as methods (as well as added `Router.prototype.add()` which allow specifying an array of methods), but I am really hesitant to just set it to string.

Technically, anything passed from the server is supported, it just won't be valid types and would require casting as `any`, which feels like a good balance.
