### ISSUE TITLE
Feature: Generate a open api documentation generation

### ISSUE THREAD

**Issue by Marek00Malik** [oakserver/oak#561]
I'm not sure if this is already available (although I have not seen anything that would say so). 

It would be extremely nice to have the possibility to generate an API documentation of the rest API that is exposed for consumers using oak on our Deno servers (and maybe serve with ReDoc or Swagger UI). 

This is a big problem for us as we are unable to provide proper documentation and prepare automated integrations with services done in Deno. 

Is there any chance that this would be provided, or there is already some work going on to make this feature happen?

**Comment by Lesiuk** [comment]
What about https://www.npmjs.com/package/swagger-jsdoc ?

**Comment by kitsonk** [comment]
This is ultimately out of scope for this project and would be something that would be a great lager community project.
