### ISSUE TITLE
Add proxy middleware options getter for fetch

### ISSUE THREAD

**Issue by wgehring-ml** [oakserver/oak#566]
I have a proxy implementation which needs to use `digest` authentication, which I am currently using [digest_fetch](https://deno.land/x/digest_fetch@v1.2.1) for, but in order to support multiple client sessions I need to be able to use the `fetch` implementation supplied by a `DigestClient` instance instead of a fixed `fetch` for the entire proxy.

Right now I'm getting around the issue by using a class

```ts
interface Session {
  readonly client: DigestClient;

  // ...
}

class ProxyOpts<R extends string, P extends RouteParams<R>, S extends { session: Session }> implements ProxyOptions<R, P, T> {
  #session: Session | undefined;

  constructor(opts: ProxyOptions<R, P, S>) {
    for (const [key, value] of Object.entries(opts)) {
      this[key] = value;
    }
  }

  get fetch() {
    return (...a) => this.#session.client.fetch(...a);
  }

  headers = (ctx: Context<S>) => {
    this.#session = ctx.state.session;

    // ...
  }
}

router.all('/api/:path*', proxy('http://domain/endpoint/', new ProxyOpts({
  // ...
}));
```

but obviously this is quite a messy solution, and I would prefer a cleaner option, which would be to provide a function in the proxy options which can return the `fetch` implementation to use based on the request context, e.g.:

```ts
router.all('/api/:path*', proxy('http://domain/endpoint/', {
  fetch(ctx) { return (...a) => ctx.state.session.client.fetch(...a); },
  // ...
});
```

**Comment by kitsonk** [comment]
This is already supported: https://deno.land/x/oak@v12.2.0/middleware/proxy.ts?s=ProxyOptions#prop_fetch

**Comment by wgehring-ml** [comment]
I can pass a custom `fetch` implementation but that implementation is not given a context object for me to retrieve anything from the context state, e.g. session information.
