### ISSUE TITLE
Signing a cookie creates two cookies (unsigned and signed)

### ISSUE THREAD

**Issue by gnom1gnom** [oakserver/oak#582]
In oak@v11.1.0 when trying to set a signed cookie, two cookies are created - unsigned and a signed
```
const appOptions = { keys: ["secretForCookieSign"] };
const app = new Application<AppState>(appOptions);
app.use(async (ctx, next) => {
  await ctx.cookies.set("lastVisit", new Date().toISOString(), { signed: true });
  next();
});
```
The response in a browser looks as follows:
```
content-encoding: gzip
content-length: 181
content-type: application/json; charset=UTF-8
date: Tue, 10 Jan 2023 16:29:45 GMT
set-cookie: lastVisit=2023-01-10T16:29:45.721Z; path=/; httponly
set-cookie: lastVisit.sig=4R-4psaVH18u4kpynvRBEKLS39FEagMx-419hkVq6jg; path=/; httponly
vary: Accept-Encoding
x-response-time: 0ms
```

This seems to happen by design as the code in [cookies.ts](https://github.com/oakserver/oak/blob/main/cookies.ts#L312) calls pushCookie twice, when signed is true
```
    const cookie = new Cookie(name, value, options);
    cookie.secure = options.secure ?? secure;
    pushCookie(headers, cookie);

    if (signed) {
      if (!this.#keys) {
        throw new TypeError(".keys required for signed cookies.");
      }
      cookie.value = await this.#keys.sign(cookie.toString());
      cookie.name += ".sig";
      pushCookie(headers, cookie);
    }
```
What is the reason for such behavior?

**Comment by lundsholm** [comment]
I have the same issue.

oak@v11.1.0
```bash
> deno --version
deno 1.29.4 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```
The only successful workaround is to either set the `set-cookie` header on your own or use `ctx.cookies.set` but manually clean the response headers and set the signed cookie again.

If I clean the headers and only return the signed cookie in the response and then try to use `ctx.cookies.get` on the following incoming requests, I only get undefined. From what I can tell, the signed cookie is not recognized and, therefore, removed.

**Comment by kitsonk** [comment]
They way you set multiple cookies in a response is to set multiple `Set-Cookie` headers.  The `.sig` of the cookie is a signature, which is then used on subsequent requests to validate that the cookie has not been tempered with by the client.  So everything you see is quite intentional.

What issue is this causing?

**Comment by kitsonk** [comment]
No response, closing.
