### ISSUE TITLE
`ctx.request.body({ type: "json" })` with no body: `RangeError: Body exceeds a limit of 10485760`

### ISSUE THREAD

**Issue by rijenkii** [oakserver/oak#583]
Source:
```typescript
import { Application, Router } from "https://deno.land/x/oak@v11.1.0/mod.ts";

const router = new Router()
  .post("/", async (ctx) => {
    console.log(await ctx.request.body({ type: "json" }).value);
    ctx.response.body = "";
  });

await new Application().use(router.routes()).use(router.allowedMethods())
  .listen({ port: 8000 });
```

Making a `curl -X POST localhost:8000` request results in a following exception:
```
[uncaught application error]: RangeError - Body exceeds a limit of 10485760.

request: { url: "http://localhost:8000/", method: "POST", hasBody: true }
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at Object.value (https://deno.land/x/oak@v11.1.0/body.ts:243:28)
    at file:///tmp/repro/main.ts:5:55
    at dispatch (https://deno.land/x/oak@v11.1.0/middleware.ts:41:13)
    at https://deno.land/x/oak@v11.1.0/router.ts:1229:20
    at dispatch (https://deno.land/x/oak@v11.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v11.1.0/middleware.ts:44:12)
    at dispatch (https://deno.land/x/oak@v11.1.0/router.ts:1235:22)
    at dispatch (https://deno.land/x/oak@v11.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v11.1.0/middleware.ts:44:12)
    at Application.#handleRequest (https://deno.land/x/oak@v11.1.0/application.ts:436:32)
```

**Comment by marc-tech** [comment]
same here

the apiClient : 
<img width="477" alt="Capture d’écran 2023-02-10 à 13 47 02" src="https://user-images.githubusercontent.com/15327831/218096087-56fb5ccc-dcb1-4cb6-ae22-006e0ea181f0.png">

the oak controller :
<img width="613" alt="Capture d’écran 2023-02-10 à 13 50 10" src="https://user-images.githubusercontent.com/15327831/218096730-c10728bd-a380-437e-90ff-626163df74af.png">

the response : 
```{ "error": "Body exceeds a limit of 10485760." }```


MORE INFO
I use the nuxt3 useFetch
I guess the code in cause is here : https://github.com/oakserver/oak/blob/main/body.ts#L241
my request payload :
<img width="495" alt="Capture d’écran 2023-02-10 à 13 52 49" src="https://user-images.githubusercontent.com/15327831/218097520-2d16d9e7-7fd0-43f4-974a-1342c924b3e1.png">

**Comment by MStefan99** [comment]
Yes, same here on 11.1.0. Example in the first comment throws an exception.
Here is a request I noticed this on:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/43060374/219014155-268bde49-812a-49a6-a0f0-b409a340abf7.png">

**Comment by marc-tech** [comment]
it's working for me now, like this : (on the left the api client on nuxt js | on the right the deno edge function)
<img width="1127" alt="Capture d’écran 2023-02-16 à 01 43 23" src="https://user-images.githubusercontent.com/15327831/219228666-a5aee364-2f9f-4826-bee9-cd56f937e970.png">
