### ISSUE TITLE
, got Some(Word(P)) at https://deno.land/x/oak@v12.0.0/router.ts:184:11

### ISSUE THREAD

**Issue by OLM0** [oakserver/oak#592]
On deno cache i am presented with the following error:

```
error: Expected RBrace, got Some(Word(P)) at https://deno.land/x/oak@v12.0.0/router.ts:184:11
```

Any idea how to solve it?

**Comment by kitsonk** [comment]
That is an internal Deno error related to parsing the source code. What version of Deno are you using? I cannot reproduce on the current version of Deno.

**Comment by OLM0** [comment]
Thanks, was indeed running an older version of demo. After updating its working.
