### ISSUE TITLE
After using server sent events, Oak does not shutdown gracefully.

### ISSUE THREAD

**Issue by cowboyd** [oakserver/oak#593]
Using a modified version of the example at https://oakserver.github.io/oak/sse I added an abort controller to shut down the Oak server when the user hits CTRL-C. The problem is that on abort, any open SSE targets are not closed, and so the server hangs forever.

```ts
import { Application, Router } from "https://deno.land/x/oak@v12.1.0/mod.ts";
import type { ServerSentEventTarget } from "https://deno.land/x/oak@v12.1.0/mod.ts";

let controller = new AbortController();
let { signal } = controller;
let abort = () => { controller.abort() };

let app = new Application();
let router = new Router();

let targets = new Set<ServerSentEventTarget>();

// without this code, server hangs forever
signal.addEventListener("abort", () => {
  for (let target of targets) {
    targets.delete(target);
    target.close()
      .then(t => console.log('closed', t))
      .catch(e => console.error('close error', e));
  }
})

router.get("/", ({ response }) => {
  response.body = `<html><body><script type="module">
window.source = new EventSource("/sse");
window.onmessage = (msg) => console.log(msg);
window.onnerror = (err) => console.log(err);
window.onclose = (event) => console.log(close);
</script>
</body></html>`;
})

router.get("/sse", (ctx) => {
  let target = ctx.sendEvents();

  targets.add(target);
  target.dispatchMessage({ hello: "world" });
});

app.use(router.routes());

Deno.addSignalListener('SIGINT', abort);

await app.listen({ port: 8080, signal });

Deno.removeSignalListener('SIGINT', abort);

console.log('done!');
```

I was able to work around this by capturing the targets, and then manually closing them. Unfortunately, there is no way to work around this with a middleware because the `#sse` field is private.

**Comment by kitsonk** [comment]
Yeah, I guess targets should be tracked and closed when the server closes.

**Comment by cowboyd** [comment]
Another thing I noticed was that the promise returned by `target.close()` does not resolve, so if I had code that was trying to `await` them on shutdown, it would also hang. The only sequence that worked was to call `target.close()`, drop the promise, and then `await` the result of `app.listen()`

I could try and have a look at it, but would need some direction on where to start.
