### ISSUE TITLE
Uncaught TypeError if ServerSentEvent is created without optional EventInit

### ISSUE THREAD

**Issue by KyleJune** [oakserver/oak#598]
Details can be found here: https://github.com/denoland/deno_std/issues/3355

Once the bug is fixed, the version of std used by oak will need updated to resolve the issue for oak.

**Comment by KyleJune** [comment]
The reason I didn't have this issue before on 12.0.0 was that the ServerSentEvent call signature required a body argument of type unknown and I happened to make it null. JSON.stringify will stringify null but won't stringify undefined.

**Comment by KyleJune** [comment]
This is fixed in std@0.186.0

**Comment by kitsonk** [comment]
std has been updated.
