### ISSUE TITLE
Globally catch body parsing errors

### ISSUE THREAD

**Issue by soulchild** [oakserver/oak#604]
How would I go about catching errors occuring from the code below (i.e. JSON parsing errors) without having to wrap all calls to `ctx.request.body` in a try/catch handler? This should not end up as an Internal Server Error but rather like a 400 or 422 HTTP error.

Currently, oak's request handler throws a generic `SyntaxError` which is not easily distinguishable in a global error handler. Express's body-parser makes it easy by throwing [http-errors](https://www.npmjs.com/package/http-errors).

```ts
const requestBody = await ctx.request.body({ type: 'json' }).value;
```

Of course, I could just wrap this together with a try/catch in a function, but I thought there might be an easier, built-in way. :wink:

**Comment by kitsonk** [comment]
No it doesn't... catching them globally doesn't make sense, but changing it from throwing a SyntaxError to one of the HTTP errors, but what is the most appropriate response? A `400 Bad Request`?

**Comment by soulchild** [comment]
I suppose a 400 Bad Request would be appropriate. That's also what express body-parser [returns](https://github.com/expressjs/body-parser#entity-parse-failed). 

Looking at the body-parser docs, I realized that there's all kinds of stuff which could go wrong during body parsing (limits, wrong content encoding, wrong charsets, etc.) Maybe there's other stuff checked by oak's parser which could then also return more appropriate http-errors. I just started using oak yesterday, so I just don't know. 😀

**Comment by denizdogan** [comment]
I was just thinking about this exact thing.

If the client says it's sending multipart/form-data, and the server insists on parsing it as JSON, wouldn't it make more sense to return [415 Unsupported Media Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415)?

**Comment by soulchild** [comment]
I don't know the philosophy behind oak's built-in parser, but I feel that it's intentionally designed to be as minimalistic as possible and does not aim at being a full-blown express body-parser replacement. 

The alternatives like [body_parser](https://deno.land/x/body_parser@v0.0.1) and [deno-body-parser](https://github.com/mayankchoubey/deno-body-parser) are either unmaintained, have little to no traction and/or offer some questionable features like `xmlToJson()` (which is implemented via regular expressions 🙈).

Personally, I'd prefer an official or built-in solution for body parsing. Just like express-body-parser is also maintained by the express team AFAIK.

**Comment by denizdogan** [comment]
@soulchild Definitely agree with you there. And I also think it should be up to the Deno community to provide these things, instead of expecting the "Oak core team" to do it!

**Comment by kitsonk** [comment]
A body parser might make sense in `std/http` for Deno, but in a lot of ways, I suspect it might be hard to have it not have enough opinions and the web standard `Request` provides enough methods to do most common things (which wasn't the case long ago in Deno's history, therefore a richer body parser in oak).  If there was in std, it would have to be pretty good and flexible for oak to adopt it, and at the moment and at the moment, I can't see me contributing one back, to std like oak has for a lot of `std/http` recently, but I will think about it.

To be honest, the body parser in oak is a bit of a mess, as it has been iterated on without a major rewrite for several years. Not totally happy with it at the moment.

I started looking at the errors body parser threw and have started raising HTTP errors instead. 400 seems the most appropriate in most cases. I will consider if 415 is appropriate anywhere.
