### ISSUE TITLE
multipart/form-data headers in body

### ISSUE THREAD

**Issue by eikooc** [oakserver/oak#629]
Hi. I was wondering if it would be possible to support headers in the content "body parts". Right now only a single header is parsed out, the `Content-Type` header, but I would like support for having arbitrary headers just like on the "root" HTTP request.

According to [RFC 1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) it looks like this feature is part of the spec.

Would you accept PRs for this feature?

**Comment by kitsonk** [comment]
From the specification:

> The only header fields that have defined meaning for body parts are those the names of which begin with "Content-". All other header fields are generally to be ignored in body parts. Although they should generally be retained in mail processing, they may be discarded by gateways if necessary. Such other fields are permitted to appear in body parts but should not be depended on. "X-" fields may be created for experimental or private purposes, with the recognition that the information they contain may be lost at some gateways.

As indicated from the spec, only `Content-*` headers are required to be maintained by gateways, the rest can be stripped. With a recent refactor, oak primarily relies about the web standard `FormData` for multi-part forms and in that case the only headers that "matter" are `Content-Type` and `Content-Disposition`. 

Given those two things, arbitrary headers is not something that would a) be easy nor b) something we would want to support or maintain.
