### ISSUE TITLE
TypeError - ctx.request.body is not a function error while deploying to deno

### ISSUE THREAD

**Issue by sweekark** [oakserver/oak#634]
![image](https://github.com/oakserver/oak/assets/3829871/af5f58d7-408f-4730-a891-8e8ba0595ac0)

getting this error while hosting on deno on local its working fine

[uncaught application error]: TypeError - ctx.request.body is not a function

**Comment by sweekark** [comment]
https://www.loom.com/share/6eb71cd91db247d0b39e7fc39e8bf7cc?sid=e26817c5-ab0d-45f3-87fb-0eadc8e4e9f7

**Comment by kitsonk** [comment]
This is expected. You deployed V13 of oak which changed the `request.body` API.  If you don't want to use the breaking changes in v13, don't use v13, use an older version.
