### ISSUE TITLE
More typing on Request and Response object?

### ISSUE THREAD

**Issue by chulucninh09** [oakserver/oak#646]
Hi, can we add generic typing to `Context` object to allow developers define `Request` and `Response` body? This is useful and important for typescript check.

I'm willing to PR in this matter also

**Comment by kitsonk** [comment]
Can you provide a use case of what problems you are experiencing that you think this will solve?

**Comment by chulucninh09** [comment]
For example, when I want to design the interface to handler the request with specification as follow:

```
POST /carts
Body schema:
id: id of the item
quantity: quantity of the item
```

Right now, I have no type hint when extracting `id` and `quantity` from `ctx.request`, which prevent me from leverage typescript linting capability in development

**Comment by kitsonk** [comment]
Given that the format or validity of a body isn't checked at any point, strongly typing the body at the oak level doesn't make sense.  People could post _anything_ to the endpoint, and if the implementor doesn't do any checking or enforcement, then all sorts of runtime errors could be caused that an implementor should consider. Having uncertainty in the types is a very good thing in this case.

Something like a schema validating middleware could be implemented which would ensure that the body conforms to expectations and then only passes those requests the conform to an inner handler/middleware.

It could could look something like this:

```ts
request.post("/endpoint", validate(schema, (requestBody, ctx, next) => {
  // body could be strongly typed based off of schema
});
```

But something like this is outside of the scope oak project, but a great idea for the wider community.

**Comment by chulucninh09** [comment]
Yes, normally we also add middleware to validate request. After that, we want to ensure developers handle the validated body correctly, at least in schema level. This is not possible right now and we have to do manual/integration testing instead of just simply run light-weight linting.

For example:
```javascript
router.post("/endpoint", validate).post("/endpoint", (context: TypedContext<TypedRequest, TypedResponse>) => {
   // Typescript helps here to ensure correct extraction and response body
}
```
