### ISSUE TITLE
request.body.text() causes error on localhost

### ISSUE THREAD

**Issue by AdrianMargel** [oakserver/oak#647]
When I try to use `request.body.text()` locally it produces an error. However when I attempt to run the same code on Deno Deploy it works fine without issue.

This makes development using Deno Oak extremely difficult without any way to test locally.

I suspect this may be an issue with the server using a different version of Oak but I'm unclear on what could cause that mismatch, or how to fix it.

The following is a simplified example to reproduce the problem. The full code where I encountered this issue can be found here: https://github.com/AdrianMargel/question-spinner/blob/main/index.js#L28
___
Deno Code:
```
import { Application, Router, Status } from "https://deno.land/x/oak/mod.ts";

const app=new Application();
const router = new Router();
router.post('/test', async (ctx) =>{
	let body=await ctx.request.body.text();
	console.log(body);
	ctx.response.status=Status.OK;
});
app.use(router.allowedMethods());
app.use(router.routes());

await app.listen({ port: 8000 });
```
Called with the following from the browser:
```
fetch("/test",{
	method: "POST",
	body:JSON.stringify({
		test:"hello world",
	})
});
```
Produces the following error in the console:
```
[uncaught application error]: TypeError - ctx.request.body.text is not a function

request: { url: "http://localhost:8000/test", method: "POST", hasBody: true }
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at <redacted>/index.js:6:34
    at dispatch (https://deno.land/x/oak@v12.1.0/middleware.ts:41:13)
    at https://deno.land/x/oak@v12.1.0/router.ts:1232:20
    at dispatch (https://deno.land/x/oak@v12.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v12.1.0/middleware.ts:44:12)
    at dispatch (https://deno.land/x/oak@v12.1.0/router.ts:1238:22)
    at dispatch (https://deno.land/x/oak@v12.1.0/middleware.ts:41:13)
    at allowedMethods (https://deno.land/x/oak@v12.1.0/router.ts:686:13)
    at dispatch (https://deno.land/x/oak@v12.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v12.1.0/middleware.ts:44:12)
```
I am running on Windows 10 with Deno version 1.41.3 installed.

I appreciate any insight into this.

**Comment by kitsonk** [comment]
> ```
> import { Application, Router, Status } from "https://deno.land/x/oak/mod.ts";
> ```

What happens when you change this to locally:

```
import { Application, Router, Status } from "https://deno.land/x/oak@14.2.0/mod.ts";
```

**Comment by AdrianMargel** [comment]
Interesting, explicitly stating the version fixes the issue. I wonder why the default version would be different between the server and my localhost though.

Thank you kindly. I'm glad it turned out to be simple to solve.

**Comment by kitsonk** [comment]
> I wonder why the default version would be different between the server and my localhost though.

This is why using unversioned specifiers from `deno.land/x` is dangerous (any why there is the [note about it in the README](https://github.com/oakserver/oak/?tab=readme-ov-file#oak)). You likely had an older version of oak cached locally. A reload (`-r`) would also have likely fixed it locally.
