### ISSUE TITLE
How to gracefully exit, when Bun Server does not adhere to AbortSignal?

### ISSUE THREAD

**Issue by Gakai** [oakserver/oak#651]
## Problem

`await app.listen({ port: 9000, signal: shutdownSignal });` never resolves even though the signal is aborted.

I use bun 1.1.3 and oak 14.2.0

Maybe this difference is the reason?
Bun Server: https://github.com/oakserver/oak/blob/c8e535fdec9bb8155cdbf92c2ad8172ac1b9e893/http_server_bun.ts#L215-L216
Native Server: https://github.com/oakserver/oak/blob/c8e535fdec9bb8155cdbf92c2ad8172ac1b9e893/http_server_native.ts#L100-L103

**Comment by Gakai** [comment]
We could solve the problem in our application by providing a custom `Server` implementation.
I think it would be reasonable to add this change to the default implementation as well.

The relevant difference to the `http_server_bun.ts` implementation is that we added an abort signal listener in the `ReadableStream.start` function, that closes the stream AND the server:

```ts
listen(): Listener | Promise<Listener> {
    if (this.#server) {
        throw new Error("Server already listening.");
    }
    const { onListen, hostname, port, signal } = this.#options;
    const tls = isServeTlsOptions(this.#options)
        ? { key: this.#options.key, cert: this.#options.cert }
        : undefined;
    const { promise, resolve } = createPromiseWithResolvers<Listener>();
    this.#stream = new ReadableStream<BunRequest>({
        start: (controller) => {
            this.#server = Bun.serve({
                fetch(req, server) {
                    const request = new BunRequest(req, server);
                    controller.enqueue(request);
                    return request.response;
                },
                hostname,
                port,
                tls,
            });
            signal?.addEventListener("abort", () => {
                controller.close();
                this.close();
            }, { once: true });
            {
                const { hostname, port } = this.#server;
                if (onListen) {
                    onListen({ hostname, port });
                }
                resolve({ addr: { hostname, port } });
            }
        },
    });
    return promise;
}
```

**Comment by olee** [comment]
Btw: The nodejs server implementation seems to suffer from the same issue.
