### ISSUE TITLE
Use `:authority` psueod-header on HTTP/2 if available

### ISSUE THREAD

**Issue by kitsonk** [oakserver/oak#657]
> @kitsonk `:authority` is a drop in replacement for `Host`. I try to read the `Host` in a proxy that I am building right now and it seems I'm unable to do so. Despite `alpnProtocols: ["h2", "http/1.1"]` by default, `context.request.headers` does not contain `:authority` and modern browsers don't send the `Host` header anymore. `context.request.headers.get(":authority")` is undefined, but I can confirm it being set in the browser via DevTools.

_Originally posted by @martin-braun in https://github.com/oakserver/oak/issues/571#issuecomment-2119201626_

**Comment by kitsonk** [comment]
I looked into this, `Host` will likely still be set when the connection is HTTP/1 to the server.  If the connection is HTTP/2 then the `:authority` pseudo-header will be set from a browser.  oak should look for the pseudo-header.  This is distinct from #571 so I have split it out.

The additional problem though is that either Deno does not process the header. `context.request.headers` simply takes what Deno offers to it, nothing more nothing less.  I am not sure if you are talking about Deno runtime or Deno Deploy (or some other runtime) but the header being missing should addressed with the runtime engine.

**Comment by martin-braun** [comment]
@kitsonk Thanks for the clarification and the split, nothing to be concerned about. So you say Deno itself doesn't provide the headers? Could you please link me to the relevant code that causes this limitation? I would be happy to bubble the issue up.

And yes, you are correct about your findings, and most, if not all, common browsers switched to HTTP/2 as far as I can tell.

**Comment by kitsonk** [comment]
The headers on the request are from the server request:

https://github.com/oakserver/oak/blob/77d50d6993becbee9a9eaea1eca24ab10cc31fb8/request.ts#L70-L72

And the server request used for Deno uses the headers from the `Request` object provided:

https://github.com/oakserver/oak/blob/77d50d6993becbee9a9eaea1eca24ab10cc31fb8/http_server_native_request.ts#L65-L67

The indirection is there is because of the evolution of Deno HTTP since 2018 and the need to support multiple runtimes.

**Comment by kitsonk** [comment]
Closed in 0c8b8daac0d82aef7fe2487d4bf9d5e50bcc6c0d
