### ISSUE TITLE
Error handling doesn't work

### ISSUE THREAD

**Issue by t3hk0d3** [oakserver/oak#661]
Application crashes after calling an HTTP endpoint without expected JSON input.

```
error: Uncaught (in promise) BadRequestError: Unexpected end of JSON input
  return new errors[Status[status] as ErrorStatusKeys](message, options);
         ^
    at createHttpError (https://jsr.io/@oak/commons/0.11.0/http_errors.ts:211:10)
    at Body.json (https://deno.land/x/oak@v16.1.0/body.ts:152:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

Wrapping it into another middleware doesn't work.

**Comment by kitsonk** [comment]
I reproduced sending an invalid JSON body to the latest version of oak and the behaviour was exactly as expected, when attempting to do `ctx.body.json()` as part of a middleware function it threw and returned a `400 Bad Request` to the client and the server continued to process requests.

You will need to provide a full reproduction or more details.

**Comment by t3hk0d3** [comment]
@kitsonk I've managed to reproduce it with following code:

```typescript
import * as Oak from "https://deno.land/x/oak@v16.1.0/mod.ts";

const app = new Oak.Application();

app.use((ctx) => ({
    beep: ctx.request.body.json(),
}))


await app.listen({port: 3000});
```

**Comment by t3hk0d3** [comment]
Seems like changing to `await beep: ctx.request.body.json()` fixes the problem.

**Comment by kitsonk** [comment]
When you queue a microstask, that occurs outside of the oak handling and therefore the behaviour you are experiencing is totally expected.  In order to have oak handle the errors, the error either needs to be thrown synchronously within the handler or the handler needs to return a promise that will be rejected with any error.

This is working as expected and unactionable.

**Comment by t3hk0d3** [comment]
@kitsonk well, if you just grab promise (through `ctx.request.body.json()`) inside handler, but not necessary `await` it - it can trigger error too.

app.use((ctx) => {
    const data = ctx.request.body.json();
    if (somethingSomething) {
          processData(await data);
    }
})


await app.listen({port: 3000});

**Comment by kitsonk** [comment]
The example provided is syntactically incorrect.  You cannot await inside an non-async function.

> In order to have oak handle the errors, the error either needs to be thrown synchronously within the handler or the handler needs to return a promise that will be rejected with any error.

As I stated above, grabbing the promise but not having promise cause a rejection of the promise returned by the handler is the same thing. This isn't an issue with oak, it is a mis-understanding of how asynchronous process work in JavaScript.

**Comment by t3hk0d3** [comment]
> The example provided is syntactically incorrect. You cannot await inside an non-async function.

That was an illustrative example. `somethingSomething` won't compile either.

> As I stated above, grabbing the promise but not having promise cause a rejection of the promise returned by the handler is the same thing. This isn't an issue with oak, it is a mis-understanding of how asynchronous process work in JavaScript.

Problem is that it kills process, because promise is rejected outside request handler scope.

IMO its not an oak's fault, but it would be nice if there were a safeguard.

**Comment by BlackAsLight** [comment]
> As alternative have request().body().json() return null if body is missing, instead of exception (i am realistic here - despite sounding logical behavior to me it would be too drastic change of the API contract).

`request.body().json().catch(() => null)`

**Comment by kitsonk** [comment]
> As alternative have `request().body().json()` return `null` if body is missing, instead of exception (i am realistic here - despite sounding logical behavior to me it would be too drastic change of the API contract).

Then users would not be able to distinguish between an empty body and a malformed body, which may very well impact what type of response people would want to send back (or further diagnostics to the client).

Properly handling the errors in the handler is the right approach.
