### ISSUE TITLE
is there anyway to get GET request query params?

### ISSUE THREAD

**Issue by yeukfei02** [oakserver/oak#67]
I ask this question because in the readme I only see `c.params` and `c.request.body()`...
For now how can I retrieve query params?

Thanks.

**Comment by kitsonk** [comment]
The requested URL is parsed and available as a WHATWG URL (see: https://developer.mozilla.org/en-US/docs/Web/API/URL) on `ctx.request.url`. The "query params" are `ctx.request.url.searchParams`.

I should link off to the documentation at MDN in the README I suspect.

**Comment by yeukfei02** [comment]
I suggest in future can be something like this:
path param: `c.params`
query param: `c.query`
body: `c.body`

This would be easier to remember.
Thanks.

**Comment by kitsonk** [comment]
As stated in the README, we try not to copy and duplicate information. URL provides a much better, and browser standard, interface to the requested URL.

**Comment by kitsonk** [comment]
I've update the documentation in 132f38ac62954bc4f903be71d46cb2ad454abb91 for clarity, including adding a FAQ on the subject.
