### ISSUE TITLE
Body cannot be re-read which is poor DX

### ISSUE THREAD

**Issue by JohannesMerkt** [oakserver/oak#671]
Hi, 
I have a middleware that checks the JSON body before passing the request to the actual route handler that also wants to access the JSON body. However that throws an error in my route handler, that the body has already been consumed and I cannot access the body anymore. With the regular Request type I could clone the request in the middleware to ensure that the next handler can also access the request body but since oak uses a proprietary request type I cannot do that. 

How can I access the Request Body JSON from multiple Handlers?

**Comment by khoaln** [comment]
I got the same issue after upgrading oak. I had to create a middleware to consume the request's body and put it in the context's state. Maybe it's not ideal, but at least it works for me atm so that I can continue with the development while watching answers/updates from oak team.

**Comment by JohannesMerkt** [comment]
Here is my temporary solution:
In each middleware that expects body usage afterwards I did
```ts
const data = await request.body.json();
request.body.json = () => data;
```

it overrides the json() function with my own function that returns the data once it has already been consumed.

**Comment by kitsonk** [comment]
I suspect it is a sort of enhancement/bug, in that the behaviour aligns to the fetch `Request` API, but people aren't expecting to have to manage the consumption of the body, which is a valid concern.

The "fix" would be to memoize the body read. I will try to take a look this week.
