### ISSUE TITLE
error: npm package '@jsr/oak__oak' does not exist (deno 2.0.0)

### ISSUE THREAD

**Issue by andersbc** [oakserver/oak#676]
With deno 2.0.0:

```sh
deno add jsr:@oak/oak
```
I get this:

```sh
Add jsr:@oak/oak@17.1.0
error: npm package '@jsr/oak__oak' does not exist.
```
I was trying to follow this tutorial
https://docs.deno.com/runtime/tutorials/how_to_with_npm/vue/

**Comment by Ethan-Hill** [comment]
Same here with me

**Comment by andersbc** [comment]
OK, this seems to be related to this issue in deno (not the oak package):
https://github.com/denoland/deno/issues/26119

Workaround: before running `deno add ...` just create an empty `deno.json` file, e.g. `touch deno.json`. It worked for me.

Closing the issue.
