### ISSUE TITLE
Error: npm package '@jsr/oak__oak' does not exist.

### ISSUE THREAD

**Issue by Mr-Unforgettable** [oakserver/oak#677]
**Oak version:** 17.1.0
**Deno version:** 
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

**Description:**
When I am trying to add the jsr:@oak/oak into my dependency list in package.json using **command:**``deno add`` logs the following message on my terminal.
```
❯ deno add jsr:@oak/oak
Add jsr:@oak/oak@17.1.0
error: npm package '@jsr/oak__oak' does not exist.
```
Here is my package.json file:
```
{
  "name": "dino-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "deno task dev:api & deno task dev:vite",
    "dev:api": "deno run --allow-env --allow-net api/main.ts",
    "dev:vite": "deno run -A npm:vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@oak/oak": "npm:@jsr/oak__oak@^17.1.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.11.1",
    "@types/react": "^18.3.10",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.2",
    "eslint": "^9.11.1",
    "eslint-plugin-react-hooks": "^5.1.0-rc.0",
    "eslint-plugin-react-refresh": "^0.4.12",
    "globals": "^15.9.0",
    "typescript": "^5.5.3",
    "typescript-eslint": "^8.7.0",
    "vite": "^5.4.8"
  }
}
```

**Steps to reproduce:** 
1. Install latest version of deno in your box. 
2. Try creating a dummy project and add the ``jsr:@oak/oak`` as a dependency in the package.json file via ``deno add`` command

**Result:**
❯ deno add jsr:@oak/oak
Add jsr:@oak/oak@17.1.0
error: npm package '@jsr/oak__oak' does not exist.

**Expected output:**
It should output some sort success message.

**Comment by Mr-Unforgettable** [comment]
Hey, I was able to fix my issue for the package being not install into my package.json. I had to reinstall deno in my WSL system and it fixed the issue.

**Comment by kitsonk** [comment]
Duplicate of #676
