### ISSUE TITLE
"use with deno" command seems to be incorrect

### ISSUE THREAD

**Issue by froggy-jpg** [oakserver/oak#688]
command on the website:
![image](https://github.com/user-attachments/assets/ff649580-e3c9-41b1-948d-0b0f618f2880)
output:
![image](https://github.com/user-attachments/assets/92c6b17c-e191-4ebb-94e9-0b47c97176ab)

**Comment by BlackAsLight** [comment]
Can you link to "the website" in question?

**Comment by froggy-jpg** [comment]
of course, my bad
here's the link: https://oakserver.org/

**Comment by kitsonk** [comment]
Fixed on the website.
