### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by brianraila** [oakserver/oak#69]
Trying to serve static files using this code snippet in the README.md yield the following error.

 `      
               app.use(async (context) => {
              await send(context, context.request.path, {
                   root: "./static",
                   index: "index.html",
                   });
          });`

Error.
`error TS2339: Property 'path' does not exist on type 'Request'.
  await send(context, context.request.path, {`

**Comment by brianraila** [comment]
Figured it was an issue with the documentation, the snippet should be changed 


`context.request.url.pathname`

**Comment by kitsonk** [comment]
The documentation/examples need to be updated as master contains a breaking change, which you figured out.  Apologies.
