### ISSUE TITLE
Cookies not working

### ISSUE THREAD

**Issue by JWebCoder** [oakserver/oak#74]
Cookies are not working.

Example:
```javascript
.get(
    '/setCookie',
    (context) => {
      context.cookies.set('auth', JSON.stringify({count:1}))
      context.response.body = 'cookie set'
    }
  )
  .get(
    '/getCookie',
    (context) => {
      context.response.body = 'hello' + context.cookies.get('auth')
    }
  )
```

This doesn't return the cookie value on the second request.

**Comment by kitsonk** [comment]
Could you provide more information, like what version of Deno you are using and what of oak?

**Comment by JWebCoder** [comment]
Hello. Deno 0.49 oak is the latest version.

**Comment by kitsonk** [comment]
Multiple cookie headers was fixed in Deno 1.0.0-rc2 I believe.

**Comment by JWebCoder** [comment]
I can test it again using the new rc. I'll give you some feedback.

**Comment by JWebCoder** [comment]
Retested with Deno 1.0.0, all working. Closing the issue.
