### ISSUE TITLE
Bodyless response

### ISSUE THREAD

**Issue by bartlomieju** [oakserver/oak#8]
I'm developing simple API with oak, I want to return simple 404 response.
```
function notFound(context: Context) {
    context.response.status = Status.NotFound;
}
```
code above causes server to hang because there is no body in response.

If you do:
```
function notFound(context: Context) {
    context.response.status = Status.NotFound;
    context.response.body = "";
}
```
everything's working correctly.

Is this a bug or did I forget about something?

**Comment by kitsonk** [comment]
Yeah it presumes there is always a body, which isn't a good assumption.

**Comment by bartlomieju** [comment]
I did some digging and it seems oak is handling empty body properly:
```ts
async listen(addr: string): Promise<void> {
    const middleware = compose<Context<S>, S>(this._middleware);
    const server = this._serve(addr);
    for await (const request of server) {
      const context = new Context<S>(this, request);
      await middleware(context);
      console.log('post middleware');
      const srvRes = context.response.toServerResponse();
      console.log('post src res', srvRes);
      await request.respond(srvRes);
      console.log('responded');
    }
  }
```
If you respond with empty body `responded` is printed to console, I suspect problem is in `serve` from `deno_std`. TBC

**Comment by bartlomieju** [comment]
Sorry @kitsonk, this is issue from `deno_std`. https://github.com/denoland/deno_std/pull/52

**Comment by kitsonk** [comment]
Yeah. I had narrowed it down to there too. Let's leave this open, because will need to bump the dep once resolved.

**Comment by kitsonk** [comment]
Actually we can set content-length to 0 in oak.

**Comment by bartlomieju** [comment]
I think it's a good idea, will get it working for now. I'll see to proper handling in standard lib.

**Comment by kitsonk** [comment]
Yeah, I think in the `toServerResponse` is the content-length is missing and there is no `content-encoding` and no body, the setting it should be fine.  I think if there is user set `content-encoding` then they may be doing something like streaming a file.

Based on that, it is arguable if `http` should `std` should actually support it as really it should leave all those concerns up to implementors.

**Comment by bartlomieju** [comment]
Agreed, but as we can see now if body is not supplied server just hangs, I believe `http.serve` should handle such cases nevertheless instead of hanging. I'll just implement it anyway 👍
