### ISSUE TITLE
Proxy middleware

### ISSUE THREAD

**Issue by BevanR** [oakserver/oak#80]
I'd like to use Oak to proxy API requests onto another server, while overriding some with other responses and/or serving up local static assets for others. A proxy middleware would be nice.

**Comment by asos-craigmorten** [comment]
I'm planning on porting [express-http-proxy](https://www.npmjs.com/package/express-http-proxy) over for my [Opine](https://github.com/asos-craigmorten/opine) project. It wouldn't be a stretch to map the `(req, res, next) => {}` interface to the koa style `(ctx) => {}` so can create an Oak wrapper if that would be useful? Don't know if someone is already working on this.

**Comment by asos-craigmorten** [comment]
Heh, remembered had said the above today so thought should probably make good one my word (albeit a couple of months later...). Behold [oak-http-proxy](https://github.com/asos-craigmorten/oak-http-proxy):

- https://github.com/asos-craigmorten/oak-http-proxy
- https://deno.land/x/oak_http_proxy@1.0.3
- https://nest.land/package/oak-http-proxy

**Comment by kitsonk** [comment]
I'm going to close this, as I looked into it at one point and it was going to get complicated quickly, and so @asos-craigmorten had the desire, so I would suggest others investigate that in the future.

@asos-craigmorten if you wanted to not have the overhead of maintaining is separately, it would be a welcome contribution to `oak/middleware` as well.
