### ISSUE TITLE
Is there any API documentation available?

### ISSUE THREAD

**Issue by flovogt** [oakserver/oak#84]
Hi team,
great work! I am getting started with oak these days and looking for some materials, like API documentation. Is there any official API documentation available?
All the best,
Florian

**Comment by kitsonk** [comment]
The README, and to a degree the /docs directory which is also https://oakserver.github.io/oak, plus all the code has inline documentation, and you can find auto generated documentation by clicking on the "deno doc" badge in the README, plus also the Deno's CLI supports auto documentation:

```shell
$ deno doc https://deno.land/x/oak/mod.ts
```

Not sure what else needs to be done.

**Comment by flovogt** [comment]
@kitsonk Thanks a lot. I missed the badge on the README directing to https://doc.deno.land/https/deno.land/x/oak/mod.ts. 
That is what I was looking for. Maybee the link could also be placed in the README a second time as text.
