### ISSUE TITLE
Property 'params' does not exist on type 'Context<Record<string, any>>'

### ISSUE THREAD

**Issue by liron-navon** [oakserver/oak#86]
The documentation shows "params" as a variable attached to the "context", but the type definition is missing the params for some reason, so the question is, are there two different types of context in the module? why does using context without explicit type works, but when giving an explicit type it fails?

using deno 1.0

```
import { Context, Router } from "https://deno.land/x/oak/mod.ts";

const router = new Router();

// Breaks when compiling...
router.get('/', (ctx: Context) => {
  console.log(ctx.params);
})

// Doesn't break when compiling
router.get('/', ctx => {
  console.log(ctx.params);
})

```

Seems like the issue is simply that the field doesn't exist on the Context class, so to fix it we just need to add "params: Record<string, any>" to the class in this file...
https://github.com/oakserver/oak/blob/master/context.ts

**Comment by liron-navon** [comment]
Ok, I fucked up and should use the "RouterContext" instead

**Comment by keb** [comment]
Also got confused by this. I wonder if the docs can be more clear about TypeScript usage.
