### ISSUE TITLE
error: Uncaught ReferenceError: ErrorEvent is not defined

### ISSUE THREAD

**Issue by KhanhKitin** [oakserver/oak#87]
`export class ApplicationErrorEvent<S extends State> extends ErrorEvent {
                                                            ^
 at application.ts:78:61`

**Comment by michaelwilcox** [comment]
[issue 76](https://github.com/oakserver/oak/issues/76), `deno upgrade --version 1.0.0-rc3` resolved this error.

**Comment by kitsonk** [comment]
Correct, you need to use Deno version `1.0.0-rc3` or later.
