### ISSUE TITLE
value is coming as Uint8Array

### ISSUE THREAD

**Issue by berkaycimsir** [oakserver/oak#88]
I am trying to make post request for login and, sending body with postman. But request.body().value returns a Uint8Array, because of this, i can't handle username and passoword.

Here is how i sent the data by using postman
![Ekran Alıntısı3](https://user-images.githubusercontent.com/47090177/82129941-711d6e00-97cf-11ea-8b0d-75a3ec1508de.JPG)

Here is my code
![Ekran Alıntısı](https://user-images.githubusercontent.com/47090177/82129901-197f0280-97cf-11ea-8b46-d51366e4f643.JPG)
![Ekran Alıntısı1](https://user-images.githubusercontent.com/47090177/82129904-1ab02f80-97cf-11ea-8801-494130fecb36.JPG)

**Comment by kitsonk** [comment]
The request does not contain a media type that oak currently understands for auto transform of the body.  You can:

- Set a content type (e.g. `multipart/form-data` if that is what the payload is)
- If the content type is being set, but isn't returning what you want, you can use the `contentTypes` option when getting the body as per the [documentation](https://github.com/oakserver/oak#request) for `.body()`.
- Decode the Uint8Array to a string yourself using `TextDecoder`

**Comment by berkaycimsir** [comment]
It works for me! Thanks
