### ISSUE TITLE
Route handlers with query params not matching

### ISSUE THREAD

**Issue by michaelwilcox** [oakserver/oak#90]
Hi,

Apologies if am doing this incorrectly. Noticing route handlers with query params are not matching.

Can reproduce this through `examples/routingServer.ts`:

1. Remove the code block 40-42:

```ts
  // .get("/book", async (context) => {
  //   context.response.body = Array.from(books.values());
  // })
```
2. Query the server (am using postman): ```GET http://127.0.0.1:8000/book?id=1234```
3. Observe that the server returns ```404 Not Found```

**Comment by kitsonk** [comment]
@michaelwilcox why is there an expectation that this would work?  It isn't documented anywhere that this would work and I am not aware of other middleware routers that match routes based on the query string.  If you wanted to change the server to handle it better, you would do it in the middleware, something like:

```ts
.get("/book", async (context) => {
    const id = context.request.url.searchParams.get("id");
    if (id) {
      if (books.has(id)) {
        context.response.body = books.get(id);
      } else {
        return notFound(context);
      }
    } else {
      context.response.body = Array.from(books.values());
    }
  })
```

**Comment by michaelwilcox** [comment]
Ah this is my fault, sorry! I was confusing query params ( `?foo=bar` ) with route params ( `/endpoint/:foo` -> `/endpoint/bar` ). Quarantine has my brain all messed up.

Thank you for the middleware example answer and this awesome library!
