### ISSUE TITLE
Cannot get query string params

### ISSUE THREAD

**Issue by parnpresso** [oakserver/oak#95]
👋🏼Hi there, I tried to get a query string params from the context but context didn't have a query string params data. Or Is there a way to get a query string params?

## Reproducing steps
Start a server with the code below and curl to `localhost:8000?name=xxx`

```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const router = new Router();
router
  .get("/", (context: any) => {
    // 🚨No query string params in context
    console.log(context)
  })

const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

**Comment by gjuoun** [comment]
You need write a middleware.
or just use this [https://github.com/gjuoun/oak-query-parser](https://github.com/gjuoun/oak-query-parser)

**Comment by kitsonk** [comment]
Or just use `context.request.url` as per the FAQ: https://oakserver.github.io/oak/FAQ
