### ISSUE TITLE
do i need to async await to get request.body() ?

### ISSUE THREAD

**Issue by joeraygme** [oakserver/oak#96]
Hi I'm working with this example: https://github.com/oakserver/oak/blob/master/examples/postGetServer.ts

when i implement it i seem to need this in order for it to return the body in the response:

```
  .put("/book", async ({ request, response }) => {
    if (!request.hasBody) {
      response.status = 400;
      response.body = { msg: "Invalid data" };
    } else {
      response.body = { msg: "Success", data: await request.body() };
    }
  });
```

should the example work as expressed and I'm doing something wrong?
specifically: async / await

**Comment by kitsonk** [comment]
@joeraygme yes the example is incorrect.  It was a contribution that I didn't check properly enough.

**Comment by kitsonk** [comment]
Upon reflection, the `putSetServer.ts` wasn't a good example.  I have added to the `examples/routingServer.ts` a functional example of taking a posted document and caching it in memory.

**Comment by joeraygme** [comment]
very nice example, thank you very much
