### ISSUE TITLE
Post Request returning unit8array instead of json

### ISSUE THREAD

**Issue by devYusuf** [oakserver/oak#97]
I built an api with oak but kept returning a unit8array , please how do I convert it it json

**Comment by kitsonk** [comment]
This is well explained in the [request](https://github.com/oakserver/oak#request) `.body` documentation.  It is likely that your `POST` is missing a valid content type, so the body is not automatically parsed, so either set a valid JSON content type header in your request, or convert the Uint8Array to a string (likely using `TextDecoder`) and then JSON parse the string.
