### ISSUE TITLE
Q:How to get query parameters ?

### ISSUE THREAD

**Issue by ToWeLong** [oakserver/oak#99]
I checked the document, but I didn't find out how to get the query parameters 
![Snipaste_2020-05-20_17-03-25](https://user-images.githubusercontent.com/41502558/82427563-d9b06780-9abb-11ea-8ce9-1a616df88bd0.png)

**Comment by FraserHamilton** [comment]
You should be able to access them like this:
``` javascript
router.get("/search", (context) => {
  const queryParams = context.request.url.searchParams;
  const name = queryParams.get("name");
  context.response.body = name;
});
```

As far as I'm aware there's not a shorthand like in koa where you can access via `context.response.query`.

**Comment by ToWeLong** [comment]
> You should be able to access them like this:
> 
> ```js
> router.get("/search", (context) => {
>   const queryParams = context.request.url.searchParams;
>   const name = queryParams.get("name");
>   context.response.body = name;
> });
> ```
> 
> As far as I'm aware there's not a shorthand like in koa where you can access via `context.response.query`.

oh,Thank you,Your method is effective！

**Comment by kitsonk** [comment]
As stated, `ctx.request.url.searchParams` and is already addressed in the FAQs: https://github.com/oakserver/oak/blob/master/docs/FAQ.md#where-is-ctxhost-ctxpath-ctxquerystring-etc
